src/0x.ts
src/contract_wrappers/contract_wrapper.ts
src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_registry_wrapper.ts
src/contract_wrappers/token_wrapper.ts
src/types.ts
src/utils/assert.ts
src/utils/decorators.ts
src/utils/utils.ts
src/web3_wrapper.ts
test/0x.js_test.ts
test/schema_test.ts
test/token_registry_wrapper_test.ts
test/utils/order_factory.ts
test/utils/token_utils.ts
tsconfig.json

This PR:
* reduces bundle size 2.61 -> 2.33 MB (821 -> 794 kB minified)
* introduces other import format for lodash
Source: https://stackoverflow.com/a/39415662/3546986

Use different lodash import syntax which allows to include only used functions

---

package.json
src/0x.ts
src/utils/utils.ts
yarn.lock

This PR:
* Is a continuation of #83 
* Updates testrpc to the newest major version
* Fixes the tests broken by undocumented changes in the newest major version (@tcoulter)

Greenkeeper/ethereumjs testrpc 4.0.1

---

test/exchange_wrapper_test.ts

This PR:
* Assert that we don't only get a event, but we get the correct event in `subscribeAsync` tests

Assert correct event names in subscribeAsync tests

---

circle.yml
package.json

This PR:
* Starts using testrpc snapshots in CI builds, which speeds them up https://quip.com/RAMmADOXkqYB
* Changes prepublish script to prepublishOnly https://iamakulov.com/notes/npm-4-prepublish/
Those changes speed up an average test run from 8mins to 5mins.

Testrpc snapshots

---

CHANGELOG.md
src/0x.ts
src/contract_wrappers/exchange_wrapper.ts
src/utils/assert.ts
test/0x.js_test.ts
test/artifacts_test.ts
test/assert_test.ts
test/exchange_wrapper_test.ts
test/proxy_wrapper_test.ts

* Moves `zeroEx.exchange.getAvailableContractAddressesAsync` to `zeroEx.getAvailableExchangeContractAddressesAsync`
* Moves `zeroEx.exchange.getProxyAuthorizedContractAddressesAsync` to `zeroEx.getProxyAuthorizedExchangeContractAddressesAsync`

Moves exchange contract address getters to zeroEx top level

---

src/0x.ts
src/utils/signature_utils.ts
test/0x.js_test.ts

This PR:
Modifies signOrderHashAsync to parse the signatureHex string as V + R + S AND R + S + V and check both for a valid signature in order to fix the issue of different clients (and client versions) returning it in one of the two formats.

Improve signOrderHashAsync

---

src/globals.d.ts
src/utils/assert.ts
src/utils/schema_validator.ts

This PR:
* Fixes failing tests because the jsonschema type definitions does not have `$ref` field
I don't know, why it was not failing before.

Jsonschema types

---

package.json
yarn.lock

This PR:
* Stops using custom chai-bignumber fork, cause the changes were merged and the new version was released

Stop using custom chai-bignumber fork

---

src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_wrapper.ts
src/subproviders/empty_wallet_subprovider.ts
src/types.ts
test/token_wrapper_test.ts
test/utils/web3_factory.ts
yarn.lock

This PR addresses https://github.com/0xProject/0x.js/issues/119
- Removes the unnecessary assertion that a user address must be available from three 0x.js methods:
- `getBalanceAsync`
- `getAllowanceAsync`
- `_isRoundingErrorAsync`
- Added regression tests for `getBalanceAsync` and `getAllowanceAsync` to ensure this type of error does not re-occur. This was also an opportunity to support writing tests with a web3 provider that does not have any addresses which will be used to make future tests more robust.

Remove unnecessary assertions & add regression tests

---

src/contract_wrappers/token_registry_wrapper.ts
test/token_registry_wrapper_test.ts

This PR:
- Adds public method `getTokenMetadataIfExistsAsync` to TokenRegistry wrapper
- Refactors `getTokensAsync` to use `getTokenMetadataIfExistsAsync` under the hood
- Adds relevant unit tests

Add public method to TokenRegistry

---

CHANGELOG.md
src/contract_wrappers/exchange_wrapper.ts
src/types.ts
src/utils/order_validation_utils.ts
test/exchange_wrapper_test.ts
test/order_validation_test.ts

This PR:
* Adds 4 new public functions
* `zeroEx.exchange.validateFillOrderAndThrowIfInvalidAsync`
* `zeroEx.exchange.validateFillOrKillOrderAndThrowIfInvalidAsync` (calls the previous one under the hood)
* `zeroEx.exchange.validateCancelOrderAndThrowIfInvalidAsync`
* `zeroEx.exchange.isRoundingErrorAsync`

Add implementation for public order validation functions

---

package.json

This PR:
* Is a reply to today's publishing issue with 0.10.0
What happened?
`publish-release`asked me to select a tag from the list, but the newest tag was not there and I was not able to move with the arrows.
I think - it's because v0.10.0 is lexicographically less than for example 0.6.0.
This PR:
* Specifies the correct tag the same way we do it for the docs in the params of `publish-release`, so a developer doesn't need to select it. It also specifies an owner and the repo name. Two clicks less.

Specify tag and other values in the release script

---

src/types.ts

This PR:
* Looked through various type definitions related to interactions with contracts
* Discovered incorrect types where Promises were expected but unwrapped types were defined (i.e Promise<number> vs number)
* This PR fixes these types, all tests pass

Fix incorrect types related to contract calls in types.ts

---

test/utils/rpc.ts

…ests made JSONRPC endpoints
This PR:
* the parity ethereum client rejects http requests that do not include a json content-type https://github.com/paritytech/parity/wiki/FAQ%3A-CLI%2C-Mining%2C-and-Networks#none-of-my-jsonrpc-requests-work-they-all-fail-with-no-output
* other clients may adopt a similar error in the future

Add 'content-type' header with value 'application/json' for http requ… 

---

CHANGELOG.md
src/contract_wrappers/exchange_wrapper.ts
src/types.ts
src/utils/order_validation_utils.ts
test/order_validation_test.ts
test/utils/fill_scenarios.ts

**Problem**: Relayers want a validation method with which to prune their orderbook. During pruning, they do not know who the order's eventual taker is going to be.
This PR:
* Adds a validation method that validates whether an order is fillable, without knowing the eventual taker. It validates that the order has not already been completely filled/cancelled, hasn't expired and that the maker still has a sufficient balance/allowance.
* The caller can optionally pass in a `opts.expectedFillTakerTokenAmount` to the validation. If omitted, the method ensures that the total remaining `takerTokenAmount` is fillable. If supplied, it validates that the order is fillable up to the passed `expectedFillTakerTokenAmount`. If a relayer wants to keep orders on their books that are partially unfillable, …

Add validateOrderFillableOrThrowAsync Method

---

CHANGELOG.md
src/artifacts/EtherToken.json
src/artifacts/Exchange.json
src/artifacts/TokenRegistry.json
test/artifacts_test.ts
test/utils/constants.ts

This PR:
* Adds support for ropsten testnet

Add Ropsten support

---

CHANGELOG.md
package.json
src/0x.ts
src/contract_wrappers/contract_wrapper.ts
src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_wrapper.ts
src/index.ts
src/types.ts
src/utils/abi_decoder.ts
src/web3_wrapper.ts
test/0x.js_test.ts
test/exchange_wrapper_test.ts
test/token_wrapper_test.ts
test/utils/token_utils.ts
yarn.lock

This PR:
* Adds `zeroEx.token.getLogsAsync` to fetch historical token logs without setting up a subscription
* Adds `zeroEx.exchange.getLogsAsync` to fetch historical exchange logs without setting up a subscription
* Adds tests for it
* Adds a new public type: `FilterObject`

Add zeroEx.getLogsAsync

---

src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_wrapper.ts

This PR:
* Adds parameter type assertions for `zeroEx.(exchange|token).getLogsAsync`

Add assertions

---

CHANGELOG.md
src/contract_wrappers/exchange_wrapper.ts
src/types.ts
src/utils/assert.ts
src/utils/exchange_transfer_simulator.ts
src/utils/order_validation_utils.ts
test/exchange_transfer_simulator_test.ts
test/order_validation_test.ts

This PR:
* Emulates the actual transfers on a copy-on-read balance/proxyAllowance store to perform validations for batch operations
* Fixes the ETH address validation
* Stops using public validations functions for internal validations and starts using utils

Fix batch validation

---

CHANGELOG.md
src/web3_wrapper.ts

This PR:
* Fixes a bug when 0x.js sent an RPC request with `fromBlock` and `toBlock` as integers instead of hexes.
* testrpc supports number values, but it's not a part of a standard.
* Fixes #188

Fix a bug in logs fetching

---

CHANGELOG.md
src/utils/order_validation_utils.ts
test/order_validation_test.ts

This PR:
* Fixes the rounding issue when calculating `maker fill amount`
* Correctly validates fees within a partial fill
* Adds regression tests for the bugs above

Fix rounding of maker fill amount and correctly validate partial fees

---

src/contract_wrappers/token_wrapper.ts

On TestRPC, I'm seeing a particular transaction that is taking 47275
gas instead of the predefined 47155. It's not at all obvious to me
why this transaction is taking an extra 120 gas, and I've been unable
to reproduce the issue in the 0x.js test suite, but bumping the gas
allowance has resolved the issue for me.
The transactions in question are trying to set an unlimited proxy
allowance on either the WETH or ZRX tokens in the testrpc snapshot,
but run out of gas.
This PR:
* Raises the ALLOWANCE_TO_ZERO_GAS_AMOUNT based on values I'm seeing with ethereumjs-testrpc@4.1.3

Increase ALLOWANCE_TO_ZERO_GAS_AMOUNT

---

package.json
src/0x.ts
src/bignumber_config.ts
src/contract_wrappers/ether_token_wrapper.ts
src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_wrapper.ts
src/globals.d.ts
src/globalsAugment.d.ts
src/types.ts
src/utils/abi_decoder.ts
src/utils/assert.ts
src/utils/constants.ts
src/utils/exchange_transfer_simulator.ts
src/utils/order_validation_utils.ts
src/utils/utils.ts
src/web3_wrapper.ts
test/0x.js_test.ts
test/ether_token_wrapper_test.ts
test/exchange_transfer_simulator_test.ts
test/exchange_wrapper_test.ts
test/order_validation_test.ts
test/token_wrapper_test.ts
test/utils/fill_scenarios.ts
test/utils/order_factory.ts
yarn.lock

This PR:
* Uses the new version of BigNumber that contains native types
* This allows us to write types as `BigNumber` instead of `BigNumber.BigNumber`
* This forces us to use a hack with chai namespace

Bignumber types

---

src/0x.ts
src/types.ts

This PR:
* Currently awaitTransactionMinedAsync will poll forever
* Allow an optional 'timeoutMs' argument which will reject the promise after n ms

Allow timeout for await transaction mined

---

src/contract_wrappers/contract_wrapper.ts
src/contract_wrappers/exchange_wrapper.ts
src/contract_wrappers/token_wrapper.ts
test/subscription_test.ts

This PR:
Higher level classes which implemented `activeSubscriptions` could result in mismatched state from the base.
In the case of an exception, keep the state correct between contract wrapper, exchange wrapper and token wrapper.

Clean up subscription state.

---

test/order_state_watcher_test.ts
test/utils/blockchain_lifecycle.ts
test/utils/rpc.ts

This PR:
* Adds additional tests for the order watcher. Most notable tests for the `numConfirmations` config and making sure the watcher doesn't emit events when state changes for unwatched orders.

Additional order watcher tests

---

src/types.ts
src/utils/order_state_utils.ts
test/order_state_watcher_test.ts

Calculate the remaining maker token amount that is fillable.
```
remainingTaker = totalTakerAmount - unavailableTakerAmount
remainingProportion = remainingTaker / totalTakerAmount
makerFillable = min(allowance, balance)
makerOrderRemaining = totalMakerAmount * remainingProportion
orderMakerFillable = min(makerFillable, makerOrderRemaining)
```
TODO

Calculate the remaining order amount in maker units

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/web3_wrapper.ts
packages/0x.js/test/token_wrapper_test.ts

This PR:
* Adds post formatter for logs that convert hexes to numbers (logIndex, txIndex, blockNumber)

Add postFormatter for logs

---

packages/0x.js/src/order_watcher/remaining_fillable_calculator.ts
packages/0x.js/src/utils/order_state_utils.ts
packages/0x.js/test/order_state_watcher_test.ts
packages/0x.js/test/remaining_fillable_calculator_test.ts
packages/0x.js/test/utils/constants.ts

This PR:
* Handles the case when `feeToken` is transferred but the `makerToken` balance is satisfactory.
* Handle the case when MakerToken and FeeToken both are ZRX (pooled).
* Handle the case when Maker Token and FeeToken are different (non-pooled).
* Calculate the maximum partially fillable amount
* handle the case where Order to Fee Ratio is < 1

Calculate remaining proportions from fee to ratio proportions

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/contract_wrappers/contract_wrapper.ts
packages/0x.js/src/types.ts
packages/0x.js/test/exchange_wrapper_test.ts
packages/0x.js/test/token_wrapper_test.ts

This PR:
* Separates logs from log events
* Now log events contain log as a subkey which will simplify consumption of this type (inspired by OTC)

Make DecodedLogEvent contain web3 log under a log subkey

---

packages/connect/CHANGELOG.md
packages/connect/src/index.ts
packages/connect/src/types.ts
packages/connect/src/utils/orderbook_channel_message_parsers.ts
packages/connect/src/ws_orderbook_channel.ts
packages/connect/test/fixtures/standard_relayer_api/snapshot_orderbook_channel_message.ts
packages/connect/test/fixtures/standard_relayer_api/unknown_orderbook_channel_message.ts
packages/connect/test/fixtures/standard_relayer_api/update_orderbook_channel_message.ts
packages/connect/test/orderbook_channel_message_parsers_test.ts
packages/json-schemas/schemas/relayer_api_orberbook_channel_subscribe_schema.ts
packages/json-schemas/schemas/relayer_api_orderbook_channel_snapshot_schema.ts
packages/json-schemas/schemas/relayer_api_orderbook_channel_update_response_schema.ts
packages/json-schemas/test/schema_test.ts

This PR:
* Expose WebSocketOrderbookChannel
* Add subscriptionOpts to channel handler callback
* Add requestId to websocket messages
* Update associated json-schemas and tests

Add requestId to subscription messages and update json-schemas

---

packages/connect/CHANGELOG.md
packages/connect/src/types.ts
packages/connect/src/ws_orderbook_channel.ts
packages/connect/test/http_client_test.ts

This PR:
* Add OrderbookChannelSubscriptionOpts to `onClose()` function in `OrderbookChannelHandler`
* Remove tokenA and tokenB fields from OrdersRequest
* These params were a bit confusing and the functionality is actually already possible via the tokenAddress param and the /orderbook endpoint

Update connect types in preperation for publishing

---

packages/website/ts/containers/connect_documentation.tsx

This PR:
* Add WebSocketOrderbookChannel to connect docs
* there is an issue where the docs use zeroEx as the instance name in the call path, will follow up with a fix for that

Add WebSocketOrderbookChannel to connect docs

---

packages/dev-utils/src/blockchain_lifecycle.ts
packages/subproviders/src/globals.d.ts
packages/subproviders/src/subproviders/redundant_rpc.ts
packages/tslint-config/package.json
packages/tslint-config/rules/asyncSuffixRule.ts
packages/tslint-config/rules/walkers/async_suffix.ts
packages/tslint-config/tsconfig.json
packages/tslint-config/tslint.json

This PR:
* Implements first custom linter rule that checks that every function returning a promise has an `Async` suffix

Implement first custom linter rule async-suffix

---

packages/0x.js/test/0x.js_test.ts
packages/0x.js/test/utils/web3_factory.ts
packages/kovan-faucets/src/ts/handler.ts
packages/kovan-faucets/src/ts/request_queue.ts
packages/kovan-faucets/src/ts/zrx_request_queue.ts

This PR:
* Move web3 import after subprovider imports in order to fix hanging RPC requests
* Update a couple comments to reference the web3 issue
* Update a `isValidSignature` test in the 0x.js tests to be more consistent with the others

Move web3 import after subprovider imports in test web3_factory

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/src/contract_wrappers/contract_wrapper.ts
packages/0x.js/src/contract_wrappers/ether_token_wrapper.ts
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/src/contract_wrappers/token_wrapper.ts
packages/0x.js/src/schemas/zero_ex_config_schema.ts
packages/0x.js/src/types.ts
packages/0x.js/test/0x.js_test.ts
packages/0x.js/test/ether_token_wrapper_test.ts
packages/contracts/test/ts/ether_token.ts
packages/contracts/test/ts/ether_token_v2.ts
packages/website/ts/blockchain.ts
packages/website/ts/components/eth_weth_conversion_button.tsx

This PR:
- Modifies the `etherTokenWrapper` methods to accept an `etherTokenAddress` as the first arg. Since it is becoming apparent we will be updating the canonical WETH contract, we want users of 0x.js to be able to interact with n number of etherToken contracts without re-instantiating the library for each one. Because of this, we modify the interface for `etherTokenWrapper` methods to be similar to `tokenWrapper` methods.
- Unrelated: I also fixed an issue with 0x.js docs where `unsubscribeAll` was showing up as a method in each contractWrapper instance since it was declared in the base class. Since it is only used by `exchangeWrapper` and `tokenWrapper`, I made it `protected` and re-declared it in those two.

Refactor EtherToken wrapper to accept address in method args

---

package.json
packages/website/ts/pages/shared/markdown_code_block.tsx

This PR:
* Fixes https://github.com/0xProject/wiki/issues/19
* Disables re-rendering markdownCodeBlock renderer if props haven't changed. Re-rendering this component causes a user's selection to become de-selected. This is annoying while trying to copy-paste code examples from wiki, 0x.js docs, etc...
* Adds a convenience `yarn lerna:rebuild` command that first calls `clean` followed by `build`.

Fix code selection bug in docs

---

packages/contracts/test/ts/zrx_token.ts
yarn.lock

This PR:
* Deploys a new `ZRXToken` before each test, rather than pulling the address from the 0x.js artifacts (this would be fine if contracts shared artifacts with 0x.js). None of the other contract tests rely on the snapshot, so this should be no different.

Remove reliance on testrpc snapshot in ZRX tests

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/src/types.ts
packages/0x.js/src/utils/constants.ts
packages/0x.js/src/utils/decorators.ts
packages/0x.js/test/0x.js_test.ts

This PR:
*  Improves an error message when taker is anything except string.
* Refactors our decorators module so that we can more easily improve other error messages and make the handlers composable.
* Adds a test for a new behaviour
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/recJWzqENfEUCbA0D

Throw a better error message when taker is null|undefined or anything but not a string

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/test/0x.js_test.ts

This PR:
* Throw if amount with too many decimal places is passed into `toBaseUnitAmount`
* Assert that valid baseUnit amount is passed into `toUnitAmount`
* Add tests for both of the above edge cases

Fix toBaseUnitAmount Issue

---

packages/website/ts/containers/connect_documentation.tsx
packages/website/ts/containers/zero_ex_js_documentation.tsx
packages/website/ts/pages/documentation/documentation.tsx
packages/website/ts/pages/documentation/event_definition.tsx
packages/website/ts/pages/documentation/interface.tsx
packages/website/ts/pages/documentation/method_block.tsx
packages/website/ts/pages/documentation/method_signature.tsx
packages/website/ts/pages/documentation/type.tsx
packages/website/ts/pages/documentation/type_definition.tsx
packages/website/ts/pages/shared/nested_sidebar_menu.tsx
packages/website/ts/utils/constants.ts

This PR:
* Fixes a bug where if two sections contain methods with the same name, the anchor link would always navigate to the first method. By namespacing the anchors below sectionNames, we alleviate this issue.

Fix doc anchor link collisions

---

packages/subproviders/src/subproviders/ledger.ts

This PR includes the following changes:
* Changed `personal_sign` to `eth_sign`. ZeroEx uses `web3.eth.sign`, rather than `web3.eth.personal.sign`, so the Ledger subprovider should be looking for `eth_sign`.
* Get the data to sign from the second parameter, rather than the first. The first parameter is the address.

Update subprovider to catch correct RPC method

---

packages/subproviders/src/subproviders/ledger.ts

This PR:
* Web3/0x machinery expects sendTransactionAsync to return a string. For ledger devices, the resulting payload is getting passed instead of the string representing txHash, which results in a broken 0x client

_sendTransactionAsync should return txHash string

---

packages/abi-gen/src/utils.ts

Incorrect typings were being generated when an array type consisted of elements separated by an | operator.  For instance, if the constituent element of the array was a `number|BigNumber`, the generated array type would be `number|BigNumber[]`.
Fixed by grouping all constituent elements in a type array with parentheses.

Fix array typing generation when permitting multiple types

---

packages/web3-typescript-typings/CHANGELOG.md
packages/web3-typescript-typings/index.d.ts

The default value for the defaultAccount property is undefined,
this happens in real-life scenarios, and so the type should
explicitly warn users about it

Fix web3 typing defaultAccount not allowing `undefined`

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/test/exchange_wrapper_test.ts

This PR:
* Fixes the validation issue in a situation when a user does a market order fill and doesn't have enough balance to fill all orders, but still has enough balance to satisfy his/her market order (`fillOrdersUpTo`)
* Adds tests for that use-case

Fix fillOrdersUpTo validation

---

packages/website/ts/components/generate_order/new_token_form.tsx

Allows alphanumeric characters in token symbols to be added to the portal. Previously a validation was failing preventing the token from being added to the Portal.
We already allow Alphanumeric when hardcoded in the config, i.e First Blood 1ST

Allow Token symbols to be alphanumeric

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/src/types.ts

This PR:
* Fixes a bug that made it impossible to use ZRX on custom chains, because we were not passing down the zrx address and it was impossible to onfigure it

Fix the bug making it impossible to specify the custom ZRX address

---

packages/web3-typescript-typings/CHANGELOG.md
packages/web3-typescript-typings/index.d.ts

If the transaction is not yet put into blockchain, using `getTransactionReceipt` will return null.

Fix getTransactionReceipt not returning null

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Updated the default Issue/Pull Request templates.
Provides a templated guide for outside commiters to follow a particular format. Mostly hijacked from Lerna.

Issue/Pull Request Template

---

packages/0x.js/src/order_watcher/order_state_watcher.ts

When removing an order from the watcher cache, we call _removeFromDependentOrderHashes for both the makerTokenAddress and the ZRX token address for fees. The problem is when the makerTokenAddress is the ZRX token address and you call this line:
```
this._dependentOrderHashes[makerAddress][tokenAddress].delete(orderHash);
```
This fails and results in the rest of the script terminating.

BUGFIX: don't remove maker/zrx order from cache twice

---

lerna.json

This PR aggs lerna ignore config to ignore non-source changes when publishing new versions.
This removes some redundant publishes.
`lerna updated`

Ignore test files and markdown files changes on publish

---

packages/0x.js/CHANGELOG.md
packages/utils/CHANGELOG.md
packages/utils/src/abi_decoder.ts

Fixes an exception in an order watcher when we have an event with the same signature as one of the known events, but it has different indexed fields and therefore fails to decode.
`Deposit(address a, uint b);`
and
`Deposit(address indexed a, uint b);`
have the same signature, but are encoded differently.
Manual tests
Closes #365

Fix an exception when a signature collision happens

---

packages/subproviders/CHANGELOG.md
packages/subproviders/README.md
packages/subproviders/src/subproviders/injected_web3.ts
packages/website/ts/blockchain.ts

Remove the requirement to pass in a Web3 object to InjectedWeb3Subprovider and accept a Web3 Provider.
Allows us to use a controlled version of Web3.
Manually tested in Website which uses InjectedWeb3 provider.

Change the InjectedWeb3Subprovider to accept Web3.Provider

---

packages/testnet-faucets/src/ts/handler.ts

When using the order from the testnet in 0x.js it fails schema validation. It requires the signature attribute to be named `ecSignature` not `signature`.
Seemless experience

Testnet Faucet Order conforming to JSON Schema

---

packages/web3-typescript-typings/index.d.ts

Fixes return type of NetApi.peerCount from `boolean` to `number` in package `web3-typescript-typings`

web3-typescript-typings fix - web3.net.peerCount returns number

---

packages/0x.js/scripts/stagedocs.js
packages/connect/scripts/stagedocs.js
packages/website/ts/containers/connect_documentation.tsx
packages/website/ts/containers/zero_ex_js_documentation.tsx
packages/website/ts/pages/documentation/type.tsx
packages/website/ts/types.ts

Added a script `stagedocs.js` to the `scripts` directory in the connect package. This script will generate and upload docs to the `staging-connect-docs-jsons` s3 bucket. Usage is as follows:
```bash
DOCS_VERSIONS=0.0.2 node scripts/stagedocs.js
```
Specify `DOCS_VERSIONS` to choose the name of the file being written to s3. In the command above, a file named `v0.0.2.json` will be uploaded to the `staging-connect-docs-jsons` bucket.
During development, the website will retreive documentation uploaded to the `staging-connect-docs-jsons` bucket.
Right now it is impossible to test out documentation w/o uploading it to the production bucket first
Manually

Add support for intersection types and staged connect documentation

---

packages/connect/CHANGELOG.md
packages/connect/src/index.ts
packages/connect/src/schemas/schemas.ts
packages/connect/src/schemas/websocket_orderbook_channel_config_schema.ts
packages/connect/src/types.ts
packages/connect/src/ws_orderbook_channel.ts
packages/website/ts/containers/connect_documentation.tsx

Add a configurable heartbeat interval to the websocket channel that keeps the socket alive. Different websocket apis may need more or less frequent heartbeats.
Radar recommends its websocket be kept alive with a ping request about every 15s.
`wss://api.kovan.radarrelay.com/0x/v0/ws`

Add configurable heartbeat to WebSocketOrderbookChannel

---

packages/contracts/package.json
packages/dev-utils/package.json
packages/subproviders/package.json
packages/utils/package.json
packages/web3-wrapper/package.json

Move all instances of `@0xproject/types` that appear in `devDependencies` to `dependencies` instead.
Our `@0xproject/types` package includes compiled JavaScript in addition to types so we must include it in the `dependencies` field in the dependent `package.json` files.

Move all dependencies on @0xproject/types out of devDependencies

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/contract_wrappers/ether_token_wrapper.ts
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/src/contract_wrappers/token_wrapper.ts
packages/0x.js/test/ether_token_wrapper_test.ts
packages/0x.js/test/exchange_wrapper_test.ts
packages/0x.js/test/subscription_test.ts
packages/0x.js/test/token_wrapper_test.ts
packages/website/ts/blockchain.ts

We accidentally named some public methods `_unsubscribeAll` instead of `unsubscribeAll`.
This fixes that.
It builds and passes tests

Rename _unsubscribeAll to unsubscribeAll

---

packages/testnet-faucets/src/ts/dispense_asset_tasks.ts

It's possible for someone to drain thousands of our Tokens from the faucet if they are persistent enough.
Someone needlessly recently drained over 3000 ZRX, forcing a bad experience for other users.
Manually tested against low and high balanced accounts (both ZRX and ETH)

Prevent a single account from draining the faucet

---

packages/subproviders/CHANGELOG.md
packages/subproviders/src/subproviders/ledger.ts
packages/subproviders/test/integration/ledger_subprovider_test.ts
packages/subproviders/test/unit/ledger_subprovider_test.ts

Previously `getAccountsAsync` always returned 10 accounts. Now the caller can specify any number of accounts to fetch. Either way, only a single request is sent to the Ledger device, fetching the public key and chainCode. We then use the key path derivation scheme to generate the requested account addresses locally.
People use more then the first 10 accounts on their Ledger (or they should!), so why not allow developers to fetch them as well.
Added unit and integration tests
*   [x] Added tests to cover my changes.
* …

Allow LedgerSubprovider to return any number of accounts

---

packages/0x.js/CHANGELOG.md
packages/0x.js/README.md
packages/0x.js/package.json
packages/assert/README.md
packages/base-contract/README.md
packages/connect/README.md
packages/dev-utils/README.md
packages/subproviders/README.md
packages/types/README.md
packages/utils/README.md
packages/web3-wrapper/README.md

Currently, many of our libraries require users to include external typings by specifying them in the `tsconfig.json` `include` section. This PR adds this instruction to all the relevant projects, to help get user's up and running.
Open question: Is there a way to eliminate the need for users to perform this step? It's quite cumbersome and error prone.
Tried using each library in stand-alone project and ran into this issue.
N/A
* …

Add Missing README Instructions

---

packages/website/ts/components/ui/etherscan_icon.tsx

EtherscanLink always used address no matter what was passed in as a required property.
This would fail if you wanted to view the tx of the trade in the Trade History, linking you to a "address".
Manually in portal
*   [ ] Labeled this PR with the labels corresponding to …

Fix the Portal Etherscan Link always overriding to address

---

packages/contract_templates/partials/tx.handlebars

`callAsync` and `getABIEncodedTransactionData` were not transforming input values before encoding, causing anything containing BigNumber values to fail.

Transform input data before encoding

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/src/contract_wrappers/exchange_wrapper.ts
packages/0x.js/src/index.ts
packages/0x.js/src/order_watcher/order_state_watcher.ts
packages/0x.js/src/order_watcher/remaining_fillable_calculator.ts
packages/0x.js/src/types.ts
packages/0x.js/src/utils/assert.ts
packages/0x.js/src/utils/order_state_utils.ts
packages/0x.js/src/utils/order_validation_utils.ts
packages/0x.js/src/utils/signature_utils.ts
packages/0x.js/src/utils/utils.ts
packages/0x.js/test/remaining_fillable_calculator_test.ts
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/http_client.ts
packages/connect/src/index.ts
packages/connect/src/types.ts
packages/connect/src/utils/relayer_response_json_parsers.ts
packages/types/CHANGELOG.md
packages/types/src/index.ts

Add SignedOrder, Order, and ECSignature types to the types package, remove the duplicated definitions from `types.ts` in 0x.js and connect.
There are duplicated definitions for SignedOrder, Order, and ECSignature
N/A
*   [] Added tests to cover my changes.
*   [x] Updated the new versions of the changed packages in the relevant CHANGELOGs.
*   [x] Labeled this PR with the labels corresponding to …

Add SignedOrder, Order, and ECSignature types to the types package

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/artifacts/TokenRegistry.json

Update Kovan Ethertoken Address
Kovan EtherToken artifact address was old and did not match the TokenRegistry
Thanks to mandy in our RocketChat for making us aware of this.

Update Kovan Ethertoken Address

---

packages/contracts/src/contracts/current/protocol/Exchange/Exchange.sol
packages/contracts/src/contracts/current/protocol/Exchange/IExchange.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinExchangeCore.sol
packages/contracts/src/contracts/current/protocol/Exchange/mixins/MExchangeCore.sol
packages/contracts/src/utils/exchange_wrapper.ts
packages/contracts/src/utils/types.ts
packages/contracts/test/exchange/core.ts

Implementation and tests in the protocol for cancelling all of a maker's orders before a certain time.
A change to the protocol which allows makers to cancel all of their orders up to a specific time.
ZEIP: https://github.com/0xProject/ZEIPs/issues/20
The existing batchCancelOrders is granular but expensive. This change introduces a very inexpensive strategy for cancelling all orders that were created before a specific time. Makers are able to timestamp their orders by overloading the salt value. Timestamps follow minimal specs; for example, a specific unit of time is not enforced.
We detect the salt value has been overloaded as a timestamp when the "cancelOrdersBefore" is called. Since timestamps and salts serve similar purposes, only one should be necessary. There is probably a better / …

Cancel maker's orders before a certain time (Revised)

---

packages/0x.js/CHANGELOG.md
packages/0x.js/src/0x.ts
packages/0x.js/src/order_watcher/event_watcher.ts
packages/0x.js/src/order_watcher/order_state_watcher.ts
packages/0x.js/src/types.ts
packages/0x.js/test/order_state_watcher_test.ts

Allow instantiation of stand-alone OrderWatchers that can monitor different blockchain state layers (e.g. pending or latest)
Modified `OrderStateWatcherConfig` to support a `stateLayer` (BlockParamLiteral) setting so that OrderStateWatcher instances can monitor different blockchain state layers.
Also modified ZeroEx class so that it does not instantiate a default `orderStateWatcher`, instead, users can now create as many stand-alone watchers as they need by using the new `ZeroEx.createOrderStateWatcher(OrderStateWatcherConfig)` method.
In the future this will allow to create watchers that go beyond simply `pending` and `latest` state layers, to arbitrary confirmation depths.
OrderStateWatcher subscriptions for mined blocks (rather than simply mempool transactions) can provide reliable …

Monitor different state layers with OrderWatcher

---

packages/website/ts/components/wallet/wallet.tsx
packages/website/ts/components/wallet/wrap_ether_item.tsx

Rendering components in an iterator requires a key to be assigned for each component rendered
N/A
`cd packages/website`
`yarn run dev`
navigate to `https://localhost:3572/portal/wallet`
verify no warnings show up in the browser console
*   [ ] Labeled this PR with the …

Fix missing key warnings in wallet component

---

packages/0x.js/README.md
packages/abi-gen/README.md
packages/assert/README.md
packages/connect/README.md
packages/contracts/README.md
packages/deployer/README.md
packages/dev-utils/README.md
packages/json-schemas/README.md
packages/monorepo-scripts/README.md
packages/monorepo-scripts/src/find_unused_dependencies.ts
packages/react-docs-example/README.md
packages/react-docs/README.md
packages/react-shared/README.md
packages/sol-cov/README.md
packages/sra-report/README.md
packages/subproviders/README.md
packages/testnet-faucets/README.md
packages/tslint-config/README.md
packages/types/README.md
packages/typescript-typings/README.md
packages/utils/README.md
packages/web3-wrapper/README.md
packages/website/README.md

- The first time a user builds a package, they must build all monorepo packages. This was missing from the package README instructions so I added it. (See issue: https://github.com/0xProject/0x-monorepo/issues/481)
- Added missing `clean` instruction.
- Standardized inclusion of `yarn build:watch` in all package README's.
- Add short description to 0x.js readme.
*   [ ] Updated the new versions of the changed packages in the …

Improve README contributing sections in all packages

---

packages/contracts/src/contracts/current/protocol/Exchange/ISigner.sol
packages/contracts/src/contracts/current/protocol/Exchange/LibErrors.sol
packages/contracts/src/contracts/current/protocol/Exchange/LibOrder.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinExchangeCore.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinSettlementProxy.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinWrapperFunctions.sol
packages/contracts/src/contracts/current/protocol/Exchange/mixins/MExchangeCore.sol
packages/contracts/src/contracts/current/protocol/Exchange/mixins/MSettlement.sol
packages/contracts/src/contracts/current/protocol/Exchange/mixins/MSignatureValidator.sol
packages/contracts/src/utils/exchange_wrapper.ts
packages/contracts/src/utils/formatters.ts
packages/contracts/src/utils/order_utils.ts
packages/contracts/src/utils/types.ts
packages/contracts/test/exchange/core.ts
packages/contracts/test/exchange/helpers.ts
packages/contracts/test/exchange/wrapper.ts

- Adds a version of `marketFillOrders` where the taker can specify the amount of `makerTokens` to buy, rather than the amount of `takerTokens` to sell
- Renames a handful of order properties, function args, and return values for clarity
TODO:
- Does `makerFeePaid` need to be in the `FillResults` struct? I can't really think of a good use case for it
*   [ ] Updated the new versions of the changed packages in the relevant …

Add marketBuyOrders

---

packages/0x.js/CHANGELOG.json
packages/0x.js/src/order_watcher/expiration_watcher.ts
packages/0x.js/src/order_watcher/order_state_watcher.ts

There appears to be a bug related to recursive attempts to remove orders from expiration_watcher.
What happens is that `_pruneExpiredOrders` removes the order from both the RBtree and the expiration stack, but when the `_onOrderExpired` callback executes at the end, it invokes `expiration_watcher.removeOrder()`, but since the order was already removed, it blows up in the scoreFunction (see this [screenshot](https://i.imgur.com/t3ltrpp.png) from my debugger).
This is a fix to ensure that the `_onOrderExpired` skips `expiration_watcher.removeOrder()` when `expiration_watcher` has already handled the order removal.
When testing OrderStateWatcher for expired orders I identified an issue where when I had multiple orders in the stack, the first expiration would fail to execute the …

Fix redundant expired order removal bug

---

packages/0x.js/CHANGELOG.json
packages/0x.js/package.json
packages/0x.js/src/order_watcher/expiration_watcher.ts
packages/0x.js/test/0x.js_test.ts
packages/0x.js/test/expiration_watcher_test.ts
packages/0x.js/test/global_hooks.ts
packages/migrations/src/migration.ts

RB tree is unable to store values with the same key. Before - we user expiraration time as a key.
This PR changes that and adds order hash as a secondary key
Added a regression test

Fix expiration watcher comparator

---

packages/website/ts/components/relayer_index/relayer_grid_tile.tsx
packages/website/ts/components/relayer_index/relayer_index.tsx
packages/website/ts/types.ts
packages/website/ts/utils/backend_client.ts

Modifies the relayer_index component to consume relayer information from the `/relayers` endpoint.
N/A
in the `website` package, modify `BACKEND_BASE_URL` in `configs.ts` to `http://localhost:3000`
then build and run the website:
```bash
cd packages/website
yarn dev
```
in a separate terminal, build and run `website-backend`
*   [ ] Labeled this …

Integrate relayer index with website backend

---

packages/website/ts/components/legacy_portal/legacy_portal.tsx
packages/website/ts/components/legacy_portal/legacy_portal_menu.tsx
packages/website/ts/components/top_bar/top_bar.tsx
packages/website/ts/containers/legacy_portal.ts
packages/website/ts/index.tsx

In preparation for moving to a new main portal component and container, this refactor simply renames the existing `Portal` and `PortalMenu` components to `LegacyPortal` and `LegacyPortalMenu` respectively. Doing this will allow us to merge code for a new `Portal` component into the `development` and `master` branches while retaining the ability to fix bugs in the old portal implementation.
See above.
Manually.
*   [ ] …

Rename Portal component to LegacyPortal

---

packages/0x.js/CHANGELOG.json
packages/0x.js/package.json
packages/dev-utils/CHANGELOG.json
packages/dev-utils/package.json
packages/metacoin/package.json
packages/subproviders/CHANGELOG.json
packages/subproviders/package.json
packages/subproviders/src/subproviders/base_wallet_subprovider.ts
packages/testnet-faucets/package.json
packages/website/package.json
yarn.lock

Update Web3 Provider engine to 14.0.04
Relax Base Wallet validation to allow contract deployment (no `to` parameter)
Updates Web3 Provider Engine to 14.0.4.
Fixes a [bug in RPC subprovider](https://github.com/MetaMask/provider-engine/commit/ea21424347d195135e5cdc9cea2ebc52ac45116a) which caused it to hang when executing in non pollyfilled/browser environments where `xhr` didn't exist.
Some members in the community had requested 14.0.x upgrade for websocket support.
*   [ ] Added …

Update Web3 Provider Engine to 14.0.4

---

packages/contracts/src/contracts/current/protocol/AssetProxy/IAssetProxy.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/proxies/ERC20Proxy.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/proxies/ERC721Proxy.sol
packages/contracts/src/contracts/current/protocol/Exchange/MixinAssetProxyDispatcher.sol
packages/contracts/src/contracts/current/protocol/Exchange/mixins/MAssetProxyDispatcher.sol
packages/contracts/test/asset_proxy/proxies.ts
packages/contracts/test/exchange/dispatcher.ts

- Hard codes a proxyId into each AssetProxy
- Check that the metadata being passed in is intended for the receiving proxy
- Check the that ids match when registering a new proxy, unless the proxy is being removed

Add hard coded proxyId into each AssetProxy

---

packages/0x.js/src/utils/exchange_transfer_simulator.ts
packages/0x.js/src/utils/order_validation_utils.ts
packages/0x.js/test/order_validation_test.ts

#567
Simulate both sides of the trade in the exchange simulator
It's possible to just in time fill for fees when buying ZRX. Exchange simulator was only trading the maker side to the taker, as such it would fail the fee simulation as the maker did not receive any ZRX.
The current order state validation code looks intentional to not execute the Taker side (as its likely the order is open to any taker). The exchange simulator now allows for open orders to be simulated. It is assumed there will be further verification with a real taker using `validateFillOrderBalancesAllowancesThrowIfInvalidAsync` or that the taker will have sufficient balance and allowance.
*   [ ] …

Execute Taker side in trade simulation

---

packages/monorepo-scripts/src/postpublish_utils.ts
packages/monorepo-scripts/src/utils.ts

This PR applies prettier to the following files:
- __packages/monorepo-scripts/src/utils.ts__
- __packages/monorepo-scripts/src/postpublish_utils.ts__
Prior to this change, CI was failing at the `yarn prettier:ci` step.
(Pretty self-explanatory).
I ran `yarn prettier:ci` locally and verified it did not spit out an error. We can also observe the output of CI on this PR.
*   [ ] Labeled this PR with the 'WIP' label if it is a …

Apply prettier to some files which were not formatted correctly

---

packages/website/ts/components/legacy_portal/legacy_portal.tsx
packages/website/ts/components/portal/back_button.tsx
packages/website/ts/components/portal/loading.tsx
packages/website/ts/components/portal/menu.tsx
packages/website/ts/components/portal/portal.tsx
packages/website/ts/components/portal/portal_menu.tsx
packages/website/ts/components/portal/section.tsx
packages/website/ts/components/portal/text_header.tsx
packages/website/ts/components/relayer_index/relayer_index.tsx
packages/website/ts/components/wallet/wallet.tsx
packages/website/ts/pages/fullscreen_message.tsx
packages/website/ts/pages/not_found.tsx

Provide the functionality from the old portal in a "manage your wallet" section. This includes viewing account balances, trade history, dedicated wrap / unwrap ETH section, and trading direct
N/A
Manually.

Manage your wallet section of portal

---

packages/contracts/src/utils/asset_proxy_utils.ts

Pad to the full 32 bytes for ERC721 encoding
Some ERC721 token ids are incremental ID's and start small. The ERC721 proxy expects a full 32 byte token id, and our current encoding doesn't pad to 32 bytes. This results in a failure to decode in the erc721 proxy.

ERC721Proxy Pad to 32 if asset ids are small

---

packages/contract-wrappers/test/ether_token_wrapper_test.ts
packages/contract-wrappers/test/exchange_transfer_simulator_test.ts
packages/contract-wrappers/test/exchange_wrapper_test.ts
packages/contract-wrappers/test/token_wrapper_test.ts
packages/contract_templates/contract.handlebars
packages/contracts/src/utils/exchange_wrapper.ts
packages/contracts/test/asset_proxy/authorizable.ts
packages/contracts/test/asset_proxy/proxies.ts
packages/contracts/test/ether_token.ts
packages/contracts/test/exchange/core.ts
packages/contracts/test/exchange/dispatcher.ts
packages/contracts/test/exchange/match_orders.ts
packages/contracts/test/exchange/transactions.ts
packages/contracts/test/exchange/wrapper.ts
packages/contracts/test/multi_sig_with_time_lock.ts
packages/contracts/test/token_registry.ts
packages/contracts/test/unlimited_allowance_token.ts
packages/fill-scenarios/src/index.ts
packages/metacoin/test/metacoin_test.ts
packages/web3-wrapper/src/web3_wrapper.ts
packages/website/ts/blockchain.ts

This PR introduces an `awaitTransactionSuccessAsync` method in `Web3Wrapper`. It works similarly to `awaitTransactionMinedAsync` but checks the transaction receipt and throws if it has a status not equal to 1.
In lots of different places in our tests, we call `awaitTransactionMinedAsync` to wait for a transaction to be added to the blockchain. However, in Ethereum, just because a transaction was mined doesn't mean it was successful. Failed transactions are still mined (though don't affect any state in the blockchain).
To check if a transaction was successful, you need to check the `status` field of the [transaction receipt](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt). The `awaitTransactionSuccessAsync` method does this and throws if it is not 1. …

Check transaction receipt status

---

packages/website/ts/components/relayer_index/relayer_grid_tile.tsx
packages/website/ts/components/relayer_index/relayer_top_tokens.tsx
packages/website/ts/types.ts

Refactored the `RelayerGridTile` internals to better support more general sections with conditional display of children

Implement design for relayers with no volume or tokens

---

packages/contracts/src/utils/token_registry_wrapper.ts
packages/contracts/test/asset_proxy_owner.ts
packages/contracts/test/ether_token.ts
packages/contracts/test/token_registry.ts
packages/contracts/test/unlimited_allowance_token.ts

See #601 and #613 for some background. We had some code pushed in the last few days that didn't follow the practice of calling `awaitTransactionSuccess` when needed.

Add awaitTransactionSuccess where needed

---

package.json
yarn.lock

This PR overrides the ethereumjs-tx version in order to use our fix at https://github.com/ethereumjs/ethereumjs-tx/pull/97. When that PR is merged, we can undo this override.
Ganache sometimes returns the same transaction hash for two different transactions. This was causing race conditions because of the way we use the transaction hash to wait for a transaction to be successfully mined. This bug is fixed by updating ethereumjs-tx, which is a dependency of Ganache.
*   [ ] Added …

Override ethereumjs-tx version

---

packages/contracts/src/utils/erc20_wrapper.ts
packages/contracts/src/utils/erc721_wrapper.ts
packages/contracts/src/utils/order_factory.ts

This PR changes some functions in __erc20_wrapper.ts__ and __erc721_wrapper.ts__ in the contracts package to run serially instead of concurrently. That means we're sending out each transaction one at a time and waiting for it to be successfully mined before continuing.
We also noticed contracts were expiring in CI because the tests sometimes take too long. It's a separate issue, but we wanted to see if we could get the tests to pass in CI for this PR so we also addressed that.
This is an attempt to solve the race condition(s) that have been disrupting our tests. We're not entirely sure if it solves the issue, but we believe at this time it is good to rule out the concurrent portions of these contract wrappers.
This change does make our tests slower, so if it turns out not to be necessary …

Make erc20_wrapper and erc721_wrapper serial and increase contract expiration time

---

packages/website/ts/blockchain.ts
packages/website/ts/components/onboarding/portal_onboarding_flow.tsx
packages/website/ts/components/portal/portal.tsx
packages/website/ts/components/wallet/wallet.tsx
packages/website/ts/containers/portal_onboarding_flow.ts

I noticed that there is similar "TokenState" (balance and allowances for tokens) fetching logic in wallet.tsx, token_balances.tsx and that I would need the same information in portal_onboarding_flow.tsx.
I initially thought about doing a major refactor (https://app.asana.com/0/628666249318202/692511197180876) but decided that this was out of scope for now so just moved the logic into portal.tsx which has all 3 of the components mentioned above. I moved the same logic out of wallet.tsx but kept it in token_balances.tsx since that is used in legacy portal and won't be around for long.
I also went ahead and implemented what is required for the WETH onboarding step, which was easy once I had access to the users WETH balance.
😁
*   [x] …

Move TokenState fetching logic up into Portal.tsx so it can be used by Wallet and PortalOnboardingFlow

---

packages/abi-gen/README.md

Note there is still a broken link here, a previously existing one which I would have fixed but for which I couldn't find the appropriate link.  It's the "wrapper files" one in the second paragraph.

Fix broken link to `contract_templates`

---

packages/website/ts/components/portal/portal.tsx

The first time you use portal, the onboarding flow clashes with the portal disclaimer. Move the disclaimer to the account management section
- Build branch
- Open localhost:3572/portal in chrome incognito
- Observe onboarding but no disclaimer
- Open localhost:3572/portal/account
- Observe disclaimer
*   [ ] Labeled this PR with the labels …

Move portal disclaimer to the account management section

---

packages/ethereum-types/package.json
packages/ethereum-types/src/monorepo_scripts/stage_docs.ts
packages/website/md/docs/ethereum_types/installation.md
packages/website/md/docs/ethereum_types/introduction.md
packages/website/translations/chinese.json
packages/website/translations/english.json
packages/website/translations/korean.json
packages/website/translations/russian.json
packages/website/translations/spanish.json
packages/website/ts/components/top_bar/top_bar.tsx
packages/website/ts/containers/ethereum_types_documentation.ts
packages/website/ts/index.tsx
packages/website/ts/pages/documentation/doc_page.tsx
packages/website/ts/types.ts
packages/website/ts/utils/doc_utils.ts

Adds a docs page for ethereum-types package
Other people that will build ethereum-related type definitions are gonna use those and they'd better be documented.
Manually

Add a documentation page for ethereum-types package

---

packages/website/ts/components/wallet/wallet.tsx

Fixes an issue for balances on the order of thousands being rendered with scientific location. Now displays decimals up to a fixed precision of 5, but does not pad 0's if there are less than 5.

Update balance amount rendering logic

---

packages/devnet/run.sh

Our contracts tests fail on Geth if there are < 3 blocks in the chain. To work around this, we added some code in __run.sh__ in the devnet to send 3 transactions during initialization. However the delay we included was not long enough and sometimes at least two of the transactions were mined into the same block (yielding < 3 blocks total).
This PR simply increases the delay to work around the issue.
*   [ ] Labeled this PR …

Increase delay when sending transactions during devnet startup

---

packages/contracts/package.json
packages/contracts/src/utils/revert_trace.ts
packages/contracts/src/utils/web3_wrapper.ts
packages/dev-utils/src/env.ts
packages/sol-cov/src/coverage_subprovider.ts
packages/sol-cov/src/index.ts
packages/sol-cov/src/profiler_subprovider.ts
packages/sol-cov/src/revert_trace.ts
packages/sol-cov/src/revert_trace_subprovider.ts
packages/sol-cov/src/trace.ts
packages/sol-cov/src/trace_collection_subprovider.ts
packages/sol-cov/src/trace_info_subprovider.ts
packages/sol-cov/src/types.ts
packages/sol-cov/src/utils.ts

This PR introduces a new subprovider, `RevertTraceSubprovider`, which can be enabled in the contracts tests by setting `SOLIDITY_REVERT_TRACE=true` (or running  `yarn wsrun test:trace contracts`).
Much like the coverage and profiler subproviders, the `RevertTraceSubprovider` will inject itself into calls to `eth_sendTransaction`, `eth_call`, and `eth_estimateGas`. It gets the trace data for each transaction, keeps track of the call stack, and looks for the `REVERT` opcode. If it sees the `REVERT` opcode, it will simply print out the stack trace which led to the revert.
In effect this means that if our tests cause a revert, we will be able to see the origin of that revert as a line number in a Solidity file 🎉 
It's not perfect, but it's a good starting point. One thing we would like to add …

Introduce subprovider for printing revert stack traces

---

packages/website/ts/components/portal/portal.tsx
packages/website/ts/components/relayer_index/relayer_grid_tile.tsx
packages/website/ts/components/relayer_index/relayer_index.tsx
packages/website/ts/components/top_bar/top_bar.tsx
packages/website/ts/components/ui/image.tsx
packages/website/ts/types.ts

Update relayer grid tile design and added max width to the portal layout
Previous screenshot header images were not really useful, margins increase readability

Change relayer grid tile to use logos and primary colors

---

packages/contracts/src/contracts/current/protocol/Exchange/MixinWrapperFunctions.sol
packages/contracts/src/contracts/current/protocol/Exchange/interfaces/IWrapperFunctions.sol

Returns a `FillResults` instance for  all derivatives of `batchFillOrders`. This is useful for certain external contracts (like the forwarding contract), and also creates a consistent interface (now all fill methods return a `FillResults`).
Note that `makerAssetFilledAmount` and `takerAssetFilledAmount` do not actually give much information unless we know that the function was called with the same `makerAsset` and `takerAsset` for each order.
*   [ ] Added new entries to the …

Make batchFill methods return FIllResults struct

---

packages/contracts/src/contracts/current/protocol/AssetProxy/ERC20Proxy.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/ERC721Proxy.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/MixinERC20Transfer.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/MixinERC721Transfer.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/libs/LibAssetProxyErrors.sol
packages/contracts/src/contracts/current/protocol/AssetProxy/libs/LibTransferErrors.sol

Split the Transfer implementation and the AssetProxy-ness so the Transfer impl can be mixed in without the AssetProxy.
This is useful for the Forwarding contract as we can get the validation and the and safeTransfer without the AssetProxy public methods.

Split transfer implementation and AssetProxyMixin

---

packages/website/ts/blockchain.ts
packages/website/ts/blockchain_watcher.ts

In the `Wallet` component, ether balance loads significantly later than other token balances. This is because we poll for users ether balance and network state on a 5s timer in the `BlockchainWatcher` class. To fix this problem we just load the user's ether balance and network state before starting the timer.
Ether balance doesn't load until 5s delay, looks like a bug.
Manually
*   [ ] Labeled this PR with the 'WIP' label …

Check network state immediately instead of waiting for delay

---

packages/website/ts/components/portal/drawer_menu.tsx
packages/website/ts/components/top_bar/provider_display.tsx
packages/website/ts/components/top_bar/top_bar.tsx
packages/website/ts/components/ui/identicon.tsx
packages/website/ts/components/ui/image.tsx
packages/website/ts/utils/utils.ts

* Abstract out logic that renders strings such as "account loading" and "no wallet detected"
* Remove use of empty identicon when no wallet is loaded and replace with a grey circle.
* Use `Container` and `Text` components instead of inline styling
DRY
Manually

Consolidate account state display message logic

---

packages/website/ts/components/portal/portal.tsx

The bug was that we were only refreshing token balances in `componentWillMount`, now we selectively fetch them in `componentDidUpdate`.
Manually

Fix bug where we do not fetch balances on wallet login

---

packages/sol-cov/src/collect_coverage_entries.ts
packages/sol-cov/src/coverage_subprovider.ts
packages/sol-cov/src/source_maps.ts

When solidity generates source maps during contract compilation, the
contracts are referred to by an id, which corresponds to an array index.
We may not want to cover all sources that were included in a compilation,
but because we use array indexes (vs. the id that is provided by solidity
compiler) to map the contract to the sourceMap, the provided sourceCodes
array must include the code at the correct index. This can result in
empty slots in the sourceCodes array.
This commit allows the coverage to only be collected for the contracts
with provided sourceCode.
Tested with our repos. I was not able to run `yarn test` as it failed before I made any changes
*   [ ] …

[sol-cov] Only collect coverage for provided sources

---

packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol

This code was unreachable, as it had the exact same condition as line 206.
Line 206 checks for signatureType == SignatureType.PreSigned. This was repeated on line 236, but that condition could never be met after the condition on line 206.

Remove unreachable PreSigned check

---

packages/sol-cov/src/revert_trace_subprovider.ts
packages/sol-cov/src/utils.ts

This PR fixes two bugs in sol-cov:
1. There was sometimes an infinite loop being triggered due to a bug in a `while` loop in __revert_trace_subprovider.ts__.
2. The wrong contract data was sometimes being returned by `getContractDataIfExists`, especially when dealing with interfaces.
Run `SOLIDITY_REVERT_TRACE=true yarn wsrun test contracts` and verify output.
*   [ ] Labeled this PR with the 'WIP' label if it is a work in …

Fix some bugs in sol-cov

---

packages/contracts/compiler.json

Efficiency gains by setting `compilerRuns = 1000000`. After 1MM there were no longer any efficiency gains. There is no build time difference between `compilerRuns=200` and `compilerRuns=1000000`.
```
Benchmarks are taken from a single, unexceptional test case for each function:
`fillOrder`: `should transfer the correct amounts when makerAssetAmount === takerAssetAmount`
`cancelOrder`: `should be able to cancel a full order`
`cancelOrdersUpTo`: `should cancel only orders with a orderEpoch less than existing orderEpoch`
compilerRuns=200:
`fillOrder` = 193,803
`cancelOrder` = 66,652
`cancelOrdersUpTo` = 45,154
compilerRuns=1,000,000:
`fillOrder` = 187,779
`cancelOrder` = 65,968
`cancelOrdersUpTo` = 44,878
Savings:
`fillOrder` = 3%
`cancelOrder` = 1%
`cancelOrdersUpTo` = 0.06%
```
*   [ ] Bug …

Updated compiler runs to be 1,000,000

---

packages/website/ts/components/portal/portal.tsx
packages/website/ts/style/z_index.ts

More z-index fun!! This actually cleaned things up a bit.
Hover over a tile and scroll down and notice that it doesn't show up over the topbar anymore!

Fix issue where hovered tiles appear over top bar

---

packages/contracts/src/contracts/current/protocol/Exchange/MixinTransactions.sol

Rewrote `hashZeroExTransaction` in assembly. Similar to what @Recmo did in [this RP](https://github.com/0xProject/0x-monorepo/pull/730/files).
Saved ~1k gas. Benchmarked using test on line 134 of `transactions.ts` (`should transfer the correct amounts when signed by taker and called by sender`).
No new tests were created. All existing tests pass.
* …

Converted `hashZeroExTransaction` to assembly. Saves 1k gas

---

packages/order-utils/test/order_hash_test.ts

This was testing end to end by deploying an Exchange contract on ganache and requesting it to hash the 0 order. With this hash (and contract address) as fixture data, it is then confirmed as a known data test in the order-utils package. 

Fix known order hash value test in order-utils

---

packages/website/package.json
packages/website/ts/components/wallet/wallet_disconnected_item.tsx
packages/website/ts/types.ts
packages/website/ts/utils/constants.ts
packages/website/ts/utils/utils.ts
yarn.lock

* Added logic in the `Wallet` component to change the metamask installation link for different browsers that support metamask.
* If we encounter a browser other than Opera, Firefox, or Chrome, we link the user to the metamask home page 
* Mobile path to come later
* Run through the onboarding flow in a variety of different browsers, verify that the installation link takes you where you expect to be
*   [ ] Labeled this PR …

Change metamask install link based on browser

---

packages/sol-cov/src/ast_visitor.ts
packages/sol-cov/src/collect_coverage_entries.ts
packages/sol-cov/test/collect_coverage_entries_test.ts
packages/sol-cov/test/fixtures/contracts/SolcovIgnore.sol

Adds functionality similar to istanbul's [ignore](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) to exclude a block of code from the coverage report
add `/* solcov ignore next */` before any block of code in the solidity source to exclude that block from the coverage report
*   [ ] Labeled this PR with the labels …

[sol-cov] add ability to ignore covering specific code blocks

---

packages/website/ts/index.tsx
packages/website/ts/pages/not_found.tsx
packages/website/ts/types.ts

* Fix buggy `NotFound` component
* Create a new route `/docs` that goes to the 0x.js docs
* How come the type checking didn't catch this? Does it not work for jsx?
* Try going to `/docs` verify that 0x.js docs pops up
* Try going to `/hello` or some other unregistered route, verify a 404 page shows up
*   [ ] Labeled this PR with the labels …

Fix NotFound component and render 0x.js docs for /docs

---

.circleci/config.yml
packages/dev-utils/package.json
packages/dev-utils/src/blockchain_lifecycle.ts
packages/devnet/run.sh

There's a weird bug we've known about for a long time having to do with the devnet/Geth. If you try to deploy a contract, it will fail if there are less than 3 blocks on the chain. To address this, we introduced a hack in the __run.sh__ file, which is run when the devnet is initialized. The hack was to simply send 3 transactions with a value of 0, effectively increasing the length of the chain by 3 without really changing anything else.
However, @fabioberger reported a bug where Geth was sometimes resetting the block number all the way back to 0 (and resetting any corresponding state). This meant that the next time you tried to deploy a contract after this happened, it would fail.
This PR improves the reliability of the minimum block hack by moving it out of the __run.sh__ file and into …

Improve reliability of the minimum block number hack for devnet/geth

---

packages/contracts/src/utils/assertions.ts
packages/contracts/test/exchange/match_orders.ts

This PR fixes the assertions to work for an edge case on Geth: `sendTrasnaction` succeeds but the txReceipt has a status code of 0, indicating a failure.

Update expectRevertReasonOrAlwaysFailingTransactionAsync to check status codes

---

packages/subproviders/package.json

`yarn build` was giving the following warning:
```
gene@precision5510:~/0x-monorepo/packages/subproviders$ yarn build
yarn run v1.7.0
warning package.json: "dependencies" has dependency "@0xproject/typescript-typings" with range "^0.4.1" that collides with a dependency in "devDependencies" of the same name with version "^0.4.2"
$ tsc && copyfiles -u 3 './lib/src/monorepo_scripts/**/*' ./scripts
Done in 2.82s.
```
*   [X] Bug fix (non-breaking change which fixes an issue)
*   [ ] …

in subproviders/package.json, cite typescript-typings only once

---

packages/website/ts/blockchain.ts
packages/website/ts/utils/backend_client.ts

* The `TokenRegistryWrapper` `getTokensAsync()` method makes one eth_call for each token in the token registry
* With the addition of new tokens in the token registry this process broke down (150 concurrent requests to infura)
* This async step is on the critical path for portal to finish loading and is causing slow load times
* In order to mitigate this we now make one api call to our backend to retrieve the the token information on mainnet and fallback to previous behavior on testnets because we do not index testnet token info in our DBs
* Switch back and forth between networks
* Add / remove tokens
* Verify normal behavior
*   [ ] Breaking change (fix or feature …

Grab token registry information from our DB for mainnet

---

PULL_REQUEST_TEMPLATE.md

Instead of using a task list to indicate Types of Changes in a PR, have contributors uncomment bullets instead.
I get mildly annoyed when I see a PR summary, such as in [the list of PR's](https://github.com/0xProject/0x-monorepo/pulls), and it says "X of 8", meaning that X of 8 task list items have been completed.  Having some tasks that will *never* be completed (eg the `Bug fix` item on a `New feature` PR) defeats the purpose of the task list, and makes the "X of 8" summary unreliable enough that it just gets ignored.
In the future I think we can put more thought into the actual "Checklist" items in the template, to phrase them such that people should check them off if they're undone and not-applicable.  (For example, perhaps the first one could be "Documentation has been updated or …

use bullets, not a task list, for Types of Changes

---

packages/dev-utils/src/blockchain_lifecycle.ts

This PR fixes a subtle bug that can occur when using `increaseTimeAndMineBlockAsync` in conjunction with `revertAsync` on Geth.
`increaseTimeAndMineBlockAsync` mines a dummy block in order to set the timestamp of the latest block in the chain to the desired time + offset. (This is necessary because our smart contracts only know the time by looking at the latest block timestamp).
However, `revertAsync` can revert the dummy transaction we mined, making it so that the time offset is no longer visible on the chain. Even though there is not a block timestamp reflecting the time offset, it ***does*** still exist. From Geth's perspective that time still passed and it is working in the future. The mismatch between Geth's view of time and the latest block timestamp can cause problems.
There is a …

Mine a dummy block in blockchain_lifecycle to re-apply any time offset

---

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol
packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol
packages/contracts/src/2.0.0/protocol/Exchange/interfaces/IWrapperFunctions.sol
packages/contracts/test/exchange/core.ts
packages/contracts/test/exchange/wrapper.ts
packages/contracts/test/utils/exchange_wrapper.ts

This doesn't add a ton of functionality, but allows us to easily validate a batch of orders with a single RPC call.
TODO: Add tests

Add getOrdersInfo function

---

packages/json-schemas/CHANGELOG.json
packages/json-schemas/schemas/call_data_schema.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/crypto.ts

Check for TypedArray when hashing data in order-utils crypto
Rename json schema call data id to CallData. 
Support TypedArray when hashing data in order-utils. Ethereumjs-utils uses safe-buffer which can support both buffers and typed arrays. In certain environments (browsers) a TypedArray is returned, though lodash does not treat both cases as Buffer (`_.isBuffer` check fails). 

Rename json schema call data id to CallData. 

---

packages/contracts/package.json
packages/order-utils/package.json
yarn.lock

ZeroEx.decodeERC20AssetData was incorrectly decoding some encoded ERC20 token addresses. Turns out to be due to a bug (documented in the Changelog here: https://github.com/ethereumjs/ethereumjs-abi/blob/master/CHANGELOG.md#065---2017-12-07) where addresses starting with 0 were not properly decoded relative to their actual type.
Packages (contracts, order-utils) are using ethereumjs-abi 0.6.4. 0.6.5 fixes this.

0x.js v2: fix decodeAssetData for addresses starting in 0

---

PULL_REQUEST_TEMPLATE.md

Goal is to make it so that every PR should check off every checklist item before it is considered complete.
Removed mention of labels.  Since contributors outside the org don't have permission to add labels, it's not possible for any such contributor to ever check those items off.  Opted instead to prescribe bracketed PR title prefixes, which are accessible to all.
Re-ordered checklist items to better represent chronological progress.
*  Meta

make PR template checklist more useful

---

packages/contract-wrappers/src/contract_wrappers/forwarder_wrapper.ts
packages/json-schemas/CHANGELOG.json
packages/json-schemas/schemas/basic_type_schemas.ts
packages/json-schemas/test/schema_test.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/constants.ts
packages/order-utils/src/index.ts
packages/order-utils/src/market_utils.ts
packages/order-utils/test/market_utils_test.ts
packages/order-utils/test/utils/test_order_factory.ts

* We need a way to take a set of orders and an amount of maker asset to fill as input and output a subset of orders that cover the fill amount
* We need a way to take a set of orders and find the total amount of fees required to fill them
```bash
yarn install && PKG=@0xproject/order-utils yarn build
cd packages/order-utils && yarn test
```

Add marketUtils object for assisting with market buy calculations

---

.circleci/config.yml
packages/0x.js/CHANGELOG.json
packages/0x.js/test/0x.js_test.ts
packages/base-contract/CHANGELOG.json
packages/base-contract/src/index.ts
packages/base-contract/test/base_contract_test.ts
packages/contract-wrappers/CHANGELOG.json
packages/contract_templates/partials/callAsync.handlebars
packages/contract_templates/partials/tx.handlebars
packages/contracts/test/exchange/signature_validator.ts
packages/fill-scenarios/CHANGELOG.json
packages/order-utils/CHANGELOG.json
packages/order-utils/test/signature_utils_test.ts
packages/order-watcher/CHANGELOG.json
packages/typescript-typings/types/ethers/index.d.ts
packages/utils/package.json
packages/utils/src/abi_utils.ts
packages/utils/test/abi_utils_test.ts
packages/utils/tsconfig.json

This PR adds a new static method `strictArgumentEncodingCheck` to `BaseContract`. This method is called in `callAsync` and `sendTransactionAsync` in all contract templates, and its purpose is to protect against encoding-related bugs. It does this by performing a simple (on the surface at least) check:
1. First we encode the arguments we are about to send.
2. Then we decode them.
3. We compare the original arguments to the decoded ones to make sure nothing has changed.
After I added this strict check, I also updated some of our tests as needed. There were some cases where we were relying on implicit padding or type coercion by the encoder. In such cases, we are now more exact about what arguments we pass through to smart contracts.
Just run `yarn test`.
* New feature (non-breaking change …

Add strictArgumentEncodingCheck to BaseContract and use it in contract templates

---

packages/contracts/src/2.0.0/protocol/Exchange/MixinAssetProxyDispatcher.sol
packages/contracts/src/2.0.0/protocol/Exchange/MixinTransactions.sol
packages/contracts/src/2.0.0/protocol/Exchange/libs/LibAbiEncoder.sol
packages/contracts/src/2.0.0/test/TestExchangeInternals/TestExchangeInternals.sol
packages/contracts/src/2.0.0/test/TestLibs/TestLibs.sol
packages/contracts/test/utils/exchange_wrapper.ts
packages/contracts/test/utils/fill_order_combinatorial_utils.ts
packages/migrations/package.json

- Test `FillResults` and `abiEncodeFillOrder` within the combinatorial tests for `fillOrder`
- Increment the free memory pointer at the end of the assembly blocks in `dispatchTransferFrom` and `abiEncodeFillOrder`. It _shouldn't_ be an issue to overwrite this memory (which was happening previously), but feels like a good safety addition.

[contracts] Test fillOrder return values and abiEncodeFillOrder

---

packages/sol-compiler/package.json
packages/sol-compiler/src/cli.ts
packages/sol-resolver/CHANGELOG.json
packages/sol-resolver/src/resolvers/npm_resolver.ts

This PR fixes the `Error: EISDIR: illegal operation on a directory` bug that occurs when trying to compile contracts. I also added source map support to sol-compiler to make issues like this easier to track down in the future.
Run `yarn compile` in the contracts package.

fix(sol-compiler, sol-resolver): Bug where sol-resolver tried to read a directory

---

packages/order-utils/CHANGELOG.json
packages/order-utils/src/index.ts
packages/order-utils/src/rate_utils.ts
packages/order-utils/src/sorting_utils.ts
packages/order-utils/test/rate_utils_test.ts
packages/order-utils/test/sorting_utils_test.ts

* Add utilities for calculating fee-adjusted rates
* Add utilities for sorting order by best fee-adjusted rate
When calculating rates for orders we need to take into account how much fees the taker needs to pay to fill the order. In the case of fee orders (ZRX/WETH) the fee is taken out of the makerAmount. In the case of non ZRX orders (ex. REP/WETH) a feeRate can be provided to estimate how much takerAsset is actually required to fill that order when performing fee abstraction
```bash
yarn install && PKG=@0xproject/order-utils yarn build
cd packages/order-utils && yarn test
```
*   [x] Prefixed the title of this PR with `[WIP]` if it is a work in progress.
*   [x] Prefixed the title of this PR with bracketed package name(s) …

[order-utils] Add rate and sorting utilities

---

packages/contracts/test/exchange/fill_order.ts
packages/contracts/test/utils/fill_order_combinatorial_utils.ts
packages/contracts/test/utils/order_factory_from_scenario.ts
packages/contracts/test/utils/types.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/order_state_utils.ts
packages/order-utils/test/order_state_utils_test.ts
packages/order-watcher/test/order_watcher_test.ts
packages/types/src/index.ts
packages/website/ts/utils/utils.ts

#922 
Previously our min fillable calculation would throw a rounding error
when encountering a valid order (with a small maker amount). This was
inconsistent with the on-chain logic which allowed this order to be
filled.
e.g:
```
makerAssetAmount: new BigNumber('10'),
takerAssetAmount: new BigNumber('10000000000000000'),
```
Old logic would perform:
```
minFillableTakerAssetAmountWithinNoRoundingErrorRange = signedOrder.takerAssetAmount
.dividedBy(ACCEPTABLE_RELATIVE_ROUNDING_ERROR)
.dividedBy(signedOrder.makerAssetAmount);
```
```
minFillableTakerAssetAmountWithinNoRoundingErrorRange 
=> 10000000000000000/0.0001/10
sidedOrderRelevantState.remainingFillableAssetAmount.lessThan(
minFillableTakerAssetAmountWithinNoRoundingErrorRange)
=> false -> RoundingError
```
*   [ ] Prefixed the title …

[Order-utils] Order is valid when maker amount is very small

---

CODEOWNERS
packages/website/package.json
packages/website/ts/utils/utils.ts

* Some changes were made to website assuming that it is on the latest RC versions of the packages, this PR reverts those changes
* The changes made it past CI because of the extra `exit 0` that was appended to the website package's build command
* The exit 0 was added a long time ago to silence uglify errors which seem to be fixed now
* This PR
```bash
yarn install && PKG=@0xproject/website yarn build
```

[website] Revert changes to website causing it to fail building

---

packages/json-schemas/schemas/relayer_api_fee_recipients_response_schema.ts

We use ids for top-level schemas (mostly for the json validator we export). The OpenAPI json schema validator doesn't like to see these ids. In the sra-api json-schema pre-processing logic we remove these ids, but since this one is nested and we only remove ids from top-level objects, it was making the validator fail. I just removed the id on the sub-schema because we never have to reference it directly.

[json-schemas] Remove superflous id from relayer api fee recipients json schema

---

packages/contract_templates/contract.handlebars

BlockParam unrolls into number | BlockParamLiteral, though BlockParamLiteral does not get imported. This results in type build errors in downstream projects where tslint checks libs
#1025 
Temporary workaround is to add `"skipLibCheck": true` to tslint config file.

[contract_templates] Issue #1025 BlockParam unroll

---

packages/contracts/test/exchange/internal.ts

This PR fixes a bug introduced in https://github.com/0xProject/0x-monorepo/pull/1005.
When there is a revert reason, both Geth and Ganache return an error message which includes that revert reason. The exact error messages differ, so the approach we have been using for months is to check if the expected error message is contained in the actual error message.
Start the devnet and then run:
```
PKG=contracts TEST_PROVIDER=geth yarn test
```
*   [ ] Add new entries to the …

Use correct error message for division by zero

---

packages/0x.js/src/index.ts
packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/contract_wrappers.ts
packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts
packages/contract-wrappers/src/fetchers/asset_balance_and_proxy_allowance_fetcher.ts
packages/contract-wrappers/src/fetchers/order_filled_cancelled_fetcher.ts
packages/contract-wrappers/src/index.ts
packages/order-watcher/src/order_watcher/order_watcher.ts
yarn.lock

Currently, `contract-wrappers` does not ship with the fill order validation methods it previously had. I've added them back since they are used in both the 0x-Starter-Project and 0x Portal. Eventually, these will be replaced with more efficient implementations that use [OrderValidator contract](https://github.com/0xProject/0x-monorepo/pull/985).
But for the launch, we need these back in action.

Temporarily Add Back Validation Methods

---

packages/ethereum-types/src/index.ts

Currently, my contract has events that take a `uint256` array  (e.g. `emit Transfer(address, address, uint256[])` ) and typescript complains that ContractEventArg does not support this.
Test to transpile using `tsc` after creating wrapper contract with a contract that has a `uint256` array as event argument. 
Bug fix (non-breaking change which fixes an issue)
*   [ x ] Prefix PR title with bracketed package name(s) corresponding to the changed package(s). For example: `[sol-cov] Fixed bug`.

[ethereum-types] Add BigNumber[] in ContractEventArg Type Definition

---

packages/web3-wrapper/CHANGELOG.json
packages/web3-wrapper/src/web3_wrapper.ts

Addressess: https://github.com/0xProject/0x-monorepo/issues/1076 by also checking that the `blockNumber` in the returned `transactionReceipt` is not `null`.

Fix awaitTransactionMinedAsync for new Parity version

---

packages/contract-wrappers/src/contract_wrappers/contract_wrapper.ts
packages/contract-wrappers/test/subscription_test.ts
packages/contracts/test/multisig/multi_sig_with_time_lock.ts
packages/contracts/test/utils/block_timestamp.ts
packages/order-watcher/src/order_watcher/event_watcher.ts
packages/web3-wrapper/CHANGELOG.json
packages/web3-wrapper/src/web3_wrapper.ts
packages/web3-wrapper/test/web3_wrapper_test.ts

Currently `web3Wrapper.getBlockAsync` throws:
```
TypeError: Cannot read property 'difficulty' of null
```
If the request for a particular block fails. A block request could fail if a node isn't fully synced, or if it's become uncle'd, among other reasons. The Ethereum JSON RPC spec specified returning `null` for requests where the block cannot be found.
This PR therefore renames `getBlockAsync` to  `getBlockIfExistsAsync` and returns `undefined` (in-line with our codebase conventions) if the block was not found. 
*   [ ] …

Fix block fetch error if block not found

---

packages/order-utils/CHANGELOG.json
packages/order-utils/src/signature_utils.ts

Fixes: https://github.com/0xProject/0x-monorepo/issues/1095

Add address normalization to isValidECSignature method

---

packages/sol-compiler/src/compiler.ts

[Fix bug where all source codes are included in each artifact.](https://app.asana.com/0/684263176955174/842516551768097/f)
> @albrow  [8:07 PM]
> Okay as far as I know, the issue first appeared after your PR for compiling contract code in batches: https://github.com/0xProject/0x-monorepo/pull/965
> What appears to be happening is that the “sources” and “sourceCodes” field for each artifact includes *all* the source code for all other contracts. This is making artifact files much much bigger than they need to be.
I modified the artifact persistence logic to include only the source codes for the target artifact (and its dependencies (recursively)), out of the larger set of compilation outputs, which includes all of the other contracts compiled together in that run of the compiler.
* Bug fix …

[WIP] [sol-compiler] persist artifacts with only relevant sources

---

package.json
packages/monorepo-scripts/CHANGELOG.json
packages/monorepo-scripts/src/utils/changelog_utils.ts
yarn.lock

Down under is in the future and causes many conflicts when formatting the timestamp in the local context. All previous releases jumped a day ahead. By setting this to UTC we will have consistent formatted dates in the changelogs no matter where one publishes from.
npm-cli-login fails on node 10 as a deprecation in node 9 has finished. This package appears to be unmaintained so we now have a fork with a fix
Before:
```diff
-## v1.0.8 - _October 4, 2018_
+## v2.0.0 - _October 17, 2018_
+
+    * Add support for `eth_signTypedData`. (#1102)
+    * Added `MetamaskSubprovider` to handle inconsistencies in Metamask's signing JSON RPC endp
+    * Removed `SignerType` (including `SignerType.Metamask`). Please use the `MetamaskSubprovid
+    * Updated to use new modularized artifacts and the latest …
```

[monorepo-scripts] Format changelog dates as UTC timezone +0:00

---

packages/asset-buyer/src/asset_buyer.ts
packages/asset-buyer/src/constants.ts
packages/asset-buyer/src/order_providers/standard_relayer_api_order_provider.ts
packages/asset-buyer/src/utils/buy_quote_calculator.ts
packages/asset-buyer/src/utils/order_provider_response_processor.ts
packages/asset-buyer/src/utils/order_utils.ts
packages/asset-buyer/test/buy_quote_calculator_test.ts

* Some calculations in the AssetBuyer were performing rounding that was inconsistent with that of the Forwarder contract, this was causing us to send in too little ETH / ZRX orders to cover worst case buys
* This PR adds various utility methods to perform calculations in the same manner as the Forwarder and incorporates them into quote calculations
* This PR also includes an optimization that de-duplicates requests for ZRX orders from the orderProvider when the target asset to buy is the ZRX token
* Unit tests
* …

[asset-buyer] Fix calculation for ETH and ZRX amount to cover orders

---

packages/asset-buyer/CHANGELOG.json
packages/asset-buyer/src/asset_buyer.ts
packages/asset-buyer/src/utils/buy_quote_calculator.ts
packages/instant/public/index.html
packages/instant/src/components/buy_button.tsx
packages/instant/src/components/buy_order_state_buttons.tsx
packages/instant/src/components/zero_ex_instant_provider.tsx
packages/instant/src/containers/selected_asset_buy_order_state_buttons.ts
packages/instant/src/containers/selected_erc20_asset_amount_input.ts
packages/instant/src/index.umd.ts
packages/instant/src/redux/reducer.ts
packages/instant/src/types.ts
packages/instant/src/util/assert.ts

* Add `affiliateFeeInfo` as a prop to instant and option for the umd entry point
* Also fix a couple bugs in asset buyer where we were accidentally overriding default values for some methods and also not rounding when calculating the affiliate fee
```
http://localhost:5000/?feeRecipient=0x14e2f1f157e7dd4057d02817436d628a37120fd1&feePercentage=0.02
```
* New feature (non-breaking change which adds functionality) 

[instant][asset-buyer] Implement affiliateInfo prop

---

packages/instant/src/containers/selected_erc20_asset_amount_input.ts

Previously, when you entered "0" into instant it would show "NaN" for token price, and the buy button would still be highlighted.
With this change, we don't get a buy quote for 0, leaving the details to show the "-" (non pulsating) and the buy button not to be enabled

[instant] Fix NaN issue with zero input

---

packages/instant/src/components/amount_placeholder.tsx
packages/instant/src/components/buy_button.tsx
packages/instant/src/components/buy_order_progress.tsx
packages/instant/src/components/buy_order_state_buttons.tsx
packages/instant/src/components/erc20_asset_amount_input.tsx
packages/instant/src/components/erc20_token_selector.tsx
packages/instant/src/components/instant_heading.tsx
packages/instant/src/components/order_details.tsx
packages/instant/src/components/placing_order_button.tsx
packages/instant/src/components/scaling_input.tsx
packages/instant/src/components/search_input.tsx
packages/instant/src/components/secondary_button.tsx
packages/instant/src/components/sliding_error.tsx
packages/instant/src/components/sliding_panel.tsx
packages/instant/src/components/ui/index.ts
packages/instant/src/components/zero_ex_instant_container.tsx
packages/instant/src/components/zero_ex_instant_overlay.tsx
packages/instant/src/redux/reducer.ts

Per convo here: https://github.com/0xProject/0x-monorepo/pull/1201#discussion_r229795463 , this PR changes instant to import UI components directly, instead of through an `index` file.
This makes our importing pattern consistent, and reduces mental overhead of where to import a local component from.

[instant] chore: Import UI components directly

---

.circleci/config.yml
packages/website/package.json

* Add a new `build:prod` command to `packages/website/package.json` that calls webpack with the production flag.
* Ensure that `build:prod` is being used in places where we want to. I.e. CI and deployment
* Default to `build:dev` when using the `build` command
* Try out the different commands
* `yarn build` on website should take < 30s now, assuming dependent packages are already built

[website] Turn off production flag when building locally

---

packages/web3-wrapper/src/web3_wrapper.ts

#1240 
#622 
In 0x packages we attempt to validate a contract call by performing an `eth_call`  before submitting a transaction. This is in order to detect any reverts or revert with reasons. For example, an `eth_call` for `cancelOrder`.
```
{id: 3, jsonrpc: "2.0", params: [{to: "0x4530c0483a1633c7a1c97d2c53721caff2caaaaf",…}, "latest"],…}
id: 3
jsonrpc: "2.0"
method: "eth_call"
params: [{to: "0x4530c0483a1633c7a1c97d2c53721caff2caaaaf",…}, "latest"]
0: {to: "0x4530c0483a1633c7a1c97d2c53721caff2caaaaf",…}
data: "0xd46b02c30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000ea95a7a25506c9f70fb7bc50877c435a609353b2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

[web3-wrapper] Throws when contract returns null

---

packages/order-watcher/CHANGELOG.json
packages/order-watcher/src/order_watcher/dependent_order_hashes_tracker.ts

When we try to remove an order that has makerToken == ZRX we tried to remove ZRX from dependent order hashes twice and it failed.

[@0x/order-watcher] Fix a bug in an order removal when maker token is ZRX

---

.prettierignore
python-packages/order_utils/setup.py
python-packages/order_utils/src/index.rst
python-packages/order_utils/src/zero_ex/json_schemas/__init__.py
python-packages/order_utils/src/zero_ex/json_schemas/schemas
python-packages/order_utils/src/zero_ex/order_utils/__init__.py
python-packages/order_utils/stubs/jsonschema/__init__.pyi
python-packages/order_utils/test/test_generate_order_hash_hex.py

Added a JSON schema Python module, and changed `generate_order_hash_hex()` to use it to validate the order.
In order to conform to the schema, though, had to rename quite a few fields, from snake case to camel.
`./setup.py test && ./setup.py lint && ./setup.py build_sphinx && tox`
All but the `tox` part is integrated with CI.

fix(order_utils.py): validate order w/json schema

---

python-packages/order_utils/src/zero_ex/order_utils/__init__.py

Don't load contract artifacts until they're actually asked for, and then cache them for the next call.
This fixes a problem with documentation generation on readthedocs.io in that it generates the docs without actually installing the packages, but because it wasn't actually installing them then the data files (artifacts) weren't available, so the process was failing.  In any case, such lazy loading is desirable anyways, so I'm glad to have the impetus to do this.
`./setup.py test`, which is integrated with CI.
* …

[order_utils.py] lazy load contract artifacts

---

packages/instant/src/components/zero_ex_instant_provider.tsx
packages/instant/src/containers/selected_erc20_asset_amount_input.ts
packages/instant/src/redux/async_data.ts
packages/instant/src/util/buy_quote_updater.ts
packages/instant/src/util/heartbeater_factory.ts

Don't trigger errors when buy quotes are updated from heartbeat
Type in large amount of asset, watch error come up .  Wait for heartbeat to trigger, and you should not see error pop up again.

[instant] Don't show errors from heartbeat buy quote calls

---

package.json

Run ganache
```
cd 0x-monorepo
yarn ganache
```
Another terminal, run migrate
```
cd packages/migrations
yarn migrate:v2
```
Then you will get these errors.
```
❯ yarn migrate:v2
yarn run v1.12.3
run-s build script:migrate:v2 run−sbuildscript:migrate:v2 tsc -b
$ node ./lib/migrate.js --contracts-version 2.0.0
{ message: 'Exceeds block gas limit',
code: -32000,
data:
{ stack: 'r: Exceeds block gas limit\n    at StateManager.queueTransaction (/Users/akagi201/Documents/src/github.com/0xProject/0x-monorepo/node_modules/ganache-cli/build/cli.node.js:149:69564)\n    at s.eth_sendTransaction (/Users/akagi201/Documents/src/github.com/0xProject/0x-monorepo/node_modules/ganache-cli/build/cli.node.js:149:81687)\n    at s.handleRequest (/Users/akagi201/Documents/src/github.com/0xProject/0x-monorepo/no …
```

[ganache]: fix exceeds block gas limit error

---

packages/web3-wrapper/CHANGELOG.json
packages/web3-wrapper/src/web3_wrapper.ts

[web3-wrapper] Only unmarshall receipt if blockNumber present

---

PULL_REQUEST_TEMPLATE.md

We now have a bot to label PRs based on files changed. No need to do that manually and easier filtering.

Remove the instruction to prefix PRs with package name from PULL_REQUEST_TEMPLATE.md

---

python-packages/order_utils/setup.py

Fix error in runs of `static-tests-python`.  Apparently there's a bug in the new version of pylint that was released yesterday, which [I've reported](https://github.com/PyCQA/pylint/issues/2612).  While we await the fix for that, this PR pins pylint to the previous version.
Watch CI :smile: 

fix(order_utils.py): work aroud pylint bug

---

packages/contracts/CHANGELOG.json
packages/contracts/contracts/extensions/OrderValidator/OrderValidator.sol
packages/contracts/test/extensions/order_validator.ts

Using `getApproved` isn't reliable since the approval is removed after a single transfer. Therefore, we no longer consider it to be a valid allowance for batch validating orders.

fix: remove getApproved check from OrderValidator

---

packages/instant/src/components/buy_button.tsx
packages/instant/src/util/analytics.ts

Adds the following events:
```
BUY_NOT_ENOUGH_ETH = 'Buy - Not Enough Eth',
BUY_STARTED = 'Buy - Started',
BUY_SIGNATURE_DENIED = 'Buy - Signature Denied',
BUY_SIMULATION_FAILED = 'Buy - Simulation Failed',
BUY_TX_SUBMITTED = 'Buy - Tx Submitted',
BUY_TX_SUCCEEDED = 'Buy - Tx Succeeded',
BUY_TX_FAILED = 'Buy - Tx Failed',
```
Each event has the following properties attached: `assetData`, `assetBuyAmount`, `assetEthAmount`, `feeEthAmount`, `totalEthAmount`, `feePercentage`, `hasFeeOrders`,
Each transaction related event also has a property `txHash` attached.
* Heap live tracking
*   [ ] Add new …

[instant] Add buy events to instant

---

python-packages/order_utils/setup.py

Yesterday I pinned pylint to the previous version, due to a problem with the newest release.  Today they released a new version with the fix, so I'm unpinning it.
Watch CI's `static-tests-python`

fix(order_utils.py): unpin pylint version

---

packages/pipeline/src/data_sources/contract-wrappers/exchange_events.ts

Fixes a timeout issue. Infura suddenly started failing when we request too many blocks at once. This PR reduces the number of blocks per query from 100k to 20k.

[pipeline] Reduce number of blocks per query in pull_missing_events

---

packages/instant/src/components/scaling_input.tsx

I found a bug where if you select MANA token for example, type 5 characters, see the font-size of the input as well as the font-size of the token reduce, and then change to ZRX, the font-size of the input resets to a larger font, but the ZRX symbol remains the same. 
This is because selecting a new token re-renders the input. I solved this by calling `onFontSize` change for the initial render, which seems reasonable. 

[instant] Notify of the used font size for re-renders of scaling input

---

packages/instant/src/components/erc20_token_selector.tsx

React was giving the following warning for the token selector:
> Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
This change stops this error by setting the state to be an empty string instead of undefined

[instant] Fix uncontrolled input warning for token selector

---

packages/instant/src/components/ui/text.tsx

Per Chris: "On hover the token symbol "REP" should be reduced to 50% opacity instead of gray."
The "Select Token" text, and the token symbol are the only `<Text>` elements with `onClick`s, so seems OK to update this globally

[instant] Half opacity on clickable text hover

---

python-packages/order_utils/src/zero_ex/json_schemas/__init__.py
python-packages/order_utils/stubs/jsonschema/__init__.pyi
python-packages/order_utils/test/test_doctest.py
python-packages/order_utils/test/test_json_schemas.py

This PR is a proposed solution for https://github.com/0xProject/0x-monorepo/issues/1316
- Perform regression on schema validation logic
- Extracts `LocalRefResolver()` to the module level
- Creates an instance variable `LOCAL_RESOLVER` that is called by `assert_valid()`
- Changes the method that the resolver uses to fetch the JSON schema: from `resolve_from_url` I changed it to `resolve`, because the latter uses a LRU cache.
- Added `signedOrderSchema` to the `LocalRefResolver()` IDs.
- Added some new unit tests for my work
- Changed the unit test that runs all docstrings to use `importlib` causes my new test to fail sporadically. This is because the old  `load_module()` will also reload modules that are already loaded. Aside from this, `load_module()` is also deprecated in Python 3.4
* …

[order_utils.py] Feature/schema resolver cache

---

packages/instant/src/components/standard_sliding_panel.tsx
packages/instant/src/index.umd.ts
packages/instant/src/redux/analytics_middleware.ts

This fixes
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at d (https://localhost:3000/zrxinstant.js:37:329752)
at window.onpopstate (https://localhost:3000/zrxinstant.js:37:331654)
at window.onpopstate (https://localhost:3000/zrxinstant.js:37:331588)
```
That can occur if:
1. No onpopstate is defined. 
2. Instant is rendered "manually" (not through navigating history) twice in a row. 
Basically we were calling an old version of `removeInstant` which had a closure around an old DOM node that had been deleted because we were mistakenly setting our own `onpopstate` as the "intergrator's" `onpopstate` on the second render... which resulted in us calling the `removeInstant` from the first render...
*   [ ] Prefix PR …

[instant] Fix push to history issue on second full render of instant

---

packages/instant/public/index.html
packages/instant/src/components/payment_method.tsx
packages/instant/src/components/zero_ex_instant_provider.tsx
packages/instant/src/containers/connected_account_payment_method.ts
packages/instant/src/index.umd.ts
packages/instant/src/redux/reducer.ts

Add new top level option `walletDisplayName` that let's the integrator choose the display name of the wallet.
Add a new query param option in our dev environment to let us test this:
ex: `http://localhost:5000/?walletDisplayName=Ledger`
Also fix misaligned colored circle and wallet display name
Try out the link above

[instant] provide a custom wallet display name option

---

packages/instant/src/components/erc20_asset_amount_input.tsx
packages/instant/src/redux/async_data.ts

* Protect against situations where the order provider reports duplicate available assets
* Allow the user to access the token selector in cases where only one asset is available

[instant] render token selector when only one asset is available

---

packages/instant/.dogfood.discharge.json
packages/instant/.production.discharge.json
packages/instant/.staging.discharge.json

With the dotenv PR ( https://github.com/0xProject/0x-monorepo/pull/1364  ), we started losing arguments sent into the build process.  This caused the production build to report to the development heap analytics.
See https://github.com/entropitor/dotenv-cli/issues/8

[instant] Ensure build process receives build arguments

---

packages/instant/src/components/ui/overlay.tsx
packages/instant/src/components/zero_ex_instant_overlay.tsx
packages/instant/src/constants.ts

* Change overlay alpha from `0.9` to `0.7`
* Give a stable class that integrators can identify the overlay close button with
* This is to address a hack in the instex integration: https://0xinstant.instex.io/ where they are trying to id the close button given the auto-generated `styled-components` class, producing the potential for the instex integration to blow up
* We're seeing more and more integrators hack around our overlay so we should probably give more serious thought to supporting an inline version
Observe the class name for the close button
*   [ ] Add new entries to the relevant …

[instant] add stable class name to overlay close button and adjust overlay color

---

packages/instant/public/external.css
packages/instant/src/components/ui/input.tsx
packages/instant/src/components/zero_ex_instant_provider.tsx
packages/instant/src/util/asset.ts

We discovered coingecko was using this code to render REP Instant:
```
zeroExInstant.render({
orderSource: "https://api.radarrelay.com/0x/v2/",
// Initialization options
availableAssetDatas: [
'0xf47261b00000000000000000000000000d8775f648430679a709e98d2b0cb6250d2887ef', // BAT
'0xf47261b000000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359', // DAI
'0xf47261b0000000000000000000000000e41d2489571d322189246dafa5ebde1f4699f498', // 0x 
'0xf47261b0000000000000000000000000d26114cd6EE289AccF82350c8d8487fedB8A0C07',// OMG
'0xf47261b00000000000000000000000001985365e9f78359a9B6AD760e32412f4a445E862',// REP
'0xf47261b00000000000000000000000008f8221afbb33998d8584a2b05749ba73c37a938a',// REQ
'0xf47261b000000000000000000000000027054b13b1b798b345b591a4d22e6562d47ea75a',// AST …
```

[instant] CSS leakage and non-lowercase defaultAssetData fix

---

packages/instant/package.json
packages/instant/src/constants.ts
packages/instant/src/util/analytics.ts
packages/instant/src/util/error_reporter.ts

If an error was coming from a `localhost` script, we were reporting it to Rollbar.  This should fix that and not allow it if we're using a production build.
Here's how I tested this:
* Created an embed page with the dogfood instant.js, with the following code in the index:
```
window.setTimeout(() => {
throw new Error("Manual trigger prod localhost error");
}, 8000);
```
* Saw that this error in `setTimeout` was reported to Rollbar
* Deployed this new change to dogfood
* Saw that this error in `setTimeout` was now not reported to Rollbar anymore
In both situations, I confirmed that the magic number `0€` still reported to Rollbar correctly, to ensure Rollbar was still configured properly
*   [ …

[instant] Don't report localhost errors to Rollbar

---

packages/instant/src/util/buy_quote_updater.ts

Initially, I was trying to be conservative with logging errors, but with the launch I think it'd be good to have more info than less, even if there is some noise.
Before: Any error that we knew could occur (i.e. insufficient liquidity, standard relayer api error), would not be reported to Rollbar
Now: These are all reported to Rollbar
Before: If a quote fetch failed on a _heartbeat_ request, it wasn't logged to heap
Now: These are all reported to heap

[instant] More aggressive error reporting

---

packages/web3-wrapper/CHANGELOG.json
packages/web3-wrapper/src/marshaller.ts
yarn.lock

Fixes: https://github.com/0xProject/0x-monorepo/issues/1394
Decided to convert `gasPrice` and `value` to BigNumbers as they can be larger then 2^53-1 (max JS number amount). I did not change `gas`, since the current gas limit per block is ~8,000,000 gas and we could image this will grow, but it's hard to imagine it ever being close to 2^53-1. Happy for anyone to dispute that last claim.

Fix `value` and `gasPrice` precision bug by returning them as BigNumbers

---

packages/instant/src/components/scaling_amount_input.tsx
packages/instant/src/components/scaling_input.tsx
packages/instant/src/components/ui/input.tsx

As discussed, adding type="number" does make the numeric keyboard appear on mobile, however it also causes some problems around the `onChange` event. Namely, it will allow you type in "1", "1.", "1.0" but will only trigger `onChange` for "1" and "1.0".
The final solution which I'm quite happy with is to just simplify the ScalingInput logic to measure everything in "ch" instead of moving between "ch" and "px" as before, and simply leaving enough room for the decimal at all times.
The only improvement we may want to add is that this "padding" is present at all time. It isn't very noticeable, but it should be pretty easy to make the text fit *perfectly* for when we have a decimal. We will always have to leave padding for when there is no decimal. On the other hand, I like the consistency of …

[instant] Change input to number input, and simplify ScalingInput

---

packages/pipeline/src/scripts/pull_missing_blocks.ts

Since we now need to pull missing blocks for other types of events, not just exchange events, we need to remove this lower bound on the block number.

Fix bug in pull_missing_blocks with incorrect start block

---

packages/instant/src/components/amount_placeholder.tsx
packages/instant/src/components/animations/slide_animation.tsx
packages/instant/src/components/buy_button.tsx
packages/instant/src/components/buy_order_progress.tsx
packages/instant/src/components/buy_order_state_buttons.tsx
packages/instant/src/components/erc20_asset_amount_input.tsx
packages/instant/src/components/erc20_token_selector.tsx
packages/instant/src/components/install_wallet_panel_content.tsx
packages/instant/src/components/instant_heading.tsx
packages/instant/src/components/order_details.tsx
packages/instant/src/components/payment_method.tsx
packages/instant/src/components/payment_method_dropdown.tsx
packages/instant/src/components/placing_order_button.tsx
packages/instant/src/components/scaling_amount_input.tsx
packages/instant/src/components/scaling_input.tsx
packages/instant/src/components/secondary_button.tsx
packages/instant/src/components/section_header.tsx
packages/instant/src/components/sliding_error.tsx
packages/instant/src/components/sliding_panel.tsx
packages/instant/src/components/standard_panel_content.tsx
packages/instant/src/components/standard_sliding_panel.tsx
packages/instant/src/components/time_counter.tsx
packages/instant/src/components/timed_progress_bar.tsx
packages/instant/src/components/ui/dropdown.tsx
packages/instant/src/components/wallet_prompt.tsx
packages/instant/src/components/zero_ex_instant.tsx
packages/instant/src/components/zero_ex_instant_container.tsx
packages/instant/src/components/zero_ex_instant_overlay.tsx
packages/instant/src/components/zero_ex_instant_provider.tsx
packages/instant/src/containers/latest_error.tsx

I started by profiling some keystrokes in Instant: 
The main thing to notice is that there are 3 main render flame-sub-graphs. The input being re-rendered (good), the order details being re-rendered (OK, since that actually displays the amount), and the token selector (bad, takes the longest, and isn't even displayed).
This PR does ~3 things, but the first two aren't that impactful.
1. Convert all `Component` instances to `PureComponent`. There really isn't a downside to doing this, and there is a perf upside.
2. Give all stateless components the static `displayName` attribute. This helps debugging tools know what component they are. 
3. Unmount the token selector when the sliding panel animation finishes. Now that 3rd flame subgraph is gone (sorry, used a different profiler at the end of …

[instant] No more laggy input

---

packages/website/ts/components/button.tsx
packages/website/ts/components/definition.tsx
packages/website/ts/components/dropdowns/dropdown_developers.tsx
packages/website/ts/components/modals/modal_contact.tsx
packages/website/ts/index.tsx
packages/website/ts/pages/market_maker.tsx

* Adds market maker page to the site
* Add new section in the developer dropdown
* Expands the copper lead form to handle both general and market maker lead forms
* I know the way this is being done isn't super scalable for adding new types of forms, but in the interest of time decided to go with the consistent and most straight forward implementation
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/market-maker

[website] Add market making grant program page

---

packages/pipeline/src/scripts/pull_missing_blocks.ts

This PR optimizes the query for finding missing blocks. The old implementation is bogging down our SQL server and occasionally causing queries to take over one hour! In a full-ish database with many events and blocks the new implementation is at least a 1000x performance increase.

Optimize SQL queries in pull_missing_blocks

---

.circleci/config.yml
packages/dev-utils/src/web3_factory.ts
packages/migrations/.gitignore
packages/migrations/Dockerfile
packages/migrations/README.md
packages/migrations/package.json
packages/migrations/src/migrate_snapshot.ts
python-packages/order_utils/setup.py

Added a Docker image for our migrations. Having this as a docker image is helpful for those who do not want to install an entire nodejs stack to run ganache. 
Ganache runs in memory but writes a leveldb to directory `0x_ganache_snapshot`. 
TODO 

Add Docker image and Snapshot commands for migrations

---

python-packages/contract_addresses/README.md
python-packages/contract_artifacts/README.md
python-packages/json_schemas/README.md

Some last-minute README tweaks before I publish these packages.
*   [X] Add tests to cover changes as needed.

In README's, don't mention non-existent tests

---

packages/utils/CHANGELOG.json
packages/utils/src/promisify.ts

The provider injected by the Android opera browser has a `sendAsync` method that returns (undefined, result) instead of (null, result). This was tripping up the code in this diff and breaking instant in Opera.
Strictly speaking, this is a breaking change so I changed the version to 3.0.0, but I think keeping it as v2 would also be acceptable. 

[utils] account for undefined errors in promisify, not only null (and fix instant in Opera)

---

packages/pipeline/migrations/1547153875669-UpdateDDexAPIToV3.ts
packages/pipeline/src/data_sources/ddex/index.ts
packages/pipeline/src/parsers/ddex_orders/index.ts
packages/pipeline/test/parsers/ddex_orders/index_test.ts

DDex script breaking because v2 no longer supported. Upgraded to v3. 
[Changelog](https://docs.ddex.io/#changelog)
Relevant:
* switched base and quote tokens
* removed maxOrderSize
Please review and confirm that `tokenOrder.baseVolume` and `tokenOrder.quoteVolume` are calculated correctly here.
`yarn test`
or
`yarn build && node lib/src/scripts/pull_ddex_orderbook_snapshots.js`

upgrade to ddex api v3

---

contracts/utils/CHANGELOG.json
contracts/utils/contracts/test/TestConstants/TestConstants.sol
contracts/utils/contracts/test/TestLibBytes/TestLibBytes.sol
packages/sol-coverage/src/coverage_subprovider.ts
packages/sol-profiler/CHANGELOG.json
packages/sol-tracing-utils/CHANGELOG.json
packages/sol-tracing-utils/package.json
packages/sol-tracing-utils/src/artifact_adapters/sol_compiler_artifact_adapter.ts
packages/sol-tracing-utils/src/collect_coverage_entries.ts
packages/sol-tracing-utils/src/utils.ts
packages/sol-tracing-utils/test/collect_coverage_entries_test.ts
yarn.lock

* Fix a bug when some parts of the profiling report were missing because of the coverage ignore lines `/* solcov ignore next */`
* `SolCompilerArtifactAdapter` now uses `SolResolver` under the hood which allows to resolve `NPM` dependencies properly. Before it was just throwing.
* Cache the `utils.getContractDataIfExists` leading to faster execution
* `SolCompilerArtifactAdapter` now doesn't return the `ContractData` for interfaces
* Print reasonable error message on bytecode collision

Sol tracing fixes

---

packages/asset-buyer/src/asset_buyer.ts

Per suggestion in PR ( https://github.com/0xProject/0x-monorepo/pull/1512#discussion_r248506087 ), I called `validateAssetDataOrThrow` to validate an assetData parameter, instead of just doing a `assert.isString('assetData', assetData);`.
But -- `validateAssetDataOrThrow` expects the input to be a string -- it calls `.slice` on it.  The test I had was sending in `false` and the code was throwing when it tried to call `.split`.  
So, now we ensure it's a string before we call the `validateAssetDataOrThrow`

[asset-buyer] Fix test (assetData string)

---

packages/sol-tracing-utils/CHANGELOG.json
packages/sol-tracing-utils/src/ast_visitor.ts

Fixes https://github.com/0xProject/0x-monorepo/issues/1530
I don't have an example solidity code and AST where that happens, but if it does - it doesn't hurt to check.

Fix the `cannot read property range of null` bug

---

.circleci/config.yml

Runs of `static-tests-python` were hanging in CircleCI, as reported by @LogvinovLeon and @xianny, with the final output looking like this:
```
Successfully built 0x-contract-addresses
Installing collected packages: 0x-contract-addresses
Found existing installation: 0x-contract-addresses 2.0.0
Uninstalling 0x-contract-addresses-2.0.0:
```
I ssh'd to the CI machine, and reproduced the hang at the terminal.  Interestingly, when I got impatient and hit Ctrl+C to get my prompt back, I got a relevant error traceback:
```    Uninstalling 0x-contract-addresses-2.0.0:
^CCleaning up...
Removed build tracker '/tmp/pip-req-tracker-oqtgj3rz'
Operation cancelled by user
Exception information:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/temp_dir.py" …
```

Fix hang in Python CI test runs

---

packages/instant/src/components/ui/input.tsx

Add a css line to remove number selector for mozilla.
Before
After

Removed number selector for firefox inputs

---

packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/contract_wrappers/order_validator_wrapper.ts

`OrderValidatorWrapper` constructor defaults to the `exchange` address instead of the correct `orderValidator` address

Use correct "orderValidator" address in OrderValidatorWrapper constructor

---

packages/utils/CHANGELOG.json
packages/utils/src/abi_encoder/evm_data_types/bool.ts
packages/utils/test/abi_encoder/evm_data_types_test.ts

There are some cases where the client returns `0x` instead of `0x0...`. 

Decode NULL as False in Abi Encoder

---

contracts/exchange/test/transactions.ts
contracts/exchange/test/utils/exchange_wrapper.ts
contracts/test-utils/CHANGELOG.json
contracts/test-utils/src/index.ts
contracts/test-utils/src/transaction_factory.ts
contracts/test-utils/src/types.ts
packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/utils/transaction_encoder.ts
packages/contract-wrappers/test/transaction_encoder_test.ts
packages/json-schemas/CHANGELOG.json
packages/json-schemas/schemas/zero_ex_transaction_schema.json
packages/order-utils/CHANGELOG.json
packages/order-utils/src/constants.ts
packages/order-utils/src/eip712_utils.ts
packages/order-utils/src/index.ts
packages/order-utils/src/order_hash.ts
packages/order-utils/src/transaction_hash.ts
packages/order-utils/test/eip712_utils_test.ts
packages/order-utils/test/order_hash_test.ts
packages/order-utils/test/transaction_hash_test.ts
packages/types/CHANGELOG.json
packages/types/src/index.ts
python-packages/json_schemas/src/zero_ex/json_schemas/schemas/zero_ex_transaction_schema.json

- Adds `transactionHashUtils` to the `order-utils` package. The other way of hashing a tx is in the `contract-wrappers` package, but you really shouldn't require an `exchange` instance to simply hash a transaction.
- Allows passing a domain into `createTypedData` to override the default.

Add transactionHashUtils to order-utils package

---

packages/utils/CHANGELOG.json
packages/utils/src/abi_encoder/evm_data_type_factory.ts
packages/utils/src/abi_encoder/evm_data_types/method.ts
packages/utils/src/abi_encoder/index.ts
packages/utils/src/abi_encoder/utils/signature_parser.ts
packages/utils/test/abi_encoder/evm_data_types_test.ts
packages/utils/test/abi_encoder/signature_test.ts

** this PR replaces #1591 **
- A collection of tests for creating ABI encoders from signatures. 
- Replaced the signature parser with a much simpler version that uses a parse tree
- New parser allowed for a new convenience function for method encoders from signatures
This must be merged after #1587.

Simplified signature parsing + signature tests

---

packages/dev-utils/CHANGELOG.json
packages/dev-utils/src/web3_factory.ts

While working on the TEC server, I wanted to use our existing Ganache snapshot as a starting point for my tests. I found out however, that I couldn't pass the Web3Factory an existing snapshot DB path. This PR fixes that.

Allow using Web3Factory in-process Ganache with existing snapshot

---

packages/pipeline/migrations/1549479172800-AddTxHashToExchangeEventPrimaryKey.ts
packages/pipeline/migrations/1549499426238-AddTxHashToERC20ApprovalEventPrimaryKey.ts
packages/pipeline/src/entities/erc20_approval_event.ts
packages/pipeline/src/entities/exchange_cancel_event.ts
packages/pipeline/src/entities/exchange_cancel_up_to_event.ts
packages/pipeline/src/entities/exchange_fill_event.ts
packages/pipeline/src/scripts/pull_exchange_events.ts

It was noticed that the `pull_exchange_events.ts` script is regularly failing with the message `error: duplicate key value violates unique constraint "PK_79d3b54710830426f998cd6263b"`, repeated for each of the tables into which it inserts.  This change is to fix that error.
A new migration script will add `transaction_hash` to (or remove it from, for revert) the set of columns that comprise the primary key.
With local DB running as described in README,
```
yarn build
yarn migrate:run
psql --username=postgres --password --host=localhost --command="\d raw.exchange_cancel_events"
```
entering `postgres` for the password, and visually confirm that the `PRIMARY KEY` line includes `transaction_hash`.
Repeat `psql` command for other tables, replacing `exchange_cancel_events` with …

Add migration to fix exchange events primary keys

---

packages/devnet/Dockerfile
packages/devnet/README.md
packages/devnet/run.sh

Truffle uses `eth_subscribe` that only works with Geth over `WebSocket`. This PR adds a `WS` endpoint to `devnode`.
I need it to fix our dev tools truffle example. https://github.com/0xProject/dev-tools-truffle-example/issues/5
For now it just hangs on `eth_subscribe`.

Add WS endpoint to devnode

---

packages/instant/src/components/css_reset.tsx

Etherscan has a global SVG style which messes up the look of instant
Added the following:
```
+++ b/packages/instant/public/index.html
@@ -31,6 +31,10 @@
height: 100vh;
background-color: rgba(0, 0, 0, 0.2);
}
+
+            svg {
+                margin-bottom: -0.4375rem;
+            }
</style>
</head>
```
W/o this commit, looks messed up like on Etherscan.  Fixed w/ this commit

[instant] Reset svg style

---

packages/pipeline/migrations/1550163069315-TokenOrderBookSnapshotsAddMakerAddress.ts

In https://github.com/0xProject/0x-monorepo/pull/1612 I broke `test-pipeline`.
This is because when writing the migrations, I looked at the name for the PRIMARY KEY constraint on `raw.token_orderbook_snapshots` on the QA and prod instances, both called `token_orderbook_snapshots_pkey1`. I do not know how those constraints became named that way, but when you run the migration code on a fresh DB instance that constraint ends up being named `token_orderbook_snapshots_pkey`. 
I think the solution here is to stick with `token_orderbook_snapshots_pkey` and manually rename the name of the constraint on QA and prod for consistency.
-   [ ] Add new entries to the …

Fix inconsistently named constraint in migration

---

packages/website/public/index.html

Appears that we have two of each meta tag between the public/index.html has default meta tags. This may be confusing the google crawler. 

Removed default meta tags in public/index.html

---

python-packages/contract_demo/test/test_exchange.py
python-packages/order_utils/setup.py

I recently updated our fork of web3 to support tuple arrays, to fix #1574.  This PR demonstrates using those changes.
Watch CI :)

Demonstrate calling contracts with tuple arrays

---

contracts/test-utils/src/web3_wrapper.ts
packages/sol-profiler/CHANGELOG.json
packages/sol-profiler/src/cost_utils.ts
packages/sol-profiler/src/profiler_subprovider.ts
packages/sol-tracing-utils/src/revert_trace.ts
packages/sol-tracing-utils/src/trace.ts
packages/sol-tracing-utils/src/trace_info_subprovider.ts
packages/sol-tracing-utils/src/utils.ts

This PR adds a workaround for [ganache issue](https://github.com/trufflesuite/ganache-core/issues/277). This means that now all the dev tools should be working with Ganache as well as Geth.
Try running metacoin profiling with Ganache.

Sol-profiler ganache

---

packages/sol-compiler/CHANGELOG.json
packages/sol-compiler/src/compiler.ts

If the user specifies some compiler settings in `compier.json` but doesn't specify the outputSelection - solidity produces 0 output.
This PR changes the way we merge the default configs in, so it should work.
FIxes https://github.com/0xProject/0x-monorepo/issues/1645

Fix a bug when combining sol-compiler settings from different sources

---

packages/sol-tracing-utils/CHANGELOG.json
packages/sol-tracing-utils/package.json
packages/sol-tracing-utils/src/artifact_adapters/truffle_artifact_adapter.ts

Truffle recently released a major new version which changed the format of `truffle-config.json`.
This PR adds support for that new format.
Fixes: https://github.com/0xProject/0x-monorepo/issues/1650

Fix a bug when TruffleArtifactAdapter was incorrectly parsing the truffle config of the newest version

---

contracts/test-utils/src/coverage.ts
packages/sol-coverage/CHANGELOG.json
packages/sol-coverage/package.json
packages/sol-coverage/src/coverage_subprovider.ts
packages/sol-coverage/src/index.ts
packages/website/md/docs/sol_coverage/usage.md
yarn.lock

Fixes #1635 
Run coverage on erc20. You don't see dependency coverage any more

Allow project specific coverage ignore paths by specifying `config.ignoreFilesGlobs`

---

packages/pipeline/src/data_sources/bloxy/index.ts
packages/pipeline/src/scripts/pull_competing_dex_trades.ts

We were using the `days` parameter, but that's no longer available in
the API, so our fetching of previous days (before "today") was broken.
This change gets rid of the concept of "days", and uses the API's new
`from_date` and `till_date` parameters to fetch previous days' trades.
The change to the query in `getLastSeenTimestampAsync()` was necessary
because it was returning a string (despite the `as Array<{ tx_timestamp:
number }>` cast), which was later causing problems trying to pass that
value into `new Date()`.  It worked before because we were doing some
math operations on it (multiplying it by some numbers), so coercion was
saving us.  With the change from a raw query to a `typeorm` call, the
`numberToBigIntTransformer` specified in the `DexTrade` entity is now
doing the proper …

Adapt to Bloxy API change

---

packages/pipeline/src/data_sources/dex_prices/index.ts
packages/pipeline/src/scripts/pull_slippage.ts

We weren't getting all the data we wanted when using ethereum-dex-prices-service (EDPS). The problem was rate limiting (primarily from Radar Relay). This PR adds a bottleneck so we do 1 request per second.
```
yarn build
yarn test
node lib/src/scripts/pull_slippage.js
```
* Bug fix (non-breaking change which fixes an issue) -> we weren't getting all the data we wanted

Added bottleneck for EDPS to deal with rate-limiting

---

contracts/coordinator/contracts/src/MixinCoordinatorApprovalVerifier.sol
contracts/coordinator/contracts/src/MixinCoordinatorCore.sol
contracts/coordinator/contracts/src/interfaces/ICoordinatorApprovalVerifier.sol
contracts/coordinator/contracts/src/interfaces/ICoordinatorCore.sol
contracts/coordinator/contracts/src/libs/LibCoordinatorApproval.sol
contracts/coordinator/contracts/src/libs/LibZeroExTransaction.sol
contracts/coordinator/test/coordinator.ts
contracts/coordinator/test/libs.ts
contracts/coordinator/test/mixins.ts
contracts/coordinator/test/utils/approval_factory.ts
contracts/coordinator/test/utils/constants.ts
contracts/coordinator/test/utils/hash_utils.ts
contracts/coordinator/test/utils/types.ts
contracts/utils/CHANGELOG.json
contracts/utils/contracts/src/LibAddressArray.sol
packages/types/CHANGELOG.json
packages/types/src/index.ts
yarn.lock

- Adds a `txOrigin` field to the Coordinator approval message. The transaction must be executed by this address. This prevent's a user's transaction from being front-runned when it is intended to be used in conjunction with external smart contract calls.
- Optimizes transaction and approval hashing

Add tx.origin to TEC approvals

---

packages/connect/CHANGELOG.json
packages/connect/package.json
packages/order-watcher/CHANGELOG.json
packages/order-watcher/package.json
yarn.lock

The `order-watcher` package was sporadically failing tests for me on *clean* installs of the `development` branch. It turns out my version of `yarn` (`1.13.0 arch-linux@5.0.0`) kept pulling  `websocket@1.0.25`, which I discovered has a [masking number calculation bug](https://github.com/theturtle32/WebSocket-Node/blob/d941f975e8ef6b55eafc0ef45996f4198013832c/lib/WebSocketFrame.js#L256) that is fixed in subsequent patches.
I was able to get a corrected version installed and tests passing by upgrading `order-watcher`'s dependency from `websocket@^1.0.25` to `websocket@^1.0.26` AND removing the `websocket@1.0.25` entry in the root `yarn.lock` file (there are two others pointing to `1.0.26` already).
So far I've been the only one who could replicate this issue, probably because I'm on a …

Upgrade to websocket@^1.0.26 to fix broken tests

---

packages/order-watcher/CHANGELOG.json
packages/order-watcher/src/order_watcher/dependent_order_hashes_tracker.ts
packages/order-watcher/test/order_watcher_test.ts

When tracking ApprovalForAll on ERC721, an untracked address (no orders added as a maker) could cause a lookup on undefined.
Fixed #1550 

Fix error where object could be undefined given an approval event

---

packages/pipeline/src/scripts/pull_slippage.ts

The slippage job was failing but Airflow thought everything was working just fine.  This change signals the presence of `fetchAsync()` errors to the command-line interface, letting Airflow know what's happening.
Tested on QA.

Relay failures through command line interface

---

packages/pipeline/package.json
packages/pipeline/src/data_sources/nonfungible_dot_com/index.ts
packages/pipeline/src/scripts/partition_nonfungible_dot_com_dump.ts

Recall that nonfungible.com sent us an initial data dump so that we wouldn't have to pull *every*thing from the API.  And recall that we're storing that initial dump on S3.  Finally, recall that the cryptokitties data was particularly voluminous (~1GB), which doesn't easily transfer to and from S3.
These changes provide a CLI script to partition that data (or any such data from nonfungible.com) into a set of smaller files; and a scraping script that seamlessly recombines those partitions for loading into the database.
After building the `pipeline` component and setting `ZEROEX_DATA_PIPELINE_DB_URL` appropriately,
`node --max-old-space-size=8192 lib/src/scripts/pull_nonfungible_dot_com_trades.js`
-   [x] Prefix PR title with …

Enable cryptokitties data from nonfungible.com

---

packages/pipeline/src/data_sources/dex_prices/index.ts
packages/pipeline/src/scripts/pull_slippage.ts

We were previously using an endpoint for Ethereum DEX Prices Service which 0x did not control. This PR changes the endpoint to a service which is hosted in the 0x AWS environment.
In addition, we've increased timeout to 30 seconds + made the bottleneck 2x more aggressive (now max 30 requests per minute) so we don't hit rate-limits for the DEX APIs.
```
yarn build
yarn test
node lib/src/scripts/pull_slippage.js
```
* Fix (non-breaking change which fixes an issue)

Changed EDPS endpoint to a 0x AWS one

---

contracts/exchange/CHANGELOG.json
contracts/exchange/contracts/test/ReentrantERC20Token.sol
contracts/exchange/test/core.ts
contracts/exchange/test/match_orders.ts
contracts/exchange/test/wrapper.ts
contracts/utils/CHANGELOG.json
contracts/utils/contracts/src/ReentrancyGuard.sol

Replaces our current contract reentrancy guard with [a cheaper version](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/utils/ReentrancyGuard.sol) that only does one SSTORE per call.
Our current implementation would have played well with [EIP-1087](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1087.md)/[EIP-1283](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1283.md), but those have been nixed for Constantinople.
This new implementation "lazily," detects reentrancy, only reverting when the penultimate reentrant call returns. 
This meant reentrancy tests that relied on immediate detection of the reentrancy had to be reworked to perform valid (non-failing) calls, because a failing call would revert the second `reentrancyGuard` state change, so no …

Cheaper Mutex/Reentrancy Lock

---

packages/order-watcher/CHANGELOG.json
packages/order-watcher/package.json
packages/order-watcher/src/order_watcher/order_watcher.ts
packages/order-watcher/test/order_watcher_test.ts

Intermittent failures were reported by an order-watcher user (https://github.com/0xProject/0x-monorepo/issues/1710)
It turns out we have several async event callbacks that are modifying a shared piece of state, and that removals from this data structure can cause other callbacks to malfunction. 
This PR adds a semaphore around each of the async event callbacks so that the shared data structures they all use won't be modified during their execution. This allows them to assume that it won't be modified by another process. 

Fix race-condition in Order-watcher

---

.circleci/config.yml

Pin Launch Kit version in test-python CI task.
Fixes CI run plaguing everyone.
I republished the launch-kit-ci docker image earlier, updating the latest tag, to fix a bug experienced in the old version, and it broke the development branch test runs.  A code update, and an unpinning, will come from a WiP PR soon, but until it does we should pin the old test code to the Launch Kit version it was always running on (and passing).

Pin Launch Kit version in test-python CI task

---

.circleci/config.yml
contracts/utils/CHANGELOG.json

The `3.0` branch is contract-focused right now and will introduce breaking changes to a lot of ancillary packages (e.g., `@0x/instant`). The current circleci suite of tests all depend on `build:ci:no_website`, which is bound to fail in `3.0`, which means circleci would give us no meaningful signals on this branch. This updates the circleci config to only build and test contract-related packages.
Note: `test-contracts-geth` still fails, just like in development, but it's still included because it should start working once we update our geth fork.
This also fixes a minor merge artifact from the the `development` rebase.
-   [ ] Update …

[3.0] Only test contract-related packages in circleci.

---

.circleci/config.yml
python-packages/sra_client/README.md
python-packages/sra_client/setup.py
python-packages/sra_client/sra_client/__init__.py
python-packages/sra_client/test/relayer/docker-compose.yml
python-packages/sra_client/test/test_default_api.py

Context: Python SRA client tests run against an instance of Launch Kit, and for testing purposes we use Ganache as its backing node.
There was a race condition in having Circle CI start these services:  Sometimes, Launch Kit would start accepting connections, and tests would start running and trying to post orders, but Ganache was not yet up and listening, so the tests would time out and fail.
This PR adds changes to wait for Ganache to answer an API call before starting Launch Kit.
It also re-enables the Python SRA client tests, which were disabled due to them intermittently failing because of this race condition.
Finally, this PR also adds some conveniences for spinning up these services in a local development environment.
In an effort to ensure there's no longer an intermittent issue, …

Fix race condition in CI runs of Python SRA client tests

---

.circleci/config.yml

Geth tests are currently failing because our fork has become out of date. I'm working on addressing the issue (not easy because some of the features we need are broken in the latest `master` version of Geth). See https://github.com/ethereum/go-ethereum/issues/19346 for some additional background.
In the meantime, it's better to just disable the tests so everyone's CI will be all green and any other failures will be more obvious.

Disable Geth tests in CircleCI

---

packages/monorepo-scripts/README.md

Don't hate me, this is a very small change, but (1) it was bugging me to know that the command doesn't work and (2) I wanted to go through the contributor guide.
```bash
yarn scripts:deps_versions
```
The solution was to replace `scripts` with `script`:
```bash
yarn script:deps_versions
```

Fix yarn command in monorepo-scripts

---

packages/order-watcher/CHANGELOG.json
packages/order-watcher/src/order_watcher/order_watcher.ts

Fixes the second race-condition identified in https://github.com/0xProject/0x-monorepo/issues/1710.

Fix OrderWatcher race-condition bug

---

contracts/exchange-forwarder/CHANGELOG.json
contracts/exchange-forwarder/contracts/src/Forwarder.sol
contracts/exchange-forwarder/contracts/src/MixinAssets.sol
contracts/exchange-forwarder/contracts/src/MixinExchangeWrapper.sol
contracts/exchange-forwarder/contracts/src/MixinForwarderCore.sol
contracts/exchange-forwarder/contracts/src/MixinWeth.sol
contracts/exchange-forwarder/contracts/src/interfaces/IAssets.sol
contracts/exchange-forwarder/contracts/src/interfaces/IForwarder.sol
contracts/exchange-forwarder/contracts/src/interfaces/IForwarderCore.sol
contracts/exchange-forwarder/contracts/src/libs/LibConstants.sol
contracts/exchange-forwarder/contracts/src/libs/LibForwarderErrors.sol
contracts/exchange-forwarder/contracts/src/mixins/MAssets.sol
contracts/exchange-forwarder/contracts/src/mixins/MExchangeWrapper.sol
contracts/exchange-forwarder/contracts/src/mixins/MWeth.sol
contracts/exchange-forwarder/package.json

This backports the `0.5.5` update to the `exchange-forwarder` from the `3.0` branch onto `development`. This is just a compiler update. There are no meaningful changes to the functionality of the contracts. The PR for that branch is #1732.
`exchange-forwarder` relies on older, pinned dependencies. These pinned dependencies break the build when changes to pervasive packages like `base-contract` are introduced due to the way dependencies of dependencies are linked in the monorepo. Updating the smart contracts to soldity `0.5.5` removes the requirement for pinned dependencies.  
New feature (non-breaking change which adds functionality)
-   [ ] Add new …

Update contracts/exchange-forwarder to 0.5.5

---

contracts/asset-proxy/compiler.json
contracts/erc1155/compiler.json
contracts/erc721/compiler.json
contracts/exchange-libs/compiler.json
contracts/exchange/compiler.json
contracts/utils/compiler.json

The latest `solc` versions are `0.4.26` and `0.5.8` but there are no docker images for these versions yet. Builds are failing due to this. This PR disables dockerized `solc` until the images are published.

Disable `useDockerisedSolc` for all contracts `compiler.json`s until latest solc docker images are published

---

packages/utils/CHANGELOG.json
packages/utils/src/abi_encoder/evm_data_types/string.ts
packages/utils/test/abi_encoder/evm_data_types_test.ts

This fixes Issue #1723: the ABI Encoder was encoding/decoding strings as ASCII rather than UTF-8. This PR includes updated code and test cases for multibyte strings.
New tests were created to validate encoding and decoding of multibyte UTF-8 characters.

Support for ABI Encoding multibyte strings (Fixes Issue #1723)

---

packages/utils/CHANGELOG.json
packages/utils/src/abi_encoder/evm_data_types/dynamic_bytes.ts
packages/utils/src/abi_encoder/evm_data_types/static_bytes.ts
packages/utils/test/abi_encoder/evm_data_types_test.ts

Fixed typo in ABI Encoder error message

---

packages/order-watcher/CHANGELOG.json
packages/order-watcher/package.json
packages/order-watcher/src/order_watcher/collision_resistant_abi_decoder.ts
packages/order-watcher/src/order_watcher/order_watcher.ts
packages/order-watcher/test/order_watcher_test.ts

OrderWatcher seemed to intermittently handle (call the callback) deposit and withdraw events for WETH.
Before any orders were added the events were handled correctly, though after a WETH order was added it would cease to trigger a callback when a `Withdraw` or `Deposit` event occurred. Without handling these events a subscriber wouldn't be able to invalidate orders where the user withdrew all WETH funds. 
Added repro test. Can be tested with Launch-Kit, creating an order, withdrawing WETH, query orders endpoint

OrderWatcher Deposit/Withdraw events

---

.circleci/config.yml
packages/asset-buyer/CHANGELOG.json
packages/asset-buyer/src/order_providers/standard_relayer_api_order_provider.ts

Asset buyer checks for `remainingTakerAssetAmount` MetaData in the APIOrder from the SRA endpoint. This value is not explicitly part of the spec and as such it is not converted from string to BigNumber in `@0x/connect`. Using this value as a string results in errors when calculating the maker asset amount.

Fix bug where remainingTakerAssetAmount is not converted to BigNumber

---

packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/contract_wrappers/dutch_auction_wrapper.ts
packages/contract-wrappers/test/dutch_auction_wrapper_test.ts

Incorrect decode in DutchAuctionWrapper

---

packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/contract_wrappers/coordinator_wrapper.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/signature_utils.ts
packages/order-utils/test/signature_utils_test.ts

Lots of wallets/web3providers still don't support the new signing methods.
Add a new method `ecSignTransactionAsync` that will first attempt `eth_signTypedData ` and fall back to `eth_sign` if it's not available. 

fallback to eth_sign if eth_signTypedData fails

---

packages/monorepo-scripts/src/prepublish_checks.ts

Add a prepublish check that the user has write permissions for all packages about to be published to npmjs. Otherwise we risk ending up with only some packages published, which is very tedious to rollback. 
```
cd packages/monorepo-scripts
yarn build
node lib/prepublish_checks.js
```

add prepublish check for write permissions for npmjs packages

---

packages/subproviders/CHANGELOG.json
packages/subproviders/src/subproviders/trezor.ts

Cache the derived key info since it does not change and currently we request it from the Trezor device for each request.
Credit goes to @NoahZinsmeister who suggested this optimization: https://github.com/NoahZinsmeister/0x-monorepo/commit/d77ea80509a365acf941136c9ecc92be7bb2c7d1

subproviders: Fix Trezor subprovider inefficiency

---

contracts/coordinator/test/coordinator.ts
contracts/coordinator/test/libs.ts
contracts/coordinator/test/mixins.ts
contracts/exchange-libs/CHANGELOG.json
contracts/exchange-libs/contracts/src/LibZeroExTransaction.sol
contracts/exchange-libs/contracts/test/TestLibs.sol
contracts/exchange-libs/test/exchange_libs.ts
contracts/exchange/CHANGELOG.json
contracts/exchange/contracts/examples/ExchangeWrapper.sol
contracts/exchange/contracts/examples/Whitelist.sol
contracts/exchange/contracts/src/MixinTransactions.sol
contracts/exchange/contracts/src/mixins/MExchangeRichErrorTypes.sol
contracts/exchange/contracts/src/mixins/MTransactions.sol
contracts/exchange/test/transactions.ts
contracts/test-utils/src/transaction_factory.ts
packages/json-schemas/CHANGELOG.json
packages/json-schemas/schemas/zero_ex_transaction_schema.json
packages/order-utils/CHANGELOG.json
packages/order-utils/src/constants.ts
packages/order-utils/src/exchange_revert_errors.ts
packages/order-utils/test/eip712_utils_test.ts
packages/order-utils/test/transaction_hash_test.ts
packages/types/CHANGELOG.json
packages/types/src/index.ts

- Adds a `TransactionExecution` event that logs the `transactionHash`
- Adds an `expirationTimeSeconds` field to transactions
- Note that the `coordinator` package still builds and passes tests, but the approvals `expirationTimeSeconds` is now probably redundant. This will be changes in a later PR after the 3.0 contracts are complete.

Add transaction expirations and execution logs

---

contracts/test-utils/CHANGELOG.json
contracts/test-utils/src/assertions.ts

The function `expectTransactionFailedAsync(transactionReceipt, expectedRevertReason)` returns a false positive when the expected revert reason is a substring of the exception message. 
For example, if the expected revert reason is `INVALID_DATA` and the actual reason is `INVALID_DATA_OFFSET` then there will be a false positive.
To go one step further, the full exception message is `VM Exception while processing transaction: revert INVALID_DATA_OFFSET`. Any substring within that message will also return a false positive, for example, `processing trans`.

Fixes false positives in `expectTransactionFailedAsync`

---

contracts/asset-proxy/CHANGELOG.json
contracts/asset-proxy/contracts/src/ERC1155Proxy.sol
contracts/asset-proxy/package.json
contracts/asset-proxy/test/erc1155_proxy.ts
contracts/asset-proxy/test/utils/erc1155_proxy_wrapper.ts
contracts/erc1155/contracts/src/ERC1155Mintable.sol
packages/types/src/index.ts
yarn.lock

The original implementation of the ERC1155 Proxy copied asset data in bulk from calldata to memory. This introduced edge cases if dynamic values overlapped one another. This PR removes any overlap by individually copying each dynamic field (`ids`, `values`, and `data`). This will undo any optimization made by a client-side ABI encoder, but is both more secure and aligned with the implementations of other proxies.
This PR supersedes #1825 and #1826.

ERC1155 Proxy - Manually Copy Dynamic Fields from Calldata to Memory

---

packages/subproviders/CHANGELOG.json
packages/subproviders/src/subproviders/trezor.ts

Fix bug in Trezor implementation

---

CODEOWNERS

I already spoke to the Protocol Team about this on Slack. It doesn't make sense for me to remain a code owner for the contracts tests since it's not something I'm focusing on these days. Still happy to answer any questions that have to do with the work I did if they happen to come up.

Remove @albrow as code owner for contract tests

---

python-packages/order_utils/setup.py

Fixes broken builds due to new release of eth-abi.

order_utils.py: pin eth-abi version

---

.circleci/config.yml

On a recent CI run for the development branch, `test-contracts-ganache` took 9 minutes and 40 seconds to run ([see here](https://circleci.com/workflow-run/51c2cd00-8799-472f-9b94-d3ef63f1c412)).  The CI runs for this PR have clocked the same `test-contracts-ganache` task at 4:22 ([see here](https://circleci.com/workflow-run/f7235f03-f0e4-439c-88bf-e47165446139)) and 5:29 ([see here](https://circleci.com/workflow-run/3510d6e1-d1b0-4c7f-ae78-f1c5b9a35926)).
Ignoring cache load/save times, the actual contract test run times were also reduced by over 50%.  I semi-manually compiled a total of 8 minutes and 39 seconds from the CI view of the run times for each of the individual packages.  The cache-ignored contract test run time from the commits in this PR were 3:58 and 3:55.
Unfortunately, the …

This one weird trick cuts contract test runtime by over 50% in CI

---

packages/monorepo-scripts/src/prepublish_checks.ts

New packages do not exist in registry and therefore would be caught by `checkPublishRequiredSetupAsync` as packages that don't have write access. Added changes for code to not throw an error if packages are not published yet.

Fix case in pre-publish write access checks

---

packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/index.ts
packages/order-utils/src/order_validation_utils.ts

Validation methods currently in `@0x/contract-wrappers` ExchangeWrapper will not be automatically generated in `@0x/abi-gen-wrappers`. This PR copies the validation behaviour into `@0x/order-utils`. This is a temporary fix and we intend to remove the validation methods after V3 contracts are deployed and provide better revert reasons.
This also changes `ExchangeWrapper.validateMakerTransferThrowIfInvalidAsync ` to call the method defined in `@0x/order-utils`. I kept the existing unit test to ensure functionality did not change, but did not add a unit test to `order-utils` since it would be a more significant change and we have a plan to deprecate the validation methods. 
Resolves #1873 
Will need to update dependency in `@0x/contract-wrappers` after the `@0x/order-utils` changes are …

Copy validation methods from ExchangeWrapper to order-utils

---

packages/contract-artifacts/src/transform.ts
packages/contract-artifacts/test/contract_artifacts_test.ts

Resolves #1960
Upon looking closer, the scripts in `development` preserves the `compiler` field already. If we run `yarn artifacts_update` in `@0x/contract-artifacts`, we get the same artifacts currently published but **with the compiler field added**.  It was not included in the initial commit of `@0x/contract-artifacts`. 
This PR updates a test to ensure that publishing v3 artifacts will require the `compiler` field to pass CI. These are the fields that will be required:
Try running `yarn artifacts_update` in `packages/contract-artifacts` and see that the `compiler` field is preserved. 
@fabioberger can you confirm these are the fields we need?
-   [x] Add tests to cover changes as …

Add compiler settings to published artifacts

---

contracts/asset-proxy/contracts/src/ERC1155Proxy.sol
contracts/asset-proxy/contracts/src/StaticCallProxy.sol
contracts/asset-proxy/contracts/src/interfaces/IAssetProxy.sol
contracts/asset-proxy/test/erc1155_proxy.ts
contracts/asset-proxy/test/static_call_proxy.ts

- Implements the `ERC1155Proxy` and `StaticCallProxy` in Solidity
- Note: `StaticCallProxy` cannot inherit `IAssetProxy` because its `transferFrom` function is marked as `view`.
- Many revert conditions no longer contain reasons, as they are handled within Solidity
- There are no longer any checks for if the length of `assetData` is a multiple of 32. However, any lengths less than required should fail (TODO: add tests for this)
- Found some pretty bizarre behavior is Solidity's `abi.decode`. When multiple offsets point to the same location in calldata (i.e if `values` == `ids`) then the decoded output is also copied to the same location in memory. This means we cannot modify `values` directly, or we may end up modifying `ids` or `data` as well.
- Thoughts on using `slice` vs …

Implement ERC1155Proxy and StaticCallProxy in Solidity

---

packages/asset-swapper/src/constants.ts
packages/asset-swapper/src/quote_consumers/exchange_swap_quote_consumer.ts
packages/asset-swapper/src/utils/assert.ts
packages/asset-swapper/src/utils/swap_quote_consumer_utils.ts

Per spec: 
> Note that `marketSellOrdersNoThrow` assumes that the `takerAssetData` is equal for each order. For any order passed in after the first, the `takerAssetData` byte array will be ignored (allowing null byte arrays to be passed in). If an order was intended to use a different `takerAssetData` field, the fill will fail at signature validation.
Added optimization to the output provided by `ExchangeSwapQuoteConsumer`.

Added optimization utils for asset-swapper exchange consumer

---

package.json
packages/monorepo-scripts/src/publish.ts
yarn.lock

Our publishing script currently calls `lerna publish` via `exec`, not allowing for any interactivity with the command. Now that we want to enable 2FA however, we need to be able to support OTPs during the commands execution.
This PR switches our use of `exec` for `spawn`, allowing us to intercept the OTP prompt and bubble it up to the publisher running our script. 

publishing: prompt user for OTP

---

packages/abi-gen/package.json

Workaround for #2000 so that developers can just run `abi-gen$ yarn test` on their local (OSX) machine and not have to say "wtf?"
Watch CI to verify that it still runs fine on Linux.  To verify for Mac, check out the branch, build and test abi-gen, and look for the "HACK! ..." message in the output.

abi-gen: skip run_mocha on OSX

---

packages/website/package.json
yarn.lock

Fixes: #1977
Yarn currently has a caching issue with Github deps specified with the short-hand notation, causing the version installed to be in-determinant. This PR makes us always use the explicit HTTP url to the repository and a specific commit hash.
Source: https://github.com/yarnpkg/yarn/issues/4722

Fix react-highlight dep issue

---

.circleci/config.yml
contracts/asset-proxy/.solhintignore
contracts/asset-proxy/test/erc1155_proxy.ts

Also, tests were broken.
- Removed `test-python` (which we don't run) as a workflow dependency in the circleci config. Looks like the rebase snuck this in.
- Disabled `abi-gen` tests in circleci. The new tests use reference contracts from the `development` branch, which obviously break on `3.0`. We could just update them, but it might get annoying having to keep doing that.
- Add a `.solhintignore` file to `/contracts/asset-proxy` to ignore `ERC1155Proxy.sol`.
- Solhint can't parse this file at all because of the `abi.decode()` in it. I tried upgrading solhint to latest and still no dice. Time to switch?
- Fix a broken test in `/contracts/asset-proxy/test/erc1155_proxy.ts`. Not sure how this one got in.
-   [ ] Add tests to cover changes …

Fix circleci workflow failing on 3.0 branch

---

contracts/exchange/CHANGELOG.json
contracts/exchange/contracts/src/MixinAssetProxyDispatcher.sol
contracts/exchange/contracts/src/interfaces/IAssetProxy.sol

This PR rewrites `_dispatchTransferFrom` in pure Solidity.
`yarn build:contracts && yarn test:contracts && yarn lint:contracts`
* Refactor

Rewrite _dispatchTransferFrom with a Solidity implementation

---

contracts/exchange/contracts/src/MixinExchangeCore.sol
contracts/exchange/contracts/src/MixinWrapperFunctions.sol
contracts/exchange/test/core.ts
contracts/exchange/test/utils/exchange_wrapper.ts
contracts/exchange/test/wrapper.ts

In the interest of simplifying the Exchange contract interface, this PR uses less strict validation in `cancelOrder` and removes `cancelOrderNoThrow`. `cancelOrder` now returns early if the order is not `FILLABLE`, rather than reverting.

Use less strict validation in `cancelOrder`, remove `cancelOrderNoThrow`

---

packages/sol-compiler/.npmignore

3.1.11 was published with 
https://unpkg.com/browse/@0x/sol-compiler@3.1.11/lib/solc_bin/
Prevent multiple versions of sol compiler being published in the package. These are downloaded on demand.

Remove solc-bin from npm publish

---

contracts/exchange/test/assertion_wrappers/fill_order_wrapper.ts
contracts/exchange/test/balance_stores/balance_store.ts
contracts/exchange/test/balance_stores/blockchain_balance_store.ts
contracts/exchange/test/balance_stores/local_balance_store.ts
contracts/exchange/test/core.ts
contracts/test-utils/src/index.ts
contracts/test-utils/src/types.ts

This is an assertion wrapper for `exchange.fillOrder`. It encapsulates all pre- and post- assertions we want to make when calling `fillOrder`. This includes validating: order state, fill results, balance changes, and events.
This PR includes:
1. Assertion wrapper for `exchange.fillOrder`. This may be used as a template for future assertion wrappers.
3. A set of `Balance Store` classes which can be recycled by other assertion wrappers / test utilities to track/compare/analyze balances throughout a test.
2. A reduction in size by 35% of `test/core.ts`
Notes:
Much of this code was reworked from the contract wrappers and the match order tester. There still exists a lot of redundant test code in those classes, and elsewhere. As we migrate to this pattern we will eventually be able to easily …

Fill Order Assertion Wrapper

---

packages/contract-artifacts/src/copy.ts

We stopped checking contract artifacts for python packages into github. This PR removes the python_packages path when copying artifacts, which was causing it to fail before.
Fixes #2063
Run `yarn artifacts_update` and verify it works.

Don't use python path when copying contract artifacts

---

python-packages/sra_client/tox.ini

We don't support 2.7 for any of our other packages, so no need to do it for this one.  And, I was running `tox` locally, and I don't even have Python 2.7 installed, so this was failing for me, so I thought I'd just remove it.

sra_client.py: don't test against Python 2.7

---

packages/base-contract/CHANGELOG.json
packages/base-contract/package.json
packages/base-contract/src/subscription_manager.ts
yarn.lock

Updates ethereumjs-blockstream.  `6.0.0` will be removed after we update coordinator-server deps in https://github.com/0xProject/0x-coordinator-server/issues/14
Relates to #1989

update ethereumjs-blockstream 6.0.0 -> ^7.0.0

---

contracts/exchange-libs/contracts/src/LibExchangeRichErrors.sol
contracts/exchange/contracts/src/MixinExchangeCore.sol
contracts/exchange/contracts/src/MixinMatchOrders.sol
contracts/exchange/contracts/src/MixinProtocolFees.sol
contracts/exchange/contracts/src/MixinSignatureValidator.sol
contracts/exchange/contracts/src/libs/LibExchangeRichErrorDecoder.sol
contracts/exchange/contracts/test/TestExchangeInternals.sol
contracts/exchange/test/core.ts
contracts/exchange/test/isolated_fill_order.ts
contracts/exchange/test/lib_exchange_rich_error_decoder.ts
contracts/exchange/test/transactions.ts
contracts/exchange/test/utils/fill_order_combinatorial_utils.ts
packages/order-utils/src/exchange_revert_errors.ts

Wrap `payProtocolFee` with rich revert + reduce codesize

---

contracts/exchange-libs/contracts/src/LibExchangeRichErrors.sol
contracts/exchange/contracts/src/MixinExchangeCore.sol
contracts/exchange/contracts/src/MixinMatchOrders.sol
contracts/exchange/contracts/src/MixinSignatureValidator.sol
contracts/exchange/contracts/src/MixinTransactions.sol
contracts/exchange/contracts/src/libs/LibExchangeRichErrorDecoder.sol
contracts/exchange/contracts/test/IsolatedExchange.sol
contracts/exchange/contracts/test/ReentrancyTester.sol
contracts/exchange/contracts/test/TestProtocolFeesReceiver.sol
contracts/exchange/test/core.ts
contracts/exchange/test/isolated_fill_order.ts
contracts/exchange/test/lib_exchange_rich_error_decoder.ts
contracts/exchange/test/match_orders.ts
contracts/exchange/test/transactions.ts
contracts/exchange/test/transactions_unit_tests.ts
contracts/utils/contracts/test/TestOwnable.sol
packages/order-utils/src/exchange_revert_errors.ts

- `batchMatchOrders` makes many `getOrderInfo` calls when all we really want is the `orderTakerAssetFilledAmount`. By creating a `_getOrderHashAndFilledAmount` function, we drastically reduce the amount of sloads used (-2 per `getOrderInfo`, plus we remove many useless checks). This change adds about 30 gas to a `fillOrder` call, but saves ~3500 gas for a `batchMatchOrders` call with 1x `leftOrder` and 2x `rightOrder`. The savings will go up by a lot post Istanbul.
- This PR also clears most compiler warnings throughout the packages.
- The `TransactionSignatureError` is consolidated with the regular `SignatureError` using a new error code.
-   [ ] Add …

Optimize batchMatchOrders, consolidate TransactionSignatureError rich revert

---

contracts/staking/contracts/src/fees/MixinExchangeFees.sol
contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/src/interfaces/IStakingPoolRewardVault.sol
contracts/staking/contracts/src/interfaces/IStructs.sol
contracts/staking/contracts/src/libs/LibStakingRichErrors.sol
contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewardVault.sol
contracts/staking/contracts/src/vaults/StakingPoolRewardVault.sol
contracts/staking/contracts/test/TestStorageLayout.sol
contracts/staking/test/actors/pool_operator_actor.ts
contracts/staking/test/pools_test.ts
contracts/staking/test/vaults_test.ts
packages/order-utils/src/staking_revert_errors.ts

Moves the pool operator getter and related modifiers from `MixinStakingPool` to `MixinStakingPoolRewardVault`, moving the state from `MixinStorage` to `StakingPoolRewardVault`. 
This PR also adds the functionality for operators to decrease their share of the rewards in the pool. 
As a byproduct of these changes, `IStructs.Pool` is ded but the `Balance` struct is renamed to `Pool` because it now has a few fields unrelated to balances.
Probably want to add some integration tests involving `decreaseStakingPoolOperatorShare` in a future PR, for now I think unit tests will suffice
* Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Update documentation as …

Move pool operator logic to vault and allow operators to decrease operatorShare

---

packages/contract-wrappers/CHANGELOG.json
packages/contract-wrappers/src/contract_wrappers.ts

We somehow missed out adding DevUtilsContract to ContractWrappers. This PR instantiates DevUtilsContract.
This enables us to replace uses of `order-utils` with `DevUtilsContract`.

Add DevUtils to @0x/contract-wrappers

---

contracts/extensions/contracts/src/OrderMatcher/interfaces/IOrderMatcher.sol

Fixing error in the import path.
Also, when I compile extensions/ dir I did the following changes:
```diff
--- a/contracts/extensions/contracts/src/OrderMatcher/interfaces/IOrderMatcher.sol
+++ b/contracts/extensions/contracts/src/OrderMatcher/interfaces/IOrderMatcher.sol
@@ -17,8 +17,9 @@
*/
pragma solidity ^0.5.5;
+pragma experimental ABIEncoderV2;
-import "@0x/contract-utils/contracts/src/interfaces/IOwnable.sol";
+import "@0x/contracts-utils/contracts/src/interfaces/IOwnable.sol";
import "./IMatchOrders.sol";
import "./IAssets.sol";
```
Without `ABIEncoderV2` it doesn't compile too, should it be added here?
I add simple truffle-config and run truffle compile.
-   [ ] Add tests to …

Fix typo at contract import

---

contracts/staking/contracts/src/interfaces/IStakingPoolRewardVault.sol
contracts/staking/contracts/src/libs/LibStakingRichErrors.sol
contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/vaults/StakingPoolRewardVault.sol
contracts/staking/test/stake_test.ts
contracts/staking/test/vaults_test.ts
packages/order-utils/src/staking_revert_errors.ts

Check whether a pool with the given `poolId` exists at the beginning of `_delegateStake` and `_undelegateStake`, revert if not. Also removes the `bool initialized` field from `struct Pool` because we can just check whether the operator address is nil.
Tests added to `stake_test.ts`

Ensure pool exists before (un)delegating

---

contracts/dev-utils/compiler.json
contracts/dev-utils/contracts/src/OrderTransferSimulationUtils.sol
contracts/dev-utils/package.json
contracts/dev-utils/test/order_validation_utils.ts
contracts/exchange/contracts/src/interfaces/IProtocolFees.sol
packages/contract-artifacts/src/copy.ts

This contract needs to be upgraded to work with v3 and deployed for use by Mesh.
Run tests for `0x-monorepo/contracts/dev-utils` (or just watch CI).
-   [x] Make DevUtils deployable.  The `DevUtils` contract can’t currently be deployed because the contract size is too large. We can experiment with turning off compiler optimizations, which might lower the codesize. Otherwise we’ll have to break up the deployments into multiple contracts (@abandeali1 thinks the `OrderValidationUtils` and `OrderTransferSimulationUtils` contracts are most important).
-   [x] More tests for `OrderTransferSimulationUtils` (there was previously a fairly large bug that wasn’t caught in tests, which you can see by looking at the diff)

DevUtils.sol: Upgrade for v3

---

contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/stake/MixinStakeBalances.sol
contracts/staking/test/actors/staker_actor.ts
contracts/staking/test/utils/types.ts

Adds a state variable to keep track of total stake in the system (by status), which gets updated every time `stake`, `unstake`, or `moveStake` is called. Intended for use in future features. 
Also makes some functions in `staker_actor` private
Updated `staker_actor.ts` to check global stake

Maintain global stake

---

packages/asset-swapper/webpack.config.js
packages/migrations/package.json
packages/migrations/src/migration.ts
packages/orderbook/package.json

* Fixed the webpack publish for asset swapper to be in line with 0x.js
* Modified the migration snapshot name to not clobber v2 until we're ready to overwrite
* Added filler transactions to keep contract addresses consistent whilst asset proxy is disabled
* Non-private package publish for orderbook
```
docker run -it --rm -p 8545:8545 -e SNAPSHOT_NAME=0x_ganache_snapshot-v3-beta -e VERSION=4.3.2 0xorg/ganache-cli:latest
```
http://ganache-snapshots.0x.org.s3.amazonaws.com/0x_ganache_snapshot-v3-beta-4.3.2.zip

Quick fixes

---

contracts/staking/CHANGELOG.json
contracts/staking/contracts/src/Staking.sol
contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol
contracts/staking/contracts/test/TestCumulativeRewardTracking.sol
contracts/staking/test/cumulative_reward_tracking_test.ts
contracts/staking/test/utils/cumulative_reward_tracking_simulation.ts

This removes reference counting for cumulative rewards.
Reference counting allowed us to clear old state that was no longer needed by the staking contract. After reviewing the tradeoffs with the protocologists, it was decided that we would remove this feature in favor of simplicity.
See #2154 for full context.

Remove reference counting for cumulative rewards

---

contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/stake/MixinStakeStorage.sol
contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol
contracts/staking/contracts/test/TestCumulativeRewardTracking.sol
contracts/staking/contracts/test/TestDelegatorRewards.sol
contracts/staking/contracts/test/TestStakingNoWETH.sol
contracts/staking/test/cumulative_reward_tracking_test.ts
contracts/staking/test/utils/cumulative_reward_tracking_simulation.ts

This PR mostly renames variables and flattens some of the logic in `MixinStakingPoolRewards` to improve readability. In the process, I came across a bug in `_trySetCumulativeReward` where it would _always_ call `_forceSetCumulativeReward`. It would return early only iff `epoch < currentEpoch && ...`. The value passed in as `epoch` was always `_loadSyncedBalance(...).currentEpoch`, which is necessarily >= `currentEpoch`.
When reviewing this PR, please note the changes in the test cases and double check that this in intended behavior.

Improve readability, fix `_trySetCumulativeReward` logic

---

contracts/staking/contracts/src/fees/MixinExchangeFees.sol
contracts/staking/contracts/src/immutable/MixinDeploymentConstants.sol
contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/src/interfaces/IStorage.sol
contracts/staking/contracts/test/TestCumulativeRewardTracking.sol
contracts/staking/contracts/test/TestProtocolFees.sol
contracts/staking/contracts/test/TestStaking.sol
contracts/staking/contracts/test/TestStorageLayoutAndConstants.sol
contracts/staking/test/unit_tests/protocol_fees_test.ts
contracts/staking/test/utils/api_wrapper.ts

There was some debate around if the staking contracts should use the existing `ERC20Proxy` or not for paying WETH denominated protocol fees. It's a close call, but I think requiring a separate allowance leads to greater security. It also isn't much of an inconvenience for end users, as I expect the majority of protocol fees will be paid in ETH and will therefore not require an allowance.
If the `ERC20Proxy` is not used, it doesn't really make sense to have a separate proxy at all - users can simply approve the staking proxy to spend their WETH directly. This PR removes the WETH AssetProxy from the staking codebase completely.
-   [ ] Add new entries to …

Remove wethAssetProxy and wethAssetData from staking contracts

---

contracts/staking/contracts/src/StakingProxy.sol
contracts/staking/contracts/src/ZrxVault.sol
contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/test/TestDelegatorRewards.sol
contracts/staking/contracts/test/TestFinalizer.sol
contracts/staking/contracts/test/TestProtocolFees.sol
contracts/staking/test/migration_test.ts
contracts/staking/test/unit_tests/exchange_test.ts
contracts/staking/test/unit_tests/params_test.ts
contracts/staking/test/unit_tests/zrx_vault_test.ts
contracts/staking/test/utils/api_wrapper.ts

The actual address used to deploy these contracts should not be authorized. The contracts are typically deployed, configured, and then their ownership is transferred to the `AssetProxyOwner`. This PR removes the owner as an authorized address in the `StakingProxy` and the `ZrxVault`.

Do not authorize owner by default

---

package.json
packages/instant/package.json
packages/orderbook/src/order_provider/mesh_order_provider.ts

Circular dependencies means we are a bit stuck. Set it to `any` until mesh-rpc-client is updated.

HACK: Types as any until Mesh RPC client is published

---

contracts/exchange/contracts/src/MixinExchangeCore.sol
contracts/exchange/contracts/src/MixinMatchOrders.sol
contracts/exchange/contracts/src/MixinSignatureValidator.sol
contracts/exchange/contracts/src/MixinWrapperFunctions.sol
contracts/utils/contracts/src/Refundable.sol

Addresses https://github.com/0xProject/protocol-development-sprint/issues/10
Introduces non-reentrant version of `refundFinalBalance`, to avoid cognitive overhead of always keeping the `nonReentrant` modifier before `refundFinalBalance` in functions that use both

refundFinalBalanceNoReentry

---

contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol

Fixes the shadowed `currentEpoch` variable in `_computeUnfinalizedDelegatorReward()` by renaming it to `currentEpoch_`. Also switched the function mutability from `view` to `pure` because I was there anyway (sorrynotsorry).
Fixes 0xProject/protocol-development-sprint#6

fix `_computeUnfinalizedDelegatorReward()` shadowed variable and function mutability

---

contracts/exchange/contracts/src/MixinExchangeCore.sol
contracts/exchange/contracts/src/MixinSignatureValidator.sol
contracts/exchange/test/core.ts
contracts/exchange/test/isolated_fill_order.ts
yarn.lock

Always validate order signatures

---

contracts/staking/contracts/src/ZrxVault.sol
contracts/staking/contracts/src/immutable/MixinStorage.sol
contracts/staking/contracts/src/interfaces/IStaking.sol
contracts/staking/contracts/src/interfaces/IStructs.sol
contracts/staking/contracts/src/interfaces/IZrxVault.sol
contracts/staking/contracts/src/libs/LibStakingRichErrors.sol
contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/stake/MixinStakeBalances.sol
contracts/staking/contracts/src/stake/MixinStakeStorage.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
contracts/staking/contracts/test/TestDelegatorRewards.sol
contracts/staking/contracts/test/TestProtocolFees.sol
contracts/staking/contracts/test/TestStorageLayoutAndConstants.sol
contracts/staking/package.json
contracts/staking/test/actors/staker_actor.ts
contracts/staking/test/catastrophe_test.ts
contracts/staking/test/codesize_test.ts
contracts/staking/test/rewards_test.ts
contracts/staking/test/stake_test.ts
contracts/staking/test/unit_tests/mixin_stake_storage_test.ts
contracts/staking/test/utils/cumulative_reward_tracking_simulation.ts
contracts/staking/test/utils/types.ts
packages/order-utils/src/staking_revert_errors.ts

This PR makes the following changes in order to simplify some of the accounting in the staking contracts:
- Withdrawable stake is now simply the stake that is inactive in both the current and next epoch. This considerably simplifies the logic for `unstake`. This does, however, actually change the functionality of withdrawals. Stakers can now withdraw immediately at the next epoch after moving their stake to `INACTIVE`. They will still forfeit their rewards for the epoch in which they withdraw, though. Open to hearing people's thoughts on this.
- Completely removes the `ACTIVE` stake status. Being able to think about the state in 1 less dimension removes a lot of complexity IMO. Newly staked ZRX is now `INACTIVE`. The only functional change here is that a user can deposit and withdraw in …

Simplify staking state

---

contracts/staking/CHANGELOG.json
contracts/staking/contracts/src/libs/LibFixedMath.sol
contracts/staking/contracts/src/libs/LibFixedMathRichErrors.sol
contracts/staking/test/unit_tests/lib_fixed_math_test.ts
packages/utils/CHANGELOG.json
packages/utils/src/fixed_math_revert_errors.ts

This PR addresses arithmetic overflows in the staking contracts' `LibFixedMath` library.
Checks were added to:
- `sub()`
- `_add()`
- `_mul()`
- `_div()`
The preliminary audit did uncover the majority of these overflows but the limits in the report were wrong, and I found some other edge cases. So the checks differ from those suggested the report.
I also removed the fixed math `BinOpErrorCodes.SubtractionUnderflow` error code, since I didn't feel the distinction is all that useful in practice since it's just implemented as a negated addition.
Fixes 0xProject/protocol-development-sprint#4

Fix LibFixedMath arithmetic overflows

---

contracts/integrations/package.json
contracts/staking/contracts/src/ZrxVault.sol
contracts/staking/contracts/src/interfaces/IStructs.sol
contracts/staking/contracts/src/interfaces/IZrxVault.sol
contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol
contracts/staking/contracts/src/sys/MixinAbstract.sol
contracts/staking/contracts/src/sys/MixinFinalizer.sol
contracts/staking/contracts/test/TestDelegatorRewards.sol
contracts/staking/test/cumulative_reward_tracking_test.ts

Some pretty small changes in this PR that primarily aim to improve readability.
- Removes an unnecessary SLOAD + assert. It is pretty easy to see that this assert will never be hit.
- Always set cumulative rewards when `_withdrawAndSyncDelegatorRewards` is called. The removed check is just an extra cost post hard-fork. We also didn't make this check in other places.
- Removes `creditRewardsToPool` and inlines the logic into `finalizePool`.
- Get's rid of return values in `finalizePool`. They were never being used, and I'd be pretty surprised if they do end up getting used in other contracts.
- Removes `initialized` parameter from the `Pool` struct (unused).
-   [ ] Update documentation as …

Staking readability improvements

---

contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol
contracts/staking/contracts/test/TestCumulativeRewardTracking.sol
contracts/staking/contracts/test/TestDelegatorRewards.sol
contracts/staking/test/cumulative_reward_tracking_test.ts
contracts/staking/test/utils/cumulative_reward_tracking_simulation.ts

This PR refactors `MixinCumulativeRewards` and `MixinStakingPoolRewards` to better encapsulate the cumulative reward logic within `MixinCumulativeRewards`. 
This is accomplished by exposing two higher level functions:
- `_updateCumulativeReward()`
- `_addCumulativeReward()`
We also hide some low level functions:
- `_forceSetCumulativeRewards()`
- `_getCumulativeRewardAtEpoch()`
As a result, `MixinStakingPoolRewards` no longer has to deal with cumulative rewards directly.
We now just fall back to an empty CR entry (`0/1`) in `_getCumulativeRewardAtEpoch()`, which means `MixinStakingPool` doesn't have to worry about cumulative rewards. I know, this removes some guard rails, but I think the simplification is worth it. 
Because `_withdrawAndSyncDelegatorRewards()` can potentially create CR …

Staking: Refactor and slightly simplify rewards tracking

---

contracts/staking/CHANGELOG.json
contracts/staking/contracts/src/fees/MixinExchangeFees.sol
contracts/staking/contracts/src/libs/LibStakingRichErrors.sol
contracts/staking/test/unit_tests/protocol_fees_test.ts
packages/order-utils/CHANGELOG.json
packages/order-utils/src/staking_revert_errors.ts

It is the responsibility of the exchange - not the staking contract - to determine if the protocol fee paid is correct.

Remove assertion that protocol fee != zero

---

contracts/staking/contracts/src/stake/MixinStake.sol
contracts/staking/test/unit_tests/stake_test.ts

This forces a no-op in the following scenarios:
i. moving zero stake, or
ii. moving from undelegated to undelegated.
This fixes C13.

Force no-op when moving stake, in some scenarios

---

contracts/asset-proxy/contracts/src/ERC20BridgeProxy.sol
contracts/asset-proxy/contracts/src/bridges/Eth2DaiBridge.sol
contracts/asset-proxy/contracts/src/bridges/UniswapBridge.sol
contracts/asset-proxy/contracts/src/interfaces/IERC20Bridge.sol
contracts/asset-proxy/contracts/test/TestERC20Bridge.sol
contracts/asset-proxy/test/eth2dai_bridge.ts
contracts/asset-proxy/test/uniswap_bridge.ts

Affects 0xProject/ZEIPs/issues/47

Rename `withdrawTo` to `bridgeTransferFrom`

---

contracts/multisig/contracts/src/MultiSigWalletWithTimeLock.sol
contracts/multisig/test/multi_sig_with_time_lock.ts

Allows transactions in the ZeroExGovernor to be over confirmed. This means that as long as 2/3 of the signers are honest, a single signer cannot block a transaction.

Allow transactions to be over confirmed without resetting the confirmation time

---

contracts/staking/CHANGELOG.json
contracts/staking/contracts/src/libs/LibFixedMath.sol
contracts/staking/test/unit_tests/lib_fixed_math_test.ts

Fixes an overflow scenario when doing `LibFixedMath._mul(-1, MIN_FIXED_VALUE)`.

Fix `LibFixedMath._mul()` overflow

---

.circleci/config.yml
python-packages/sra_client/src/zero_ex/sra_client/__init__.py
python-packages/sra_client/test/relayer/docker-compose.yml

For CircleCI job `test-python`, change docker config for `launch-kit-backend` to set an environment variable for the chain ID, not for the network ID.  This was failing on all branches after a recent update to the `0xorg/launch-kit-backend:v3` tag.

CI/test-python: give launch-kit-backend CHAIN_ID, not NETWORK_ID

---

packages/subproviders/CHANGELOG.json
packages/subproviders/package.json
packages/subproviders/src/index.ts
packages/subproviders/src/subproviders/debug_subprovider.ts
packages/subproviders/test/unit/debug_subprovider_test.ts
packages/subproviders/test/utils/fixture_data.ts
yarn.lock

Adds a DebugSubprovider.  Useful for investigating RPC calls.
Inspired from the situation in which transactions were not getting generated correctly, and it took a long time to recognize that a subprovider was generating incorrect nonces.
Add a DebugSubprovider before the final subprovider (i.e. RPCSubprovider) and watch statements be logged to `console.debug`
New feature

Add DebugSubprovider

---

contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
contracts/staking/test/pools_test.ts
contracts/staking/test/unit_tests/staking_pool_test.ts
packages/migrations/src/test_contract_configs.ts

An operator currently cannot open up a pool with a 100% `operatorShare` because of an off by 1 error. Pretty simple fix.

Fix 100% operator share

---

packages/utils/CHANGELOG.json
packages/utils/src/revert_error.ts
packages/utils/test/revert_error_test.ts

Parity nodes have a different response than Ganache/Geth nodes in the event of an `eth_call` error. This lead to the errors not being decoded and just throwing ABI encoded strings.
Parity
```
Error Thrown
{ code: -32015,
data:
'Reverted 0xa6bcde47000000000000000000000000000000000000000000000000000000005dcf4184000000000000000000000000000000000000000000000000000000005dce5fec',
message: 'VM execution error.' }
```
Geth
```
RESPONSE
"0xa6bcde47000000000000000000000000000000000000000000000000000000005dcf798c000000000000000000000000000000000000000000000000000000005dce5fe9"
{ BlockTimestampTooLowError: BlockTimestampTooLowError()
...
abi:
{ type: 'error',
name: 'BlockTimestampTooLowError',
arguments: [ [Object], [Object] ] },
_raw: undefined }
```

RevertError: Decode Parity revert errors

---

packages/0x.js/CHANGELOG.json
packages/asset-swapper/CHANGELOG.json
packages/ethereum-types/package.json
packages/types/package.json
packages/typescript-typings/package.json
packages/utils/CHANGELOG.json
packages/utils/package.json

Supercedes: https://github.com/0xProject/0x-monorepo/pull/2331
Updates our tooling's BigNumber dep to ~9.0.0.

Update BigNumber dep to ~9.0.0

---

packages/utils/src/provider_utils.ts

Yesterday, Metamask (as of 7.7.0 https://github.com/MetaMask/metamask-extension/releases/tag/v7.7.0) changed the internals of their provider (using prototypes) [see 
[https://github.com/MetaMask/metamask-inpage-provider/blob/master/index.js#L285-L301](https://github.com/MetaMask/metamask-inpage-provider/blob/master/index.js#L285-L301) ] and the way we pull off the methods of the provider object when standardizing the providing make JavaScript lose the `this` context without binding, which breaks our implementation. This PR fixes that.

Fix unbound method in provider standardizer

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/protocol_fee_utils.ts
packages/orderbook/CHANGELOG.json
packages/orderbook/src/order_provider/base_order_provider.ts
packages/orderbook/src/order_provider/custom_order_provider.ts
packages/orderbook/src/order_provider/mesh_order_provider.ts
packages/orderbook/src/order_provider/sra_polling_order_provider.ts
packages/orderbook/src/order_provider/sra_websocket_order_provider.ts
packages/orderbook/src/order_store.ts
packages/orderbook/src/orderbook.ts
packages/orderbook/test/order_provider/mesh_order_provider.test.ts
packages/orderbook/test/order_provider/sra_polling_order_provider.test.ts
packages/orderbook/test/order_provider/sra_websocket_order_provider.test.ts

We want to adapt the orderstore to fetch from a local database rather than in-memory for usage with 0x API and AssetSwapper. 0xProject/0x-api#33
As such this change moves a number of `OrderStore` functions to be async. This is not a directly used class and all of `OrderBook` functions are already `async`. As are `OrderSet` since it calculates `orderHash` async.
Also fixes an issue in `asset-swapper` where the gas price estimate from ethgastation is in gwei. All calculations based off of that result in gwei as well. This is results in an underfunded `protocolFee` when a real gas price is used (8 gwei in wei rather than 8 wei).
TODO

orderbook: Make OrderStore async for use in db adapter

---

contracts/integrations/test/framework/actors/maker.ts
contracts/integrations/test/framework/actors/pool_operator.ts
contracts/integrations/test/framework/actors/staker.ts
contracts/integrations/test/framework/actors/taker.ts
contracts/integrations/test/framework/actors/tslint.json
contracts/integrations/test/framework/assertions/decreaseStakingPoolOperatorShare.ts
contracts/integrations/test/framework/utils/pseudorandom.ts
contracts/integrations/test/fuzz_tests/pool_management_test.ts
contracts/integrations/test/fuzz_tests/pool_membership_test.ts
contracts/integrations/test/fuzz_tests/stake_management_test.ts
contracts/integrations/test/fuzz_tests/staking_rewards_test.ts
contracts/integrations/test/fuzz_tests/tslint.json
contracts/staking/src/types.ts

Adds some functionality to `Pseudorandom` for more sophisticated input generation. In particular, you can now pass in an array of weights alongside the array of inputs to `Pseudorandom.sample` and `sampleSize`. For `Pseudorandom.integer`, you can pass in a custom probability distribution alongside the min and max values. I implemented the [Kumaraswamy distribution](https://www.johndcook.com/blog/2009/11/24/kumaraswamy-distribution/), a beta-like distribution which allows to weigh the extreme ends of an input distribution more heavily: 
I want to get some feedback on what sort of weights/distributions we want. I've chosen some values that are intended to be either more realistic or hit more corner cases than uniformly random samples, but they're still p arbitrary. 
-   [ ] Prefix PR title …

`@0x/contracts-integrations`: Better input generation for fuzzing

---

.circleci/config.yml

`test-python` is currently failing in development.
This is the relevant error: `{"code":100,"reason":"Validation Failed","validationErrors":[{"field":"signedOrder","code":1007,"reason":"OrderUnfunded: maker has insufficient balance or allowance for this order to be filled"}`.  This is in response to the Python SRA client doctest trying to post an order to `launch-kit-backend`+`mesh`+`ganache`.
The last time `test-python` ran successfully on `development` was at 2:52 PM PST yesterday.  The first time it failed on `development` was at 5:40 PM PST yesterday.
My first idea (and @jacob's too) was that something must have changed in the ganache snapshot, but that hasn't changed since Dec 3.
My next guess was that something changed in Mesh order validation (this runs unpinned, against the …

sra_client.py: Tweak Mesh block polling interval used in tests

---

contracts/asset-proxy/CHANGELOG.json
contracts/asset-proxy/contracts/src/bridges/KyberBridge.sol
contracts/asset-proxy/contracts/src/bridges/UniswapBridge.sol
contracts/asset-proxy/contracts/test/TestKyberBridge.sol
contracts/asset-proxy/test/kyber_bridge.ts
contracts/asset-proxy/test/uniswap_bridge.ts
packages/contract-addresses/CHANGELOG.json
packages/contract-addresses/addresses.json

- Uniswap `tokenToTokenTransferInput()` was being called wrongly (minimum eth buy must be at least `1`).
- Kyber's `minConversionRate` parameter for `trade()` was being computed all wrong by not normalizing for token decimals. :tired_face: 
Both contracts have been redeployed and addresses updated in `contract-addresses`.

Fix Kyber and Uniswap ERC20Bridges

---

.circleci/config.yml
python-packages/sra_client/test/relayer/docker-compose.yml

Remove unnecessary environment variables from the Mesh environment used by Python SRA client tests.

Pare down Mesh env vars in Py test env

---

packages/instant/.dogfood.discharge.json
packages/instant/.production.discharge.json
packages/instant/.staging.discharge.json

Adding in flag to keep v2.1 in s3 without a later upload of `umd/v3*` deleting the 2.1 build.
Related: https://github.com/0xProject/discharge/pull/1

Instant - Added should_remove_files_in_s3 flag in discharge configuration

---

packages/migrations/CHANGELOG.json
packages/migrations/Dockerfile

In using `0xorg/ganache-cli` for Neptune, we have a docker-compose file that includes an image for the `maker_keeper` service, which is dependent on another image for `ganache-cli`.  In attempting to re-run the `maker_keeper` image, docker-compose was bringing up the existing `ganache-cli` container, and hitting a prompt like:
```
Archive:  snapshot.zip
replace 0x_ganache_snapshot/!trie_db!0xdcd9cdbeca6483199e490e6fd0f1faf52bc1470d6e045421f0e86461b4c84578? [y]es, [n]o, [A]ll, [N]one, [r]ename: downloading snapshot version: 5.0.0
```
This was precluding us from re-running `maker_keeper` tests.
With this change, restarting an existing container will not hang on the prompt shown above, and will start up fully.
```bash
$ docker run -d -p 8545:8545 --name ganache 0xorg/ganache-cli
$ docker …
```

Fix 0xorg/ganache-cli docker image not supporting re-runs

---

contracts/exchange-forwarder/contracts/src/MixinAssets.sol
contracts/exchange-forwarder/contracts/src/MixinExchangeWrapper.sol
contracts/exchange-forwarder/contracts/test/TestForwarder.sol
contracts/exchange-forwarder/test/asset_test.ts
contracts/integrations/test/forwarder/forwarder_test.ts
contracts/integrations/test/forwarder/forwarder_test_factory.ts

Adds for MultiAsset `makerAssetData` and StaticCall `makerAssetData`/`makerFeeAssetData`/`takerFeeAssetData` in the Forwarder.
MultiAsset buy support is straightforward enough, but StaticCall `takerFeeAssetData` introduces some corner cases wrt how the Forwarder computes how much WETH has been spent. 
We could simplify the code a bit by restricting the user from providing StaticCall `takerFeeAssetData`, but one could plausibly have some weird use case where you'd want that due to for settlement order reasons 🤷‍♂
Edit: No longer supports StaticCall `takerFeeAssetData` for cleanliness' sake
Unit tests: `PKG=@0x/contracts-exchange-forwarder yarn test`
Integration tests: `PKG=@0x/contracts-integrations yarn test`
-   [ ] Add tests to cover …

`@0x/contracts-exchange-forwarder`: StaticCall support, MultiAsset buy support

---

contracts/exchange-libs/CHANGELOG.json
contracts/exchange-libs/package.json
contracts/exchange-libs/src/reference_functions.ts
contracts/integrations/CHANGELOG.json
contracts/integrations/test/framework/actors/maker.ts
contracts/integrations/test/framework/actors/taker.ts
contracts/integrations/test/framework/assertions/fillOrder.ts
contracts/integrations/test/framework/assertions/matchOrders.ts
contracts/integrations/test/framework/assertions/matchOrdersWithMaximalFill.ts
contracts/integrations/test/framework/utils/assert_protocol_fee.ts
contracts/integrations/test/framework/utils/verify_match_events.ts
contracts/integrations/test/fuzz_tests/match_orders_test.ts

This PR implements fuzz testing for `matchOrders` and `matchOrdersWithMaximalFill`. 
Included in this PR:
1. Maker actor can now generate matchable orders.
2. Taker actor can now match orders.
3. Reference functions for `matchOrders` and `matchOrdersWithMaximalFill`. 
4. Fuzz tests for `matchOrders` and `matchOrdersWithMaximalFill`. 
5. Fixed a bug in the fill order fuzz tests: `_validJoinStakingPool` was not recording the `poolId` after joining, so protocol fees were not getting validated by the `fillOrder` assertion.

Fuzz order matching

---

contracts/erc20-bridge-sampler/CHANGELOG.json
contracts/erc20-bridge-sampler/contracts/src/ERC20BridgeSampler.sol
contracts/erc20-bridge-sampler/contracts/test/TestERC20BridgeSampler.sol
contracts/erc20-bridge-sampler/test/erc20-bridge-sampler.ts
packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/index.ts
packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
packages/asset-swapper/src/utils/market_operation_utils/types.ts
packages/asset-swapper/src/utils/protocol_fee_utils.ts
packages/asset-swapper/test/exchange_swap_quote_consumer_test.ts
packages/asset-swapper/test/forwarder_swap_quote_consumer_test.ts
packages/asset-swapper/test/market_operation_utils_test.ts
packages/asset-swapper/test/swap_quote_consumer_utils_test.ts
packages/contract-artifacts/CHANGELOG.json
packages/contract-artifacts/artifacts/IERC20BridgeSampler.json
packages/contract-wrappers/src/generated-wrappers/i_erc20_bridge_sampler.ts

- Sampler contract now forwards more gas to kyber and eth2dai, to make up for large fills.
- Sampler now bails if any DEX sample reverts.
- Add exponential sampling distribution to `SwapQuoter`, exposed via option `sampleDistributionBase`.
- Tweak other default `SwapQuoter` options to be friendlier to big fills.
- Disable ethgasstation requests in `asset-swapper` tests because they can fail on CI.
**TODO**: Deploy thew new `ERC20BridgeSampler` contract and update `contract-addresses`. 

Feature/erc20 bridge sampler/query multiple buys sells tweaks

---

contracts/integrations/CHANGELOG.json
contracts/integrations/test/framework/actors/keeper.ts
contracts/integrations/test/framework/actors/pool_operator.ts
contracts/integrations/test/framework/actors/staker.ts
contracts/integrations/test/framework/assertions/createStakingPool.ts
contracts/integrations/test/framework/assertions/decreaseStakingPoolOperatorShare.ts
contracts/integrations/test/framework/assertions/endEpoch.ts
contracts/integrations/test/framework/assertions/finalizePool.ts
contracts/integrations/test/framework/assertions/generic_assertions.ts
contracts/integrations/test/framework/assertions/moveStake.ts
contracts/integrations/test/framework/assertions/unstake.ts
contracts/integrations/test/framework/assertions/withdrawDelegatorRewards.ts
contracts/integrations/test/fuzz_tests/pool_management_test.ts
contracts/integrations/test/fuzz_tests/stake_management_test.ts
contracts/integrations/test/fuzz_tests/staking_rewards_test.ts
contracts/test-utils/src/constants.ts

Adds "negative assertions" for `endEpoch`, `createStakingPool`, `decreaseStakingPoolOperatorShare`, `stake`, `unstake`, `moveStake`, and `withdrawDelegatorRewards` –– i.e. `FunctionAssertion`s that check revert conditions. 
Adds these new assertions to the fuzz tests, giving them lower weight than their valid counterparts. 
One notable omission is `fillOrder` –– imo it's already very thoroughly tested, and there are so many different ways it can revert that it's not as valuable to add negative assertions for. `fillOrder` is mostly important for the fuzz tests insofar as it generates protocol fees. 

`@0x/contracts-integrations`: Negative assertions for fuzzing

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/quote_consumers/exchange_swap_quote_consumer.ts

Inconsistency with `getCallData` and `execute` and with buy versus sell. In execute we use [`marketSellOrdersFillOrKill`](https://github.com/0xProject/0x-monorepo/pull/2450/files#diff-d9a13f38d79f128b4e2775a4f283d1e3R101)

[asset-swapper] Change Exchange sell to marketSellOrdersFillOrKill

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/swap_quote_calculator.ts
packages/asset-swapper/test/swap_quote_calculator_test.ts

There are scenarios where the protocol fee is actually *lower* when calculating the worst case fill order vs the best case. Because 0x-api uses the worst case protocol fees to compute the final quote `value`, we can end up underpaying gas at fill time.

asset-swapper: Fix understimated protocol fee in worst case quote.

---

packages/base-contract/CHANGELOG.json
packages/base-contract/src/index.ts

Was throwing inside a try/catch and immediately getting caught. Exception was then re-thrown as:
```js
{
message: 'VM execution error.',
data:
'Reverted 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000025455243323042726964676553616d706c65722f494e56414c49445f544f4b454e5f50414952000000000000000000000000000000000000000000000000000000' 
}
```

[base-contract] throw string revert error

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/index.ts
packages/asset-swapper/src/quote_consumers/swap_quote_consumer.ts
packages/asset-swapper/src/swap_quoter.ts
packages/asset-swapper/src/types.ts

In `@0x/asset-swapper`, some modules are instantiated by referring to addresses hardcoded in `@0x/contract-addresses`. This creates difficulty in testing because some contracts are not included on the Ganache snapshot or migration script e.g. ERC20BridgeSampler. 
This PR adds an optional `contractAddresses` param. If not provided, will fallback to previous behaviour of fetching from `@0x/contract-addresses`.
Tests should pass

Stop hardcoding contract addresses

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/package.json
packages/asset-swapper/src/swap_quoter.ts

Quick fix where we were pruning before we needed to check if we should create a dummy order. In the case we prune everything, we did not create a dummy.

[asset-swapper] prune before dummy order creation

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/constants.ts
packages/asset-swapper/src/swap_quoter.ts
packages/asset-swapper/src/types.ts
packages/asset-swapper/src/utils/market_operation_utils/constants.ts

Sometimes sampling can be over `16e6` gas. On Kovan we had disabled Kyber as sampling can sometimes be `55,883,366` from `estimateGas`. It's a crazy amount. If we go over the set gas limit it results in an OOG exception. If unset it uses the current block limit.
I've exposed the option so it can be modified in a pinch rather than being a fixed constant. 
Perhaps in the future we calculate this based on the numSamples and sources involved (plus some buffer for 0x Native orders)
We do restrict gas limits for Kyber (1.5mil), Eth2Dai (1mil), Uniswap (150k)
`34.5e6 = 1.5e6 * 13 + 1e6 * 13 + .15e6 * 13`. So assuming 0 Native orders and `13` samples, we need a limit in the worst case of `34.5e6`. Setting it to `36e6` to accounts for 0x native orders.

[asset-swapper] Bump sampler gas limit and allow for override

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/swap_quote_calculator.ts

Screwed up the math behind the liquidity breakdown, quick fix for that.

[FIX] asset-swapper liquidity breakdown

---

contracts/erc20-bridge-sampler/CHANGELOG.json
contracts/erc20-bridge-sampler/contracts/src/ERC20BridgeSampler.sol
packages/contract-addresses/CHANGELOG.json
packages/contract-addresses/addresses.json

Puts `getOrderRelevantState()` behind a `staticcall()` to catch reverts. Redeployed the sampler contract.

ERC20BridgeSampler: Catch DevUtils reverts

---

contracts/integrations/CHANGELOG.json
contracts/integrations/contracts/test/TestDydxUser.sol
contracts/integrations/test/bridges/dydx_bridge_mainnet_test.ts
contracts/integrations/test/mainnet_fork_utils.ts
contracts/test-utils/src/web3_wrapper.ts

Re-deployed the dYdX test user and updated the mainnet tests. The tests also use the new abi decoding.

Fixed dYdX Bridge Tests

---

contracts/broker/CHANGELOG.json
contracts/broker/src/gods_unchained_utils.ts
contracts/broker/src/index.ts
contracts/broker/test/gods_unchained_validator_test.ts
contracts/integrations/CHANGELOG.json
contracts/integrations/src/chainlink_utils.ts
contracts/integrations/test/broker/broker_test.ts
contracts/integrations/test/stop-limit/chainlink_stop_limit_test.ts

Adds decoding equivalents to the encoders found in `chainlink_utils` and `gods_unchained_utils`

Add decoders for broker and stop-limit data

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/fillable_amounts_utils.ts
packages/asset-swapper/src/utils/market_operation_utils/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/create_order.ts
packages/asset-swapper/src/utils/market_operation_utils/fill_optimizer.ts
packages/asset-swapper/src/utils/market_operation_utils/index.ts
packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
packages/asset-swapper/src/utils/market_operation_utils/types.ts
packages/asset-swapper/src/utils/swap_quote_calculator.ts
packages/asset-swapper/test/fillable_amounts_utils_test.ts
packages/asset-swapper/test/market_operation_utils_test.ts
packages/asset-swapper/test/swap_quote_calculator_test.ts

Small orders are hurting the bottom line on small swaps because of the fees involved in filling them. `asset-swapper` needs to account for gas and protocol fees to intelligently skip over these orders if they are not profitable. This will also help wrt gas-heavy DEXes like Kyber.
The basic idea is to express the gas + protocol fees, which are denominated in ETH, as an equivalent amount of maker or taker asset (depending on whether we're doing a buy or sell). This "penalty" is then added or subtracted to the fill output value during the optimization phase, which proceeds as normal.
To express the fees as the maker or taker asset, we ask the sampler contract for an additional sell quote of 1 ETH->X, where X is either the maker (sells) or taker (buys) asset. This allows us to convert …

Asset-Swapper: Incorporate fees into fill path optimization

---

packages/abi-gen/CHANGELOG.json
packages/abi-gen/package.json
packages/sol-compiler/CHANGELOG.json
packages/sol-doc/.npmignore
packages/sol-doc/CHANGELOG.json

`bin/*` was not present in the publish.
https://unpkg.com/browse/@0x/sol-doc@3.1.5/
```
(env) abi-gen λ npm publish --dry-run                                       fix/sol-doc/publish
npm notice
npm notice 📦  @0x/abi-gen@5.2.1
npm notice === Tarball Contents ===
npm notice 5.9kB  package.json
npm notice 23.8kB CHANGELOG.json
npm notice 11.1kB CHANGELOG.md
npm notice 6.8kB  README.md
npm notice 52B    bin/abi-gen.js
npm notice 66B    lib/src/index.d.ts
npm notice 107B   lib/src/index.d.ts.map
```
```
npm notice
npm notice 📦  @0x/sol-compiler@4.0.8
npm notice === Tarball Contents ===
npm notice 4.0kB  package.json
npm notice 18.5kB CHANGELOG.json
npm notice 7.5kB  CHANGELOG.md
npm notice 2.1kB  README.md
npm notice 49B    bin/sol-compiler.js
npm notice 91B    lib/src/cli.d.ts
npm notice …
```

Include bin in npm publish

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/create_order.ts
packages/asset-swapper/src/utils/market_operation_utils/sampler.ts
packages/asset-swapper/src/utils/market_operation_utils/types.ts
packages/asset-swapper/test/market_operation_utils_test.ts

Adds latest Curve (BUSD) 
https://github.com/curvefi/curve-contract/blob/pool_busd/deployed/2020-02-28_busd/mainnet.log
https://explore.duneanalytics.com/public/dashboards/ZaUkVovIfv5jm3OMqRochs3vTlc7PPUD4OjBOfrq
Migrates to latest Compound Curve (version 1)
https://github.com/curvefi/curve-contract/blob/pool_compound/deployed/2020-02-25_compound/mainnet.log
```json
{
"price": "1.0012382004075",
"to": "0x61935cbdd02287b511119ddb11aeb42f1593b7ef",
"data": "...",
"value": "3150000000000000",
"gas": "4065253",
"from": "REDACTED",
"gasPrice": "7000000000",
"protocolFee": "3150000000000000",
"buyTokenAddress": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
"sellTokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f",
"buyAmount": "400495280163",
"sellAmount": "400000000000000000000000", …
```

[asset-swapper] Add latest BUSD Curve

---

packages/sol-compiler/src/utils/compiler.ts

Add parent filename when resolving on the parents dependencies fails. This makes it so that it's easy to figure out which file has invalid import when multiple contracts has the same failing imports. Commonly happens during sweeping refactors.
Run compiler on a smart contract that has an incorrect import path for a dependency, inspect that the error message now reports the smart contract file within the error description.
- Add parent filename when resolving on the parents dependencies fails.
I didnt modify the changelog since I dont know if 0x wants to include extra features in the next release.

Update resolver errors to include parent filename

---

packages/asset-swapper/package.json
yarn.lock

Works pretty well?
It uploads the package as built to https://github.com/0xProject/gitpkg-registry/releases and uses the version in `package.json` as the tag. We need to establish some conventions around how to do this but seems useful?

Install gitpkg in asset-swapper

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/swap_quote_calculator.ts

`feeSchedule` wasn't being passed into `MarketOperationUtils`.

`@0x/asset-swapper`: Fix fee schedule not being scaled by gas price.

---

contracts/asset-proxy/CHANGELOG.json
contracts/asset-proxy/contracts/src/interfaces/IERC20Bridge.sol

The old ones were pretty ambiguous. So instead of `fromToken` an `toToken`, we have `inputToken` and `outputToken`, respectively.

Rename `ERC20BridgeTransfer` event args

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/fills.ts
packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts

When the optimizer was building a quote, it wasn't clipping the input/output amounts of a tail-end fill by the remaining input amount. So a large enough fill (usually native orders) could be attributed a higher return rate than it really should. This fix also apparently improves quoted and realized prices slightly, even though I wasn't trying to.
Also updated the ethgasstation poll rate to ~half the block time, because gas price is a lot more mercurial during the end of the world.

AssetSwapper: Fix quote optimizer fee bug

---

contracts/utils/CHANGELOG.json
contracts/utils/contracts/src/DeploymentConstants.sol
packages/contract-addresses/CHANGELOG.json
packages/contract-addresses/addresses.json

Sets the GSTCollector address for freeing GST in Bridges (Curve).
Redeployed CurveBridge with the address set.

Set GSTCollector address and deploy Curve

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/index.ts

`_generateOptimizedOrders` Can throw `NO_OPTIMAL_PATH`, catch it since we don't want one throw to spoil the broth.

[asset-swapper] Fix getBatchMarketBuyOrdersAsync

---

contracts/erc20-bridge-sampler/CHANGELOG.json
contracts/erc20-bridge-sampler/contracts/src/ERC20BridgeSampler.sol
contracts/erc20-bridge-sampler/contracts/test/TestERC20BridgeSampler.sol
contracts/integrations/CHANGELOG.json
contracts/integrations/test/bridge_sampler/bridge_sampler_mainnet_test.ts

Helps with RFQT integration tests.

ERC20BridgeSampler: Pass in `DevUtils` address as a constructor arg

---

.circleci/config.yml
python-packages/sra_client/test/relayer/docker-compose.yml

The "latest" ganache snapshot, 6.2.4, broke the test-python CI job.
- The last time this CI job passed on the development branch was March 6 at 15:34
- The first time it failed was on March 6 at 16:44.
- Ganahce snapshot 6.2.4, copied to latest, was published at 16:17, exactly in that window.
(All times EST)
The surface failure symptom is an SRA response HTTP 100, "Validation failed", with the reason `EthRPCRequestFailed: network request to Ethereum RPC endpoint failed`.
That RPC message seems to be being relayed from Mesh, whose log shows many entries like:
`{"attempt_number":0,"error_string":"abi: unmarshalling empty output","level":"info","msg":"GetOrderRelevantStates request failed","myPeerID":"16Uiu2HAmNmNAjt947uJLhSg98FjXb6ymi2nUphBmHEwFfeiSTUL3","numOrders_number":3,"time":"2020-03- …

Pin python tests to ganache snapshot 6.0.0

---

python-packages/contract_wrappers/setup.py

The latest version of the sphinx (documentation generation tool) broke our build.  I reported the problem [here](https://github.com/sphinx-doc/sphinx/issues/7429).  This change pins us to the previous version.

py/contract_wrappers: Pin sphinx to prev version

---

packages/asset-swapper/src/utils/market_operation_utils/orders.ts
packages/asset-swapper/test/market_operation_utils_test.ts

Use DFB even when there is only one source.
* Gives us a single entry point to monitor
* Allows burning of GST over all sources

Always use DFB in asset-swapper

---

packages/asset-swapper/src/utils/quote_requestor.ts
packages/asset-swapper/test/quote_requestor_test.ts

* Validates taker and maker asset data
* Validates signedOrderSchema instead of just orderSchema
* Adds some more logs
* Adds some more tests

RFQ-T: validate assetData & add more tests

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/orders.ts
packages/asset-swapper/test/market_operation_utils_test.ts

Collapse as many sources into DexForwarderBridge as possible to reduce excess protocol fees for on-chain sources.

Collapse on-chain sources into DexForwarderBridge

---

contracts/zero-ex/contracts/src/features/Migrate.sol
contracts/zero-ex/contracts/src/features/Ownable.sol
contracts/zero-ex/contracts/src/storage/LibStorage.sol

Adds `Unused` as the first enum value in the `StorageId` enum.
This means real buckets start at `1e18`, which gives us a safety buffer in case we accidentally deploy a feature that uses non-bucketed state variables.

ZeroEx: Add `Unused` to `StorageId` enum

---

packages/asset-swapper/src/swap_quoter.ts
packages/asset-swapper/src/types.ts
packages/asset-swapper/src/utils/quote_requestor.ts

For use in integrations that have specific log formats to adhere to.

asset-swapper: support RFQ-T logger callback

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/constants.ts
packages/asset-swapper/src/utils/market_operation_utils/orders.ts
packages/asset-swapper/src/utils/market_operation_utils/types.ts
packages/asset-swapper/test/market_operation_utils_test.ts

Adds Curve sUSD plain (no underlying yTokens)
```
curl 'http://localhost:3000/swap/v0/quote?buyToken=USDT&sellToken=DAI&sellAmount=100000000000000000000000&takerAddress=WHALE'
```
```json
{
"price": "1.00919950822",
"guaranteedPrice": "0.97892059851",
"to": "0x61935cbdd02287b511119ddb11aeb42f1593b7ef",
"value": "1200000000000000",
"gas": "3634181",
"from": "WHALE",
"gasPrice": "8000000000",
"protocolFee": "1200000000000000",
"buyTokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
"sellTokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f",
"buyAmount": "100919950822",
"sellAmount": "100000000000000000000000",
"sources": [
{
"name": "0x",
"proportion": "0"
},
{
"name": "Uniswap",
"proportion": "0"
},
{
"name": "Eth2Dai",
"proportion": "0"
},
{
"name": "Kyber",
"proportion": …
```

Add Curve sUSD

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/fills.ts
packages/asset-swapper/src/utils/market_operation_utils/path_optimizer.ts
packages/asset-swapper/test/market_operation_utils_test.ts

There is a scenario where perfectly sized Native orders were penalized more aggressively than they should have been. 
The previous behaviour was as follows:
```
penaltyMakerUnits = 10
input = 2000
SMALL_ORDER
makerAmount = 100
takerAmount = 200
adjustedOutput = 90
adjustedRate = 0.45
BIG_ORDER
makerAmount = 1000
takerAmount = 2000
adjustedOutput = 990
adjustedRate = 0.495
```
In the scenario where the user wishes to sell `2000` the `SMALL_ORDER` should be penalized over `BIG_ORDER` and `BIG_ORDER` should be favoured. 
In the scenario where the user wishes to sell `200` both `SMALL_ORDER` and `BIG_ORDER` are sufficient and either is acceptable to fill.
```
penaltyMakerUnits = 10
input = 200
SMALL_ORDER
makerAmount = 100
takerAmount = 200
adjustedOutput = (min(takerAmount, input) / …
```

[asset-swapper] clip native fill data

---

packages/contract-addresses/CHANGELOG.json
packages/contract-addresses/addresses.json

Previous ERC20BridgeSampler on Kovan had mainnet addresses for on-chain sources

fix: contract-addresses ERC20BridgeSampler

---

packages/utils/CHANGELOG.json
packages/utils/src/abi_encoder/abstract_data_types/types/set.ts

fixes https://github.com/0xProject/0x-monorepo/issues/2558
gotta love js
http://web.mit.edu/jwalden/www/isArray.html

instanceof Array -> Array.isArray

---

contracts/utils/contracts/src/v06/interfaces/IOwnableV06.sol
contracts/zero-ex/contracts/src/features/Ownable.sol
contracts/zero-ex/contracts/test/TestMigrator.sol
contracts/zero-ex/test/features/ownable_test.ts
contracts/zero-ex/test/initial_migration_test.ts

Reverts `IOwnableV06` to use `owner()` instead of `getOwner()`, so it's compatible with the old (pre-0.6) `IOwnable` interface.

ZeroEx: IOwnable(V06) compatibility

---

python-packages/middlewares/setup.py
python-packages/order_utils/src/zero_ex/order_utils/asset_data_utils.py

The `development` branch is failing, due to a recent update to `pylint` that is apparently checking some things more stringently.  This PR changes a few tiny code spots in order to conform to the new checks.

Python: adapt to latest version of pylint

---

python-packages/contract_wrappers/setup.py
python-packages/contract_wrappers/src/conf.py
python-packages/contract_wrappers/src/index.rst
python-packages/json_schemas/setup.py
python-packages/json_schemas/src/conf.py
python-packages/middlewares/setup.py
python-packages/middlewares/src/conf.py
python-packages/order_utils/setup.py
python-packages/order_utils/src/conf.py
python-packages/order_utils/src/index.rst
python-packages/sra_client/setup.py
python-packages/sra_client/src/conf.py

Recently we pinned the Sphinx dependency to a specific version, because the latest version was breaking our build.
This PR changes our Sphinx usage in order to avoid the breakage, and removes the pin.

Python: unpin Sphinx dependency, clean up warnings

---

contracts/zero-ex/contracts/src/migrations/InitialMigration.sol
contracts/zero-ex/contracts/test/TestInitialMigration.sol
contracts/zero-ex/test/initial_migration_test.ts
contracts/zero-ex/test/utils/migration.ts
packages/contract-wrappers-test/package.json

The `InitialMigration` contract had a race condition where anyone could call `deploy()` first and prevent the governor from calling it. Not a vuln, just a nuisance.
Now the caller to `deploy()` is set in the constructor of `InitialMigration` AND the contract self-destructs before returning. The old comments actually stated this latter behavior but the code never actually did it.

ZeroEx: InitialMigration Race Condition/Self-destruct

---

contracts/zero-ex/contracts/src/storage/LibOwnableStorage.sol
contracts/zero-ex/contracts/src/storage/LibProxyStorage.sol
contracts/zero-ex/contracts/src/storage/LibSimpleFunctionRegistryStorage.sol
contracts/zero-ex/contracts/src/storage/LibStorage.sol

Some small changes based on early audit feedback.
- Remove `Unused` enum value from `StorageId`.
- Always add `1` to the (uint256 cast) storage ID, so no more need for ^.
- Bit-shift by `128` instead of multiplying by `10**18` to save gas and space buckets out even more.
- Link to solidity docs in comments.
- Rename "offset" verbiage to "slot," since this is more accurate.

ZeroEx: Always offset storage bucket ID by 1.

---

packages/abi-gen/test-cli/output/python/lib_dummy/__init__.py
packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/types.ts
packages/asset-swapper/src/utils/swap_quote_calculator.ts
packages/asset-swapper/test/utils/swap_quote.ts

In order to calculate `estimatedGasTokenRefund` in API we need more information from asset-swapper.

Expose fills object in asset-swapper quote orders

---

packages/asset-swapper/src/utils/quote_requestor.ts

An example of a test's output before this change:
`{"rfqtMakerInteraction":{"url":"https://37.0.0.1","quoteType":"firm","requestParams":{"takerAddress":"0xd209925defc99488e3afff1174e48b4fa628302a","buyToken":"0x34d402f14d58e001d8efbe6585051bf9706aa064","sellToken":"0x25b8fe1de9daf8ba351890744ff28cf7dfa8f5e3","sellAmount":"10000"},"response":{"latencyMs":27}}}`
And that same test's output after this change:
`{"rfqtMakerInteraction":{"url":"https://37.0.0.1","quoteType":"firm","requestParams":{"takerAddress":"0xd209925defc99488e3afff1174e48b4fa628302a","buyToken":"0x34d402f14d58e001d8efbe6585051bf9706aa064","sellToken":"0x25b8fe1de9daf8ba351890744ff28cf7dfa8f5e3","sellAmount":"10000"},"response":{"statusCode":404,"latencyMs":4}}}`

asset-s/QuoteRequestor: fix statusCode logging

---

contracts/zero-ex/contracts/src/ZeroEx.sol
contracts/zero-ex/contracts/src/errors/LibOwnableRichErrors.sol
contracts/zero-ex/contracts/src/features/Ownable.sol
contracts/zero-ex/contracts/src/features/SimpleFunctionRegistry.sol
contracts/zero-ex/contracts/src/fixins/FixinCommon.sol
contracts/zero-ex/contracts/src/migrations/InitialMigration.sol
contracts/zero-ex/contracts/src/storage/LibOwnableStorage.sol
contracts/zero-ex/contracts/src/storage/LibProxyStorage.sol
contracts/zero-ex/contracts/src/storage/LibSimpleFunctionRegistryStorage.sol
contracts/zero-ex/contracts/src/storage/LibTokenSpenderStorage.sol
contracts/zero-ex/contracts/src/storage/LibTransformERC20Storage.sol
contracts/zero-ex/test/initial_migration_test.ts
packages/utils/src/revert_errors/zero-ex/ownable_revert_errors.ts

- Bring back `_extendSelf()`.
- I feel this is ultimately the cleanest solution. Clean separation and no need to dip into anyone else's storage.
- The `InitialMigration` contract will deregister it after bootstrap completes.
- `FixinCommon.onlyOwner` modifier no longer reads directly from `Ownable`'s storage thanks to ^.
- Removed easily bypassed reentrancy check on `Ownable.migrate()`.
- Clean up some misleading comments.
- Add comments to assembly.

ZeroEx: Audit Fixes

---

python-packages/contract_addresses/setup.py
python-packages/contract_artifacts/setup.py
python-packages/contract_wrappers/setup.py
python-packages/json_schemas/setup.py
python-packages/middlewares/setup.py
python-packages/order_utils/setup.py

A new check in the `mypy` Python type checker is flagging an issue with our code.  I took a look at fixing our code, and it was non-trivial, so in the mean time this change pins `mypy` to the version which doesn't flag this issue.
See also https://github.com/python/mypy/issues/8953

Python: pin mypy to <= 0.770

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/utils/market_operation_utils/orders.ts

Re-order the UniswapV2 path to be takerToken to makerToken.

fix: UniswapV2 path order

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/quote_consumers/exchange_proxy_swap_quote_consumer.ts
packages/asset-swapper/src/utils/quote_simulation.ts
packages/asset-swapper/test/quote_simulation_test.ts

Worst case asset amount calculations were off by a lot because the fill simulator made the assumption that optimized orders were always sorted. Frequently this would result in worst case buy estimates being better than best case buy estimates. Temporarily sorting the orders before simulating a worst case fill gives us a more realistic lower-bound.
In the Forwarder/Exchange Proxy this manifested as a revert since we were not providing enough input tokens to fill the orders.

asset-swapper: Fix worst case asset amount calculations.

---

packages/asset-swapper/CHANGELOG.json
packages/asset-swapper/src/quote_consumers/forwarder_swap_quote_consumer.ts
packages/asset-swapper/test/forwarder_swap_quote_consumer_test.ts

There seems to be a rounding bug in the Forwarder contract than can cause *buys* of  ETH->low decimal tokens to regularly (30-50%) fail. Simulations show a small "nudge" of the *maximum* sell amount of 1 bps is enough to overcome this rounding error in nearly all cases. This is PR applies this short-term hack to the `ForwarderSwapQuoteConsumer` until we identify and fix the rounding error in the Forwarder contract.

asset-swapper: "Fix" forwarder buys of low decimal tokens.
