src/0x.ts, src/contract_wrappers/contract_wrapper.ts, src/contract_wrappers/exchange_wrapper.ts, src/contract_wrappers/token_registry_wrapper.ts, src/contract_wrappers/token_wrapper.ts, src/types.ts, src/utils/assert.ts, src/utils/decorators.ts, src/utils/utils.ts, src/web3_wrapper.ts, test/0x.js_test.ts, test/schema_test.ts, test/token_registry_wrapper_test.ts, test/utils/order_factory.ts, test/utils/token_utils.ts
Reverts 0xProject/0x.js#71
We'll use a different approach
=> Revert "Use different lodash import syntax which allows to include only used functions"

package.json, src/globals.d.ts, test/artifacts_test.ts, test/utils/constants.ts, yarn.lock
This PR:
* Adds integration tests that check that contracts are deployed on kovan network
=> Add kovan integration tests

CHANGELOG.md, src/0x.ts, src/contract_wrappers/exchange_wrapper.ts, src/contract_wrappers/proxy_wrapper.ts, src/types.ts, test/exchange_wrapper_test.ts, test/proxy_wrapper_test.ts
This PR:
* Makes proxy a public property on a zeroEx instance
* Exposes `zeroEx.proxy.isAuthorizedAsync`
* Adds `zeroEx.proxy.getAuthorizedAddressesAsync`
=> Add zeroEx.proxy

test/utils/fill_scenarios.ts
This PR:
* Speeds up tests for me by ~10 seconds
* Makes the code more readable and understandable
* Only affects tests
=> Paralellize fill scenarios

CHANGELOG.md, src/0x.ts, test/0x.js_test.ts, test/exchange_wrapper_test.ts, test/utils/order_factory.ts
This PR:
* Makes getOrderHashHex static
=> Static get order hash hex

CHANGELOG.md, package.json, src/schemas/basic_type_schemas.ts, src/utils/assert.ts, test/0x.js_test.ts, test/schema_test.ts, test/token_wrapper_test.ts, yarn.lock
This PR:
* Changes address schema to reject checksummed addresses
=> Reject checksummed addresses

CHANGELOG.md, src/contract_wrappers/exchange_wrapper.ts, test/exchange_wrapper_test.ts, test/order_validation_test.ts, test/token_wrapper_test.ts, test/utils/fill_scenarios.ts
This PR:
* Fixes the description of shouldThrowOnInsufficientBalanceOrAllowance in docs
=> Fix the docs for shouldThrowOnInsufficientBalanceOrAllowance

CHANGELOG.md, src/contract_wrappers/contract_wrapper.ts, src/contract_wrappers/token_wrapper.ts
This PR:
* Converts addresses from artifacts `toLowerCase` before using
=> Artifacts addresses

CHANGELOG.md, src/0x.ts, src/contract_wrappers/contract_wrapper.ts, src/contract_wrappers/ether_token_wrapper.ts, src/contract_wrappers/exchange_wrapper.ts, src/contract_wrappers/token_registry_wrapper.ts, src/contract_wrappers/token_wrapper.ts, src/globals.d.ts, src/index.ts, src/types.ts, src/web3_wrapper.ts, test/ether_token_wrapper_test.ts
This PR:
* Allows the user to specify gas price for transactions when instantiating `ZeroEx`
=> Gas price config

package.json, src/0x.ts, src/globals.d.ts, src/types.ts, src/utils/abi_decoder.ts, test/0x.js_test.ts, yarn.lock
This PR:
* Removed abi-decoder as a dependency
* Reimplments a subset of it in TS
* Handles the case, when the log can't be decoded
=> Custom abi decoder

src/artifacts.ts, src/contract_wrappers/contract_wrapper.ts, src/globals.d.ts, src/types.ts, src/web3_wrapper.ts
=> Move Aftifact type definition to 'types'

CHANGELOG.md, package.json
=> Add bignumber.js types as a dependency

CHANGELOG.md, src/contract_wrappers/exchange_wrapper.ts, src/contract_wrappers/token_wrapper.ts, src/index.ts, src/types.ts
This PR:
* Adds a posibility to specify defaultBlock when calling const blockchain methods
=> Add a possibility to specify defaultBlock when calling const blockchain methods

CHANGELOG.md, src/contract_wrappers/exchange_wrapper.ts, test/exchange_wrapper_test.ts
This PR:
* Makes `zeroEx.exchange.getZRXTokenAddressAsync` public
=> Make getZRXTokenAddressAsync public

CHANGELOG.md, src/utils/order_validation_utils.ts, test/order_validation_test.ts
This PR:
* Fixes fees validations when one of the tokens is ZRX
=> Fees validations when one of the tokens is ZRX

CHANGELOG.md, src/index.ts
This PR:
* exports `ContractEventArg`
=> Export ContractEventArg

CHANGELOG.md, src/utils/order_validation_utils.ts, test/order_validation_test.ts, test/utils/fill_scenarios.ts
This PR:
* Fixes an issue causing fills to throw `INSUFFICIENT_TAKER_ALLOWANCE`
* Adds a regression test for it
* Fixes #192
=> Fix an issue causing fills to throw `INSUFFICIENT_TAKER_ALLOWANCE`

package.json, test/utils/rpc.ts
This PR:
* Fixed lint script to look at nested files
* Fixed one lint error that popped up as a result
=> Fix lint script to analyze nested files

circle.yml, src/contract_wrappers/contract_wrapper.ts, src/contract_wrappers/exchange_wrapper.ts, src/contract_wrappers/token_wrapper.ts, src/types.ts, test/exchange_wrapper_test.ts, test/subscription_test.ts, test/token_wrapper_test.ts
This PR:
* Fixes an unhandled promise rejection error on subscriptions
=> Fix unhandled promise rejection error on subscriptions

package.json, src/index.ts, src/types.ts, src/web3_wrapper.ts, test/token_wrapper_test.ts, yarn.lock
This PR:
* Normalizes the status field in a transaction receipt
=> Normalize the way we return the transaction status

.circleci/config.yml, packages/0x.js/package.json
=> Mono repo Final Steps

packages/0x.js/CHANGELOG.md, packages/0x.js/src/contract_wrappers/exchange_wrapper.ts, packages/0x.js/src/stores/order_filled_cancelled_lazy_store.ts, packages/0x.js/src/types.ts, packages/0x.js/src/utils/order_state_utils.ts, packages/0x.js/test/exchange_wrapper_test.ts, packages/0x.js/test/order_state_watcher_test.ts
This PR:
* Standardise on Cancelled over canceled
=> Standardise on Cancelled over canceled

packages/0x.js/package.json, packages/0x.js/src/utils/abi_decoder.ts, packages/0x.js/tslint.json, packages/assert/package.json, packages/tslint-config/README.md, packages/tslint-config/package.json, packages/tslint-config/tslint.json, yarn.lock
This PR:
* Adds the tslint-config package into this repo
* Upgrade to tslint 5.8.0 and update our tslint rules accordingly
* Fixed some dormant tslint issues
* Use tslint-config in all other sub-packages
=> Add TSLint Config package

packages/0x.js/src/types.ts, packages/0x.js/src/utils/order_state_utils.ts, packages/0x.js/test/order_state_watcher_test.ts
This PR:
* Adds a validations that the order values are within the range without rounding errors
=> Rounding validation

packages/0x.js/CHANGELOG.md, packages/0x.js/src/order_watcher/order_state_watcher.ts, packages/0x.js/test/order_state_watcher_test.ts
This PR:
* When ZRX isn't the makerToken, any ZRX (fee) movements will now be tracked.
=> Track ZRX Approval and Balance events

packages/connect/package.json, packages/connect/scripts/postpublish.js, packages/connect/src/http_client.ts, packages/connect/src/index.ts, packages/connect/test/ws_orderbook_channel_test.ts
This PR:
* add docs generation to connect/scripts/postPublish.js
* remove websocket related classes and types from public interface
* correctly configure BigNumber and fix issue with stringifying HTTP post request payloads
=> Prepare connect package for publishing

packages/0x.js/src/order_watcher/order_state_watcher.ts
This PR:
* Removes duplicate events by introducing order state cache
=> Add an order state cache to filter out duplicate events

packages/0x.js/src/types.ts, packages/website/ts/pages/documentation/method_block.tsx, packages/website/ts/pages/documentation/source_link.tsx, packages/website/ts/pages/documentation/type.tsx, packages/website/ts/utils/constants.ts
This PR:
* Fixes overlapping argument name and descriptions
* Fixed source links
* Added Web3 prefix to web3 type aliases and links to typings
* Add link to provider explanation from provider type comment
=> Fix 0x.js Doc Issues

packages/connect/src/http_client.ts, packages/connect/src/types.ts, packages/connect/src/ws_orderbook_channel.ts
This PR:
* move types from http_client.ts and ws_orderbook_channel.ts into types.ts
=> Move all connect types into types.ts

packages/0x.js/src/order_watcher/order_state_watcher.ts, packages/0x.js/src/types.ts
This PR:
* Adds a cleanup job to an order watcher
=> Add a cleanup job to an order watcher

packages/subproviders/CHANGELOG.md, packages/subproviders/package.json, packages/subproviders/src/globals.d.ts, packages/subproviders/src/subproviders/ledger.ts, packages/subproviders/src/types.ts, packages/subproviders/test/unit/ledger_subprovider_test.ts, yarn.lock
This PR:
* Uses HD library to derive addresses from pk and chain code instead of asking ledger for each address
=> Implement ledger optimization for address derivation

packages/0x.js/CHANGELOG.md, packages/0x.js/src/contract_wrappers/contract_wrapper.ts, packages/0x.js/src/contract_wrappers/exchange_wrapper.ts, packages/0x.js/src/contract_wrappers/token_wrapper.ts, packages/0x.js/src/index.ts, packages/0x.js/src/types.ts, packages/0x.js/src/utils/filter_utils.ts, packages/0x.js/test/exchange_wrapper_test.ts, packages/0x.js/test/token_wrapper_test.ts, packages/json-schemas/CHANGELOG.md, packages/json-schemas/schemas/block_range_schema.ts, packages/json-schemas/src/schemas.ts, packages/json-schemas/test/schema_test.ts, packages/website/ts/blockchain.ts, packages/website/ts/containers/zero_ex_js_documentation.tsx
This PR:
* Renames the type (and schema) to better represent it's content
=> Rename SubscriptionOpts to BlockRange

packages/abi-gen/package.json, packages/contracts/deploy/cli.ts, packages/contracts/deploy/src/utils/types.ts, packages/contracts/globals.d.ts, packages/contracts/package.json, yarn.lock
This PR:
* Adds proper types for yargs and ethereumjs-abi in contracts
=> Add proper types for yargs and ethereumjs-abi

README.md, packages/monorepo-scripts/README.md, packages/subproviders/README.md, packages/website/README.md
This PR:
* Adds/improves README's for `subproviders`, `website`, `monoRepoScripts` as well as the main mono repo README as per the Quip guidelines.
* Improves the topLevel readme package descriptions.
=> Improve/Add to README's

packages/assert/README.md, packages/json-schemas/README.md, packages/tslint-config/README.md, packages/web3-wrapper/README.md
This PR:
* Adds README's according to this template https://quip.com/I8G9AIIs05Ta for 4 subpackages
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/receleUOwdnfj0K6E
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/rec0Vwdk55VvzRPkK
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/recTU2i7xHK4ZVI43
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/recTPm5SgCNrZjFoQ
=> Write 4 README's

packages/contracts/README.md
This PR:
* Updates and standardizes the contracts README
https://airtable.com/tblFe0Q9JuKJPYbTn/viw2LUWhbLzAsfGXH/recfsNB13kgpvHzHv
=> Update and standardize contracts README

packages/abi-gen/src/index.ts
We're beginning to use Abi-Gen in JoinCivil and it's very useful. Adding the ability to generate good APIs for Events we can skip a lot of manual work later on.
=> Added Event generation to abi-gen

packages/connect/CHANGELOG.md, packages/connect/src/http_client.ts, packages/connect/test/http_client_test.ts, yarn.lock
This PR:
* Sanitize HttpClient api urls and improve error messaging
=> Improve HttpClient errors

packages/0x.js/CHANGELOG.md, packages/0x.js/package.json, packages/0x.js/src/0x.ts, packages/0x.js/src/contract_wrappers/contract_wrapper.ts, packages/0x.js/src/order_watcher/event_watcher.ts, packages/0x.js/src/order_watcher/expiration_watcher.ts, packages/0x.js/src/order_watcher/order_state_watcher.ts, packages/0x.js/src/types.ts, packages/0x.js/test/event_watcher_test.ts, packages/0x.js/test/order_state_watcher_test.ts, packages/0x.js/test/utils/report_callback_errors.ts, packages/connect/package.json, packages/contracts/package.json, packages/tslint-config/package.json, packages/utils/CHANGELOG.md, packages/utils/src/interval_utils.ts, packages/web3-typescript-typings/package.json, packages/website/package.json
This PR:
* Resolves https://github.com/0xProject/0x.js/issues/308
* Makes `EventWatcher` and `OrderWatcher` callbacks failable
* Extends intervalUtils to also support sync intervals
=> Better error handling on async/sync intervals

packages/0x.js/CHANGELOG.md, packages/0x.js/package.json, packages/0x.js/src/artifacts/EtherToken.json, packages/0x.js/src/artifacts/Exchange.json, packages/0x.js/src/artifacts/TokenRegistry.json, packages/0x.js/src/artifacts/TokenTransferProxy.json, packages/0x.js/src/artifacts/ZRX.json, packages/chai-as-promised-typescript-typings/package.json, packages/connect/package.json, packages/contracts/package.json, packages/testnet-faucets/README.md, packages/tslint-config/package.json, packages/web3-typescript-typings/package.json, packages/website/package.json
- Adds Rinkeby addresses to 0x.js artifacts
=> Add Rinkeby addresses to artifacts

packages/deployer/src/solc/bin_paths.ts
Add Solidity compiler v. 0.4.19 to those supported by deployer.
We should target the latest version of Solidity for new contracts. This lowers exposure to compiler bugs and adds more static validation.
Works for me.
=> Add solc 0.4.19

packages/website/package.json, packages/website/public/index.html, packages/website/ts/components/fill_order.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/inputs/allowance_toggle.tsx, packages/website/ts/globals.d.ts, packages/website/ts/index.tsx
Added Google Analytics event logging for key user activity in the portal.
Allows us to better understand what actions users are taking when they go to portal beyond existing traffic numbers. Can also be used to find errors and bugs in the future.
1. Go to allowances page.
2. Set allowance for WETH and ZRX
3. Verify that allowance events for WETH and ZRX have been logged
https://analytics.google.com/analytics/web/?authuser=1#report/content-event-overview/a98720122w145076439p149780311/%3F_u.date00%3D20180205%26_u.date01%3D20180205%26overview-dimensionSummary.selectedGroup%3Dvisitors%26overview-dimensionSummary.selectedDimension%3Danalytics.eventLabel/
1. Go to orders page
2. Sign order
3. Verify that sign order events have been logged
=> Add GA Logging to Portal

packages/testnet-faucets/src/ts/handler.ts
Create signed orders with Base Unit amounts
=> Convert to baseUnits in signed order

packages/connect/CHANGELOG.md, packages/connect/src/http_client.ts
=> Do not JSON parse empty reponse

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md, package.json, packages/connect/README.md, packages/contracts/README.md, packages/json-schemas/CHANGELOG.md, packages/subproviders/README.md, packages/website/README.md, packages/website/md/docs/smart_contracts/introduction.md, yarn.lock
Upgrade prettier to a never version
=> Upgrade prettier

packages/website/ts/utils/utils.ts
Fixed issue from move to react-shared
=> Fixed merge issue

packages/web3-wrapper/CHANGELOG.md, packages/web3-wrapper/src/index.ts, packages/website/package.json, packages/website/ts/blockchain.ts, packages/website/ts/blockchain_watcher.ts, packages/website/ts/components/dialogs/eth_weth_conversion_dialog.tsx, packages/website/ts/components/dialogs/ledger_config_dialog.tsx, packages/website/ts/components/eth_weth_conversion_button.tsx, packages/website/ts/components/eth_wrappers.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/inputs/allowance_toggle.tsx, packages/website/ts/components/inputs/token_amount_input.tsx, packages/website/ts/components/portal.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/trade_history/trade_history_item.tsx, packages/website/ts/components/visual_order.tsx, packages/website/ts/containers/portal.ts, packages/website/ts/redux/dispatcher.ts, packages/website/ts/redux/reducer.ts, packages/website/ts/utils/configs.ts, packages/website/ts/web3_wrapper.ts
- Removes custom web3Wrapper from website (@0xproject/web3-wrapper)
- Refactors Portal to pass around Ether amounts in wei, and to only convert to Ether before displaying an amount.
- Removed unnecessary `exchangeAddress` instance variable from `blockchain.ts`.
*   [x] Updated the new versions of the changed packages in the relevant CHANGELOGs.
*   [ ] …
=> Remove custom web3Wrapper from website

packages/abi-gen/README.md
=> Update README for abi-gen

packages/website/ts/blockchain.ts, packages/website/ts/components/fill_order.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/inputs/allowance_toggle.tsx, packages/website/ts/index.tsx, packages/website/ts/types.ts, packages/website/ts/utils/analytics.ts, packages/website/ts/utils/configs.ts, packages/website/ts/utils/constants.ts, packages/website/ts/utils/utils.ts
…e, combining the provider type util function, moving GA id to configs and using utils.onPageLoadAsync
- Move all calls to ReactGA into a single module
- Merge disparate provider name logic to use single utils method
- Move Google analytics id to configs
- Re-use utils.onPageLoadAsync
*   [ ] Labeled this PR with the 'WIP' label if it is a work …
=> Refactor Website Analytics

packages/react-shared/CHANGELOG.md, packages/react-shared/src/utils/colors.ts, packages/website/ts/components/eth_wrappers.tsx, packages/website/ts/components/portal.tsx, packages/website/ts/components/portal_menu.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/wallet.tsx, packages/website/ts/types.ts
Initial wallet interface for the portal redesign. The component currently resides in a "Wallet" tab that is for development only.
TODO:
*   [ ] Error states
*   [ ] Loading states
*   [ ] Wrap/unwrap flow
*   [ ] Adding tokens flow
*   [ ] Prices in dollars
*   [ ] Onboarding
N/A
N/A
*   [x] Labeled this PR with the 'WIP' label if it is a work …
=> Implement initial wallet interface

packages/website/ts/blockchain.ts, packages/website/ts/utils/configs.ts
Removes the hard-coded WETH addressses from 0x Portal now that the TokenRegistry is up-to-date.
=> Remove WETH hack now that updated WETH address is in TokenRegistry

packages/0x.js/src/0x.ts, packages/0x.js/src/order_watcher/event_watcher.ts, packages/0x.js/src/order_watcher/order_state_watcher.ts, packages/0x.js/test/order_state_watcher_test.ts, packages/contracts/package.json, packages/deployer/CHANGELOG.md, packages/deployer/src/compiler.ts, packages/deployer/src/utils/compiler.ts, packages/deployer/test/compiler_utils_test.ts
* Adds missing import for `Web3Provider` type
* Creates the `solc_bin` directory in the deployer package if it does not already exist
=> Fix build errors

packages/website/ts/components/portal.tsx, packages/website/ts/components/portal_menu.tsx, packages/website/ts/components/relayer_index/relayer_grid_tile.tsx, packages/website/ts/components/relayer_index/relayer_index.tsx, packages/website/ts/components/relayer_index/relayer_top_tokens.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/types.ts
N/A
N/A
*   [x] Updated the new versions of the changed packages in the relevant CHANGELOGs.
=> Implement initial relayer grid

packages/contracts/src/contracts/current/protocol/Exchange/MixinWrapperFunctions.sol
- Reuses a new `addFillResults` function in all versions of `marketFillOrders`
- Adds comments for clarity 
=> Use addFillResults function and add comments to all marketFill functions

packages/0x.js/CHANGELOG.json, packages/0x.js/src/contract_wrappers/exchange_wrapper.ts, packages/0x.js/src/fetchers/simple_balance_and_proxy_allowance_fetcher.ts, packages/0x.js/src/fetchers/simple_order_filled_cancelled_fetcher.ts, packages/0x.js/src/stores/balance_proxy_allowance_lazy_store.ts, packages/0x.js/src/stores/order_filled_cancelled_lazy_store.ts, packages/0x.js/src/utils/order_state_utils.ts
=> Fix linter and prettier on development

packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol
Adds the `preSigned` signature type and replaces https://github.com/0xProject/0x-monorepo/pull/414 (easier to make a new PR than to rebase :) )
=> Add presigned signature type

packages/monorepo-scripts/README.md, packages/monorepo-scripts/package.json, packages/monorepo-scripts/src/constants.ts, packages/monorepo-scripts/src/postpublish_utils.ts, packages/monorepo-scripts/src/publish.ts, packages/monorepo-scripts/src/remove_tags.ts, packages/monorepo-scripts/src/utils.ts
This PR:
- Adds a new script that removes all the git tags created by a failed `lerna publish`. Unfortunately this command is not idempotent. 
- Adds checks to make sure a dev running our publish script has the requisite local setup to do so successfully. 
- Adds descriptions about each available script to the README.
Manually.
*   [ ] Labeled this PR …
=> Improve Monorepo-scripts

packages/contracts/src/contracts/current/protocol/Exchange/Exchange.sol, packages/contracts/src/contracts/current/protocol/Exchange/LibOrder.sol, packages/contracts/src/contracts/current/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/contracts/current/protocol/Exchange/MixinTransactions.sol, packages/contracts/src/contracts/current/protocol/Exchange/MixinWrapperFunctions.sol, packages/contracts/src/contracts/current/protocol/Exchange/mixins/MTransactions.sol, packages/contracts/src/utils/crypto.ts, packages/contracts/src/utils/exchange_wrapper.ts, packages/contracts/src/utils/order_factory.ts, packages/contracts/src/utils/order_utils.ts, packages/contracts/src/utils/transaction_factory.ts, packages/contracts/src/utils/types.ts, packages/contracts/test/exchange/transactions.ts
Implements sender abstraction in its simplest form (ZEIP #18)
Need to add more tests.
=> Sender abstraction

packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/types.ts, packages/website/ts/utils/backend_client.ts, packages/website/ts/utils/configs.ts, packages/website/ts/utils/fetch_utils.ts, yarn.lock
Query our backend service by symbol instead of token address
Coin market cap API does not have address information
Manually
=> Grab wallet price information by token symbol

packages/contracts/src/contracts/current/protocol/AssetProxy/IAssetProxy.sol, packages/contracts/src/contracts/current/protocol/AssetProxy/MixinAssetProxy.sol, packages/contracts/src/contracts/current/protocol/AssetProxy/mixins/MAssetProxy.sol, packages/contracts/src/contracts/current/protocol/AssetProxy/proxies/ERC20Proxy.sol, packages/contracts/src/contracts/current/protocol/AssetProxy/proxies/ERC721Proxy.sol, packages/contracts/test/asset_proxy/proxies.ts
Adds a `batchTransferFrom` function in each asset proxy. While this isn't actually used today, it opens doors to batch call `transferFrom` in the future, which could significantly decrease gas costs.
=> Batch transfers in proxies

packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/relayer_index/relayer_index.tsx, packages/website/ts/containers/portal.ts, packages/website/ts/index.tsx
Combines the `Wallet` and `RelayerIndex` components into the new `Portal` component
N/A
Manually
=> Add new top-level portal component with wallet and relayer index layout

packages/website/ts/components/legacy_portal/legacy_portal.tsx, packages/website/ts/components/legacy_portal/legacy_portal_menu.tsx, packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/wallet/wallet.tsx
Add token flow for the wallet. Also removes wallet and relayer entries in the legacy portal
N/A
Manually
=> Portal v2 add tokens flow

packages/website/ts/components/relayer_index/relayer_grid_tile.tsx, packages/website/ts/components/relayer_index/relayer_top_tokens.tsx, packages/website/ts/types.ts
Replace hard coded tokens with top tokens
N/A
Manually
=> Display top tokens from backend

packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/wallet/wallet.tsx
Added the ability to remove tracked tokens from the wallet.
N/A
Manually.
=> Update wallet footer and add remove token functionality

.circleci/config.yml, README.md, package.json, packages/0x.js/package.json, packages/abi-gen/package.json, packages/assert/package.json, packages/base-contract/package.json, packages/connect/package.json, packages/contracts/package.json, packages/dev-utils/package.json, packages/json-schemas/package.json, packages/metacoin/package.json, packages/migrations/package.json, packages/monorepo-scripts/package.json, packages/order-utils/package.json, packages/react-docs-example/package.json, packages/react-docs/package.json, packages/react-shared/package.json, packages/sol-compiler/package.json, packages/sol-cov/package.json, packages/sol-resolver/package.json, packages/sra-report/package.json, packages/subproviders/package.json, packages/testnet-faucets/package.json, packages/tslint-config/package.json, packages/types/package.json, packages/typescript-typings/package.json, packages/utils/package.json, packages/web3-wrapper/package.json, packages/website/package.json
Most packages don't specify the Node version they need in __package.json__ so I added it to any that were missing. I also added a note to the README.
Some packages asked for version >= 6.0. After speaking with Fabio and Leonid, we decided to set our Node version to the latest LTS release, which is Node 8. I'm open to keeping it on Node 6 if we need to for some reason.
Historically, I've experienced problems with different team members using different versions of Node. To pre-empt these problems, it is a good idea to specify the Node version we are using up front so that our team, as well as any third-parties who use the packages, are on the same page.
I ran all tests with `yarn lerna:test`. Since there are no code changes, there are no new tests to write. We just needed to make sure the …
=> Document Node.js version requirement and add it to package.json

packages/website/ts/utils/backend_client.ts, packages/website/ts/utils/configs.ts, packages/website/ts/utils/utils.ts
There was a circular dependency which was causing the site to crash occasionally. This diff fixes that with a slight refactor.
We don't like crashes.
The site loads now!
=> Fix circular dependency

packages/website/ts/components/inputs/balance_bounded_input.tsx, packages/website/ts/components/inputs/eth_amount_input.tsx, packages/website/ts/components/inputs/token_amount_input.tsx, packages/website/ts/components/wallet/wrap_ether_item.tsx, packages/website/ts/pages/about/about.tsx, packages/website/ts/types.ts, packages/website/ts/utils/utils.ts
Show error messages for the wrapping inputs in the wallet. Also some minor style tweaks. 
Couldn't decide if should back-pack the error message onto the "onChange" handler which somehow is also informing whether the input is valid?
We need to show error messages!
Manually!
=> Show error messages in the wrapped ether item

packages/react-shared/CHANGELOG.json, packages/react-shared/src/utils/colors.ts, packages/website/ts/components/inputs/allowance_toggle.tsx, packages/website/ts/components/portal/back_button.tsx, packages/website/ts/components/portal/drawer_menu.tsx, packages/website/ts/components/portal/menu.tsx, packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/relayer_index/relayer_grid_tile.tsx, packages/website/ts/components/relayer_index/relayer_index.tsx, packages/website/ts/components/relayer_index/relayer_top_tokens.tsx, packages/website/ts/components/top_bar/provider_display.tsx, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/components/wallet/wallet_disconnected_item.tsx, packages/website/ts/components/wallet/wrap_ether_item.tsx, packages/website/ts/index.tsx, packages/website/ts/utils/colors.ts, packages/website/ts/utils/utils.ts, packages/website/ts/utils/wallet_item_styles.ts
* Move app specific colors out of `react-shared` and into the website package
* Consolidate `shouldShowPortalV2` logic into utils
* Redesign the drawer menu for portal v2
* Modulate the number of columns displayed in the `RelayerIndex` component based on screen width
* Switch between different layouts in the Portal component based on screen width
* Fix a missing key error in `TokenLink` component
If you're not mobile first, you're mobile last.
Manually
*   [x] Added new entries to …
=> Mobile optimize the portal layout

packages/connect/src/types.ts
Corrects the documentation for `WebSocketOrderbookChannelConfig` for `heartbeatInterval` to `heartbeatIntervalMs`.
More accurate documentation.
No.
*   [X] Bug fix (non-breaking change which fixes an issue)
*   [X] Change requires a change to the documentation.
=> Correct documentation variable name

packages/sra-report/package.json, packages/sra-report/src/postman_environment_factory.ts
=> Remove 0x.js dependency from sra-report

packages/sol-compiler/src/cli.ts, packages/website/package.json, packages/website/ts/blockchain.ts, packages/website/ts/components/dialogs/eth_weth_conversion_dialog.tsx, packages/website/ts/components/dialogs/ledger_config_dialog.tsx, packages/website/ts/components/eth_weth_conversion_button.tsx, packages/website/ts/components/eth_wrappers.tsx, packages/website/ts/components/fill_order.tsx, packages/website/ts/components/fill_order_json.tsx, packages/website/ts/components/flash_messages/token_send_completed.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/inputs/eth_amount_input.tsx, packages/website/ts/components/inputs/hash_input.tsx, packages/website/ts/components/inputs/token_amount_input.tsx, packages/website/ts/components/order_json.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/top_bar/provider_display.tsx, packages/website/ts/components/trade_history/trade_history_item.tsx, packages/website/ts/components/visual_order.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/components/wallet/wrap_ether_item.tsx, packages/website/ts/containers/generate_order_form.ts, packages/website/ts/redux/dispatcher.ts, packages/website/ts/redux/reducer.ts, packages/website/ts/types.ts, packages/website/ts/utils/utils.ts
=> Remove 0x.js as a dependency from website

.prettierignore
=> Ignore v2 artifacts

.circleci/config.yml, packages/contracts/package.json
=> Disable contracts coverage on CI

packages/website/ts/components/onboarding/onboarding_flow.tsx, packages/website/ts/components/onboarding/onboarding_tooltip.tsx, packages/website/ts/components/onboarding/portal_onboarding_flow.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/containers/portal_onboarding_flow.ts, packages/website/ts/utils/constants.ts, packages/website/ts/utils/utils.ts
Mostly added 2 steps, one for adding ETH and one for adding WETH. 
The adding ETH step was easy to implement as there is an user eth balance in the store. 
The logic for the WETH step will not be 100% completed in this PR because I need to refactor wallet.tsx first. 
More generally, I added the 'Continue Button' concept, and am making the tooltip target specific rows in the wallet for the ETH and WETH steps.
Manual
*   [ ] …
=> Onboarding: implement add ETH step, and stub for add WETH step

.circleci/config.yml, package.json, yarn.lock
Rebalance CI tests to run faster
Upgrade to a newer node version to get a faster new yarn version
Create just 4 groups of tests because we have 4 machines on CI
=> Rebalance CI tests to run faster

packages/website/ts/blockchain_watcher.ts, packages/website/ts/components/eth_weth_conversion_button.tsx, packages/website/ts/components/eth_wrappers.tsx, packages/website/ts/components/legacy_portal/legacy_portal.tsx, packages/website/ts/components/onboarding/portal_onboarding_flow.tsx, packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/top_bar/provider_display.tsx, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/components/wallet/wallet_disconnected_item.tsx, packages/website/ts/containers/legacy_portal.ts, packages/website/ts/containers/portal.ts, packages/website/ts/containers/portal_onboarding_flow.ts, packages/website/ts/redux/dispatcher.ts, packages/website/ts/redux/reducer.ts
* Loading state for `ProviderDisplay` component in the top right
* Loading state for `Wallet` component
* Loading state for balances within `Wallet`
More spinners, more problems
Manually.
*   [x] Added new entries to the relevant CHANGELOG.jsons.
=> Add loading states to wallet and provider display

packages/website/ts/components/legacy_portal/legacy_portal.tsx, packages/website/ts/components/portal/menu.tsx, packages/website/ts/components/portal/portal.tsx, packages/website/ts/utils/order_parser.ts
Add support for passing orders as a query param .
Features that are present in legacy portal should be supported in the new portal.
Build and try this link: https://localhost:3572/portal/fill?order={%22signedOrder%22:{%22maker%22:%220x14e2f1f157e7dd4057d02817436d628a37120fd1%22,%22taker%22:%220x0000000000000000000000000000000000000000%22,%22makerFee%22:%220%22,%22takerFee%22:%220%22,%22makerTokenAmount%22:%22100000000000000000%22,%22takerTokenAmount%22:%22100000000000000000%22,%22makerTokenAddress%22:%220xd0a1e359811322d97991e03f863a0c30c2cf029c%22,%22takerTokenAddress%22:%220x6ff6c0ff1d68b964901f986d4c9fa3ac68346570%22,%22expirationUnixTimestampSec%22:%222524636800%22,%22feeRecipient%22:%220x0000000000000000000000000000000000000000%22,%22salt%22:%223729388640488766414530793849304185181521 …
=> Add shared order support

packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/wallet/wallet.tsx
During a recent refactor we missed price fetching functionality from the wallet
=> Move price fetching from wallet into portal

packages/website/ts/components/dialogs/eth_weth_conversion_dialog.tsx, packages/website/ts/components/eth_weth_conversion_button.tsx, packages/website/ts/components/eth_wrappers.tsx, packages/website/ts/components/fill_order.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/trade_history/trade_history.tsx, packages/website/ts/containers/generate_order_form.ts
- Makes a number of changes to the "manage your wallet" section of portal to tidy it up visiually
- Fix an error when navigating directly to `/portal/weth` and the user's ether balance has not loaded yet
=> Account management polish

packages/contracts/test/exchange/transactions.ts, packages/contracts/test/zrx_token.ts
This PR fixes a race condition that causes tests to fail in https://github.com/0xProject/0x-monorepo/pull/674.
=> Add missing awaitTransactionSuccessAsync calls

.circleci/config.yml, packages/devnet/run.sh
This PR updates __.circleci/config.yaml__ to run tests against Geth. This also required redistributing some of our existing tests in that configuration file.
=> Run contracts tests against Geth in CI

packages/sol-compiler/src/schemas/compiler_options_schema.ts, packages/sol-cov/CHANGELOG.json, packages/sol-cov/src/artifact_adapters/sol_compiler_artifact_adapter.ts, packages/sol-cov/src/trace_collection_subprovider.ts
A bunch of fixes discovered while integrating sol-cov with openzeppelin-solidity.
BTW, it works.
* Don't throw if config file is not there.
* Fix the solidity version regex
* Speed-up sol-cov transaction awaiting
Manually
=> Sol-cov fixes

packages/metacoin/README.md, packages/metacoin/package.json, packages/metacoin/test/global_hooks.ts, packages/metacoin/test/metacoin_test.ts, packages/metacoin/test/utils/profiler.ts, packages/metacoin/test/utils/web3_wrapper.ts
This PR adds a README for metacoin project.
It also adds profiling capabilities to it and tests running against geth.
To have a small, well-documented example.
Manually & tests.
*   [x] Change requires a change to the documentation.
*   [x] Added tests to cover my changes.
*   [x] Added new entries to the relevant CHANGELOG.jsons.
=> Add profiler and geth tests to metacoin

packages/contracts/src/contracts/current/protocol/AssetProxy/ERC20Proxy.sol
See title.
Still needs test coverage.
=> [discussion] Handle tokens that do not return bool

packages/web3-wrapper/src/web3_wrapper.ts, yarn.lock
Porting over a change that was made in development branch to improve JSON-RPC compatibility.
=> Fix sendRawPaylodAsync for improved JSON-RPC compatibility

packages/contracts/src/contracts/current/utils/LibMem/LibMem.sol
=> Simplified handling of source < 32 edge case

packages/fill-scenarios/CHANGELOG.json, packages/order-utils/CHANGELOG.json, packages/sol-cov/CHANGELOG.json, packages/sol-resolver/CHANGELOG.json, packages/utils/CHANGELOG.json
=> Fix CHANGELOG entries changed during incorrect merge (2a4456b)

packages/sol-cov/CHANGELOG.json, packages/sol-cov/package.json, packages/sol-cov/src/ast_visitor.ts, packages/sol-cov/src/get_source_range_snippet.ts, packages/sol-cov/src/revert_trace_subprovider.ts, packages/sol-cov/src/types.ts, packages/sol-cov/src/utils.ts, packages/sol-cov/test/collect_coverage_entries_test.ts, yarn.lock
This PR improves the `RevertTraceSubprovider` by adding relevant source code snippets to the stack trace. This makes it much easier to follow the stack trace at a glance. Here's an example:
=> Include source code snippets in revert stack traces

packages/website/ts/components/portal/back_button.tsx, packages/website/ts/components/top_bar/provider_display.tsx, packages/website/ts/components/ui/island.tsx, packages/website/ts/style/colors.ts
* Updated the dropshadow styling we use across portal
* Used the `Island` component in come places where we should be
* Go to /portal
* Verify that the shadow looks as designed
=> Update Island shadow styling and use Island in more places

packages/website/ts/pages/about/about.tsx, packages/website/ts/pages/about/profile.tsx
Also removed some unnecessary margin.
=> Add Chris and Mel to about page

packages/contracts/compiler.json, packages/contracts/package.json, packages/contracts/src/contracts/current/protocol/AssetProxyOwner/AssetProxyOwner.sol, packages/contracts/src/contracts/current/test/TestAssetProxyOwner/TestAssetProxyOwner.sol, packages/contracts/src/utils/artifacts.ts, packages/contracts/src/utils/multi_sig_wrapper.ts, packages/contracts/test/asset_proxy_owner.ts, packages/contracts/test/libraries/lib_bytes.ts
- Allows `AssetProxyOwner` to execute `removeAuthorizedAddressAtIndex` without a timelock instead of `removeAuthorizedAddress`.
- Creates `TestAssetProxyOwner` to test the `validRemoveAuthorizedAddressAtIndexTx`
- Adds/updates tests
=> Update AssetProxyOwner + tests

packages/contracts/src/contracts/current/protocol/AssetProxy/MixinERC721Transfer.sol, packages/contracts/src/contracts/current/protocol/Exchange/MixinAssetProxyDispatcher.sol, packages/contracts/src/contracts/current/protocol/Exchange/libs/LibExchangeErrors.sol
Adds an explicit check to see if AssetProxy exists before attempting a transfer.
=> Check that assetProxy exists before attempting transfer

packages/website/ts/components/generate_order/asset_picker.tsx, packages/website/ts/redux/reducer.ts
* Prevent empty tokens from being written to local storage
* Fix state mutations in reducer
* Try to add a token to your wallet 
=> Various add token flow bugs

packages/metacoin/package.json, packages/metacoin/tsconfig.json
Added missing dependencies to metacoin/package.json, and edited metacoin/tsconfig.json to not depend on ../../tsconfig.json.
I think if Metacoin is to serve as a good example, it should be easy to build it outside of the monorepo yarn workspace environment.  Unfortunately, [due to the limitations of yarn workspaces, yarn does not support warning that dependencies in a workspace package are not listed in that package's package.json](https://yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats).  When metacoin is built within the monorepo workspace environment, yarn will pick up dependencies installed by other packages, even if they're not mentioned in metacoin's package.json.  This leads to metacoin being an incomplete example as missing dependencies go unnoticed in the build of …
=> Metacoin independence

package.json, packages/subproviders/package.json, packages/testnet-faucets/package.json, yarn.lock
Since https://github.com/ethereumjs/ethereumjs-tx/pull/97 was merged, we can use the official version instead of relying on our fork.
If the tests pass in CI, that should be sufficient.
=> Use ethereumjs-tx@1.3.5 instead of our fork

packages/migrations/src/v2/migration.ts
=> Register the asset proxies to exchange

packages/contracts/src/contracts/current/protocol/Exchange/MixinTransactions.sol, packages/contracts/src/contracts/current/protocol/Exchange/libs/LibOrder.sol
=> Added some comments for ASM hashing

packages/0x.js/package.json, packages/abi-gen/package.json, packages/base-contract/package.json, packages/contract-wrappers/package.json, packages/contracts/package.json, packages/dev-utils/package.json, packages/ethereum-types/package.json, packages/fill-scenarios/CHANGELOG.json, packages/fill-scenarios/package.json, packages/json-schemas/CHANGELOG.json, packages/migrations/package.json, packages/monorepo-scripts/CHANGELOG.json, packages/monorepo-scripts/src/prepublish_checks.ts, packages/monorepo-scripts/src/utils/utils.ts, packages/order-utils/CHANGELOG.json, packages/order-utils/package.json, packages/order-watcher/package.json, packages/sol-compiler/package.json, packages/sol-cov/package.json, packages/subproviders/package.json, packages/testnet-faucets/package.json, packages/types/CHANGELOG.json, packages/types/package.json, packages/typescript-typings/package.json, packages/utils/CHANGELOG.json, packages/utils/package.json, packages/web3-wrapper/package.json, yarn.lock
Makes some small publish fixes:
- Don't  throw if `git` commands return something on `stderr`. They use it for logging non-errors.
- Throw if CHANGELOG version is below Package.json version.
It also updates outdated CHANGELOGS found.
*   [x] Added new entries to the relevant CHANGELOG.jsons.
=> Small publish fixes

packages/subproviders/package.json
It seems that the `circleci:submit-coverage` check always fails when run for a PR that's based on a fork rather than a branch.  I'm trying to figure out what configuration a user must do in order for the coverage check to work on a fork.  I'm using this PR as a way to force CI builds, rather than causing a bunch of noise by doing it on my other non-dummy PR's.
None!
*   [X] Labeled this PR with the 'WIP' label if it is a work in progress.
=> [WIP] dummy PR, for forcing CI builds, to investigate coverage failures on forks

packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/package.json, packages/contract-wrappers/src/contract_wrappers/contract_wrapper.ts, packages/dev-utils/package.json, packages/metacoin/package.json, packages/migrations/package.json, packages/subproviders/package.json, packages/testnet-faucets/package.json, packages/website/package.json, yarn.lock
Replaces: https://github.com/0xProject/0x-monorepo/pull/756/files.
Some important fixes were released by these two dependencies of ours.
=> Update Blockstream & ProviderEngine

packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/components/top_bar/top_bar_menu_item.tsx, packages/website/ts/components/wallet/wallet.tsx
* Removed "0x Relayers" and "Your" account headers in mobile
* Decreased margins on mobile
* Reworked the top bar to use flex box for centering instead of hard coded padding
* Removed a couple of options from the wallet menu that aren't relevant to mobile
=> Various mobile portal fixes and top bar layout refactor

packages/website/translations/english.json, packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/components/top_bar/top_bar_menu_item.tsx, packages/website/ts/components/ui/button.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/pages/landing/landing.tsx, packages/website/ts/types.ts, packages/website/ts/utils/translate.ts
* Update look and feel for Portal cta on the landing page
* Update translation logic to fallback to english if translation unavilable
* Unify different paddings we have in portal
* Expand interface of the `Button` component
* Update styling of the "what's new" section of the landing page
* Force users to click to dismiss menu in the wallet, this is more in line with other websites (ex. options menu on a status on the facebook news feed)
* Look through the landing page
* Try to switch between different translations
*   [ ] …
=> Landing page CTA for portal

packages/sol-compiler/README.md, packages/web3-wrapper/README.md, packages/website/md/docs/sol-compiler/introduction.md, packages/website/md/docs/web3_wrapper/introduction.md
Needed updates to these package descriptions.
=> Update Package Descriptions

packages/website/ts/blockchain.ts, packages/website/ts/components/dialogs/ledger_config_dialog.tsx, packages/website/ts/components/onboarding/onboarding_flow.tsx, packages/website/ts/components/onboarding/portal_onboarding_flow.tsx, packages/website/ts/components/wallet/wallet.tsx, packages/website/ts/types.ts
This change addresses some small issues with Portal, as well as change our gas price polling set-up. Right now we just use the "average" gas price found on page-load, but it would be more ideal to poll that value and to use "fast" since it is hard to ask your users to go through onboarding steps with 5 minute waiting times.
1. Make sure no more annoying onboarding closes happen when you use Firefox.
2. Make sure that ledger dialog always shows a default network.
3. Make sure that the gas price being used allows for transactions to go through in a timely manner (and that it is being updated).
*   [ ] Breaking change (fix or feature that would cause existing …
=> Fix some portal bugs, and poll for best gas price

packages/contracts/package.json, packages/contracts/src/2.0.0/forwarder/MixinERC20.sol, packages/contracts/src/2.0.0/forwarder/MixinWethFees.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/ERC20Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/ERC721Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/MixinAuthorizable.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/interfaces/IAssetProxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/interfaces/IAuthorizable.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/mixins/MAuthorizable.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinSignatureValidator.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinTransactions.sol, packages/contracts/src/2.0.0/protocol/Exchange/interfaces/IMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/interfaces/IWrapperFunctions.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibOrder.sol, packages/contracts/src/2.0.0/protocol/Exchange/mixins/MAssetProxyDispatcher.sol, packages/contracts/src/2.0.0/test/DummyERC20Token/DummyERC20Token.sol, packages/contracts/src/2.0.0/test/DummyERC721Token/DummyERC721Token.sol, packages/contracts/src/2.0.0/test/Mintable/Mintable.sol, packages/contracts/src/2.0.0/test/TestAssetProxyDispatcher/TestAssetProxyDispatcher.sol, packages/contracts/src/2.0.0/test/TestLibBytes/TestLibBytes.sol, packages/contracts/src/2.0.0/test/TestLibs/TestLibs.sol, packages/contracts/src/2.0.0/test/TestSignatureValidator/TestSignatureValidator.sol, packages/contracts/src/2.0.0/tokens/ERC20Token/ERC20Token.sol, packages/contracts/src/2.0.0/tokens/ERC20Token/IERC20Token.sol, packages/contracts/src/2.0.0/tokens/UnlimitedAllowanceToken/UnlimitedAllowanceToken.sol, packages/contracts/src/2.0.0/utils/Ownable/IOwnable.sol, packages/contracts/src/2.0.0/utils/Ownable/Ownable.sol, packages/contracts/src/2.0.0/utils/SafeMath/SafeMath.sol
- Removes use of ABIEncoderV2 where not necessary (saves ~2k gas per fill!)
- Removes TODOs that won't be addressed
- Small optimization and style changes
One main TODO that is worth discussing is how much gas to forward in `fillOrderNoThrow`. Old contracts that use `assert` or `throw` over `require` or `revert` will still consume 63/64 of the entire gas, which means that any logic after the first failure will probably not be executed. There probably isn't a whole lot we can do here other than hard coding an upper bound of gas to forward, but it is worth thinking about.
*   [ …
=> Address TODOs and small fixes

CONTRIBUTING.md
Addresses: #823 
Explains how to get test coverage checks working on a fork of 0xProject/0x-monorepo.
Follow the directions :)
Addition to CONTRIBUTING.md
*   [X] Bug fix (non-breaking change which fixes an issue)
=> document how to check test coverage on a fork

packages/contract-wrappers/test/ether_token_wrapper_test.ts, packages/contracts/src/1.0.0/MultiSigWalletWithTImeLockExceptRemoveAuthorizedAddress/MultiSigWalletWithTimeLockExceptRemoveAuthorizedAddress.sol, packages/contracts/src/2.0.0/forwarder/Forwarder.sol, packages/contracts/test/forwarder/forwarder.ts, packages/migrations/artifacts/2.0.0/Forwarder.json, packages/migrations/compiler.json, packages/migrations/src/2.0.0/migration.ts
- Fixes MultiSigWithTimeLock pointing to old current file structure
- update compiler.json to point to new contract base directory
- Remove redundant constructor argument in Forwarder
- Adds Forwarder to Migrations
=> Add Migrations for Forwarder and miscellaneous fixes

packages/website/package.json, packages/website/ts/blockchain.ts, packages/website/ts/components/eth_weth_conversion_button.tsx, packages/website/ts/components/fill_order.tsx, packages/website/ts/components/generate_order/generate_order_form.tsx, packages/website/ts/components/inputs/allowance_toggle.tsx, packages/website/ts/components/order_json.tsx, packages/website/ts/components/send_button.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/wallet/wrap_ether_item.tsx, packages/website/ts/types.ts, packages/website/ts/utils/configs.ts, packages/website/ts/utils/error_reporter.ts, packages/website/ts/utils/fetch_utils.ts, packages/website/ts/utils/utils.ts, packages/website/webpack.config.js, yarn.lock
Only upload sourcemaps to rollbar on live deploys, and log NaN error for future debugging
`yarn build` should not upload sourcemaps, `yarn deploy_live` should.
=> Only upload sourcemaps to rollbar on live deploys, and handle NaN error by using 0

packages/website/ts/components/onboarding/portal_onboarding_flow.tsx, packages/website/ts/redux/analyticsMiddleware.ts
Just did some more Heap debugging. This seemed to be the only issue: we don't want to be logging 'Update Onboarding Step' from the analytics middleware since that is modifying a bunch automatically by the "adjust step" logic. We really just want to hook into it when the user completes an action.
*   [x] Labeled this PR with the labels corresponding to …
=> Move update onboarding step tracking to onboarding flow code

packages/0x.js/CHANGELOG.json, packages/contract-wrappers/src/contract_wrappers/contract_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/erc20_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/erc721_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/ether_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts, packages/contract-wrappers/test/subscription_test.ts, packages/order-watcher/CHANGELOG.json, packages/order-watcher/src/order_watcher/event_watcher.ts, packages/order-watcher/src/order_watcher/order_watcher.ts, packages/order-watcher/src/types.ts, yarn.lock
This PR:
- Removes the bound parameters on the callbacks passed into `BlockAndLogStreamer`. It calls these methods with it's own parameters.
- Allow the user to configure the `blockRetention` config passed to `BlockAndLogStreamer` since users might have different memory resources available to them. 
Run all the tests.
*   [x] Added new entries to the relevant CHANGELOG.jsons.
*   [ ] Labeled this PR with the …
=> OrderWatcher Fixes

packages/abi-gen/CHANGELOG.json, packages/abi-gen/bin/abi-gen.js, packages/abi-gen/package.json
=> Fix the abi-gen entry point

packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibAbiEncoder.sol
Moved this code into a separate library so it can be used by the forwarding contract.
All existing tests pass.
=> Created LibAbiEncoder with `fillOrderNoThrow`

packages/website/ts/blockchain.ts, packages/website/ts/components/dialogs/eth_weth_conversion_dialog.tsx, packages/website/ts/components/dialogs/send_dialog.tsx, packages/website/ts/components/flash_messages/asset_send_completed.tsx, packages/website/ts/components/inputs/eth_amount_input.tsx, packages/website/ts/components/send_button.tsx, packages/website/ts/components/token_balances.tsx, packages/website/ts/components/wallet/wrap_ether_item.tsx, packages/website/ts/containers/inputs/eth_amount_input.ts
The Send ether button in this picture is new. 
=> Send Ether from Portal

packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/pages/wiki/wiki.tsx
=> Make topbar zIndex 1

packages/contract-wrappers/package.json, packages/contract-wrappers/src/artifacts.ts, packages/contract-wrappers/src/contract_wrappers.ts, packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/forwarder_wrapper.ts, packages/contract-wrappers/src/index.ts, packages/contract-wrappers/src/types.ts, packages/contract-wrappers/src/utils/assert.ts, packages/contract-wrappers/src/utils/constants.ts, packages/contract-wrappers/test/exchange_wrapper_test.ts, packages/contract-wrappers/test/forwarder_wrapper_test.ts
* Adds a new `ForwarderWrapper` class to the `contract-wrappers` package
* Only implements the `marketSellOrdersWithEthAsync` and `marketBuyOrdersWithEthAsync` transactions
* Provides many assertions for type safety and correct orders
* Adds the `getOrdersInfoAsync` method to `ExchangeWrapper` with accompanying test
* Convenience / utility methods for calculating how much ETH to send with the `marketBuyOrdersWithEthAsync` tx in order to cover the required `makerAssetFillAmount`
* Possible make the `ethAmount` parameter optional and use the convenience methods to estimate by default
* More assertions (do orders provided cover the specified makerAssetFillAmount, do the fee orders cover the required fees, are the order funded?)
* make sure fee percentage is the correct format
* order …
=> Initial forwarder contract wrapper

packages/contracts/src/2.0.0/protocol/Exchange/MixinTransactions.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibEIP712.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibOrder.sol
- Fixes some misleading and unclear comments/styling
- Adds small optimization + readability improvement to `hashOrder`
=> [contracts] Fix comments, styling and small optimization for hashOrder

packages/contracts/src/2.0.0/protocol/Exchange/MixinSignatureValidator.sol
=> [contracts] Fix comments and styling for MixinSignatureValidator

PULL_REQUEST_TEMPLATE.md
*   [x] Prefixed the title of this PR with `[WIP]` if it is a work in progress.
*   [x] Prefixed the title of this PR with bracketed package name(s) corresponding to the changed package(s). For example: `[sol-cov] Fixed bug`.
*   [x] Added tests to cover my changes, or decided that tests would be too impractical.
*   [x] Updated documentation, or decided that no doc change is needed.
=> [PR template] a to-do list should be in the imperative mood

.circleci/config.yml, package.json, packages/monorepo-scripts/package.json, packages/monorepo-scripts/src/test_installation.ts, yarn.lock
This PR allows us to run the __test_installation.ts__ script in CircleCI. This required first spinning up an instance of Verdaccio (a private NPM registry) in a Docker container.
=> Run publish/installation tests in CircleCI

package.json, yarn.lock
This PR updates the version of (our fork of) lerna to take advantage of https://github.com/0xProject/lerna/pull/2. With this new feature, lerna will automatically add 'beta' tags to npm when it detects a release candidate version.
=> feat: Update lerna to version 3.0.0-beta.25 of our fork

packages/contracts/src/2.0.0/forwarder/Forwarder.sol, packages/contracts/src/2.0.0/forwarder/libs/LibConstants.sol, packages/contracts/test/forwarder/forwarder.ts, packages/migrations/src/2.0.0/migration.ts
=> [contracts] Remove redundant constructor args

package.json
`test:publish:circleci` sometimes fails with an error message that looks like this:
```
{ echo "test"; sleep 1; echo "test"; sleep 1; echo "test@example.com"; } | npm login --registry=http://localhost:4873 && IS_LOCAL_PUBLISH=true run-s script:publish test:installation:local
Username: test
Password: npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
Hopefully increasing the time delay will prevent this issue.
This is meant to fix an issue that occurs non-deterministically in CI. We'll just have to monitor the situation over time.
*   [ ] Prefix PR title with bracketed package name(s) …
=> fix: Increase delay for non-interactive npm login

packages/website/md/docs/connect/2.0.0/introduction.md, packages/website/ts/containers/connect_documentation.ts
Just a small documentation addition for connect v2 when it is released.
=> [website] Add documentation for connect v2

packages/migrations/artifacts/2.0.0-beta-testnet/OrderValidator.json
* Add entry for network 50 in the `OrderValidator.json` artifact
N/A
=> [migrations] Add testnet network info to OrderValidator artifact

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/mixins/MExchangeCore.sol, packages/types/src/index.ts
=> [WIP] Split order assertion function in two

packages/contracts/src/2.0.0/protocol/Exchange/MixinAssetProxyDispatcher.sol
=> [Contracts] Skip self transfers

packages/contracts/src/2.0.0/extensions/Forwarder/MixinExchangeWrapper.sol, packages/contracts/src/2.0.0/extensions/Forwarder/MixinForwarderCore.sol, packages/contracts/src/2.0.0/extensions/Forwarder/MixinWeth.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibMath.sol, packages/contracts/src/2.0.0/test/TestExchangeInternals/TestExchangeInternals.sol, packages/contracts/src/2.0.0/test/TestLibs/TestLibs.sol, packages/contracts/test/exchange/internal.ts, packages/contracts/test/exchange/libs.ts, packages/contracts/test/utils/fill_order_combinatorial_utils.ts, packages/contracts/test/utils/order_utils.ts, packages/order-utils/src/order_state_utils.ts, packages/order-utils/src/order_validation_utils.ts, packages/order-utils/src/utils.ts, packages/order-utils/test/order_validation_utils_test.ts, packages/types/src/index.ts
**Includes:** #1005.
* Adds `getPartialAmountCeil` and `isRoundingErrorCeil` that round up instead of down.
* Add `DIVISION_BY_ZERO` error to new and existing functions.
* Update/add test coverage.
Added test coverages. Added tests have merge conflicts with PR #1000.
=> [contracts] Add getPartialAmountCeil and isRoundingErrorCeil

packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/test/exchange/match_orders.ts, packages/contracts/test/utils/match_order_tester.ts, packages/contracts/test/utils/types.ts
Changes to Order Matching Implementation:
The algorithm is now written out fully within `calculateMatchedFillResults`. 
Changes to Order Matching Tests:
1. Test author must compute the expected transfer amounts by hand
2. These expected amounts are tested against logs+return values, exchange state, and balances
3. Assertions are more granular to provide better feedback to test authors
4. Additional edge case tests were added
=> Robustness in Order Matching

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/mixins/MExchangeCore.sol, packages/types/src/index.ts
Add assertions to `assertValidFill` that catch bugs in contracts that would result in loss of funds.
**Note** One of the added assertions is `maker != taker`. This requires two tests to be removed from match orders where taker is left or right maker.
=> Add more assertions to assertValidFill

.circleci/config.yml
=> fix: Use yarn version 1.9.4 on CI

packages/contracts/src/2.0.0/extensions/Forwarder/MixinExchangeWrapper.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol
=> Remove redundant mstores from fillOrderNoThrow

packages/contracts/test/utils/test_with_reference.ts, packages/contracts/test/utils_test/test_with_reference.ts
This PR fixes a bug in `testWithReferenceFuncAsync` which can result in false positives (tests which pass but should have failed). See https://github.com/0xProject/0x-monorepo/pull/1000 for more information about the bug. Portions of the code here are borrowed from https://github.com/0xProject/0x-monorepo/pull/1000.
In https://github.com/0xProject/0x-monorepo/pull/1000 @Recmo was working on a larger refactor of our contracts tests in order to address this bug (especially around how we handle and compare error messages). There are some good ideas in that PR and it is probably worth continuing to work on refactoring. However, in the interest of time, I'm suggesting that we fix the original bug first and then move on to more extensive refactors.
This PR addresses the bug while not really …
=> Fix false positives in testWithReferenceFuncAsync

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinMatchOrders.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibMath.sol, packages/contracts/src/2.0.0/test/ReentrantERC20Token/ReentrantERC20Token.sol, packages/contracts/src/2.0.0/test/TestExchangeInternals/TestExchangeInternals.sol, packages/contracts/test/exchange/internal.ts, packages/contracts/test/exchange/match_orders.ts
=> safeGetPartialAmount

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/test/exchange/internal.ts
=> Making rounding consistent in calculateFillResults

packages/contracts/src/2.0.0/protocol/AssetProxy/ERC20Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/ERC721Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxyOwner/AssetProxyOwner.sol, packages/contracts/src/2.0.0/utils/LibBytes/LibBytes.sol, packages/contracts/test/libraries/lib_bytes.ts
Fixes for following tasks from audit:
* 3.5 LibBytes: Insufficient Testing
* 3.6 LibBytes: readBytes4 does not adhere to spec
* 3.18 ERC20Proxy: Unclear comments
=> Fixes as-per Audit for LibBytes + ERC20 Proxy Comments

packages/contracts/src/2.0.0/protocol/AssetProxy/ERC20Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxy/ERC721Proxy.sol, packages/contracts/src/2.0.0/protocol/AssetProxyOwner/AssetProxyOwner.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinAssetProxyDispatcher.sol, packages/contracts/src/2.0.0/test/TestAssetProxyOwner/TestAssetProxyOwner.sol, packages/contracts/test/exchange/signature_validator.ts, packages/contracts/test/libraries/lib_bytes.ts, packages/contracts/test/multisig/asset_proxy_owner.ts, packages/contracts/test/tokens/unlimited_allowance_token.ts, packages/contracts/test/utils/assertions.ts, packages/types/CHANGELOG.json, packages/types/src/index.ts
=> Update AssetProxyOwner to 0.4.24, remove redundant code

packages/typescript-typings/types/react-typist/index.d.ts, packages/website/package.json, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/components/ui/button.tsx, packages/website/ts/components/ui/text.tsx, packages/website/ts/components/ui/typed_text.tsx, packages/website/ts/index.tsx, packages/website/ts/pages/landing/landing.tsx, yarn.lock
Try it out on staging. We have a few levers to play with, such as:
How fast does it type (avg time between keystrokes)?
What is the delay between words?
What is the initial delay?
How randomly does it type (ie, what is the std deviation in time between keystrokes)
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/
=> [website] Add rotating text to landing header and careers button to topbar

packages/contracts/compiler.json, packages/contracts/package.json, packages/contracts/src/2.0.0/test/DummyERC20Token/DummyMultipleReturnERC20Token.sol, packages/contracts/test/asset_proxy/authorizable.ts, packages/contracts/test/asset_proxy/proxies.ts, packages/contracts/test/exchange/core.ts, packages/contracts/test/exchange/dispatcher.ts, packages/contracts/test/utils/artifacts.ts
- Adds tests for when `from == to`
- Makes `MixinAuthorizable` tests more robust
- Adds tests for where `assetData` has extra data appended
- Adds tests for ERC20 tokens that return >32 bytes
=> Add edge case tests

packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol, packages/contracts/src/2.0.0/protocol/Exchange/mixins/MExchangeCore.sol, packages/contracts/src/2.0.0/test/ReentrantERC20Token/ReentrantERC20Token.sol, packages/contracts/test/utils/constants.ts
=> Add cancelOrderInternal, use within batchCancelOrders

packages/contracts/test/exchange/match_orders.ts
=> Test cases for rounding fees in matchOrders

packages/contracts/test/exchange/internal.ts, packages/contracts/test/exchange/signature_validator.ts, packages/react-docs/src/docs_info.ts, packages/react-shared/src/components/anchor_title.tsx, packages/tslint-config/tslint.json, packages/website/ts/components/top_bar/top_bar.tsx, packages/website/ts/containers/connect_documentation.ts, packages/website/ts/containers/contract_wrappers_documentation.ts, packages/website/ts/containers/ethereum_types_documentation.ts, packages/website/ts/containers/order_utils_documentation.ts, packages/website/ts/containers/order_watcher_documentation.ts, packages/website/ts/containers/sol_compiler_documentation.ts, packages/website/ts/containers/sol_cov_documentation.ts, packages/website/ts/containers/subproviders_documentation.ts, packages/website/ts/containers/web3_wrapper_documentation.ts, packages/website/ts/containers/zero_ex_js_documentation.ts
I'm not sure why we removed this rule. My guess is because it currently spews out deprecation warnings and recommends to use the compiler options instead. However, turning on the compiler options doesn't really work for us because we need to be able to [selectively not apply this rule to certain files](https://github.com/Microsoft/TypeScript/issues/12913).
It seems that a [lot of people feel this way, so it has been undeprecated](https://github.com/palantir/tslint/pull/2256) so we should go back to using it. We already had a few unused variables lying around.
* …
=> Re-add no-unused-variable tslint rule

packages/website/translations/english.json, packages/website/ts/pages/landing/landing.tsx, yarn.lock
=> [website] Final tweaks for landing page

packages/website/ts/components/ui/typed_text.tsx, packages/website/ts/pages/landing/landing.tsx
Tests are now failing on CI because of those linter issues fixed here.
=> [website] Remove unused imports

packages/contracts/src/2.0.0/extensions/Forwarder/MixinExchangeWrapper.sol, packages/contracts/src/2.0.0/multisig/MultiSigWallet.sol, packages/contracts/src/2.0.0/multisig/MultiSigWalletWithTimeLock.sol, packages/contracts/src/2.0.0/protocol/AssetProxyOwner/AssetProxyOwner.sol, packages/contracts/src/2.0.0/protocol/Exchange/MixinWrapperFunctions.sol, packages/contracts/src/2.0.0/protocol/Exchange/libs/LibMath.sol, packages/contracts/test/multisig/asset_proxy_owner.ts, packages/contracts/test/multisig/multi_sig_with_time_lock.ts, packages/contracts/test/utils/multi_sig_wrapper.ts, packages/types/CHANGELOG.json, packages/types/src/index.ts
- Updates the Gnosis MultiSigWallet to the most [recent version](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol) (with the only difference being that `external_call` is internal instead of private)
- Removes `revokeConfirmation` from `MultiSigWalletWithTimeLock`. This change allows confirmations to be revoked after the confirmation time has been set. Before, you could implicitly delay the execution of a transaction by increasing the number of required owners or increasing the timelock - now there is an explicit way to do so.
- Note that _anyone_ can call `executeTransaction` in `MultiSigWalletWithTimeLock`. This differs from the new behavior of the Gnosis MultiSigWallet.
*   [ ] Prefix PR title with …
=> Update MultiSig and add more tests

packages/connect/CHANGELOG.json, packages/connect/src/http_client.ts, packages/connect/src/types.ts, packages/connect/test/http_client_test.ts
Was writing the connect tutorial and realized that this interface was a bit broken. You should be dealing with `BigNumber`, not numbers that are strings.
Tests pass.
=> [connect] Use BigNumber instead of string where appropriate in OrderConfigRequest

packages/testnet-faucets/package.json, packages/testnet-faucets/src/ts/dispense_asset_tasks.ts, packages/testnet-faucets/src/ts/handler.ts, packages/testnet-faucets/src/ts/rpc_urls.ts, packages/testnet-faucets/src/ts/tokens.ts, yarn.lock
Update the testnet faucet to v2.
Tested on Kovan + Ropsten through filling a generated order via Sandbox. Dispensed via curl.
=> [testnet-faucets] update to v2

.circleci/config.yml
This PR bumps the [`resource_class`](https://circleci.com/docs/2.0/configuration-reference/#resource_class) for two of our CI jobs that were struggling.
Just observe the results of the tests on CircleCI.
=> Bump CircleCI resource class for build and test-publish

packages/0x.js/CHANGELOG.json, packages/contract-wrappers/CHANGELOG.json, packages/migrations/artifacts/2.0.0/WETH9.json, packages/migrations/artifacts/2.0.0/ZRXToken.json, packages/order-watcher/CHANGELOG.json
Fixes: https://github.com/0xProject/0x-monorepo/issues/1065
=> Add missing mainnet addresses to ZRXToken & WETH artifacts

packages/0x.js/package.json, packages/abi-gen/package.json, packages/contract-wrappers/package.json, packages/contracts/package.json, packages/ethereum-types/package.json, packages/forwarder-helper/package.json, packages/json-schemas/package.json, packages/monorepo-scripts/package.json, packages/order-utils/package.json, packages/order-watcher/package.json, packages/react-docs/package.json, packages/react-shared/package.json, packages/sol-cov/package.json, packages/sra-report/package.json, packages/subproviders/package.json, packages/types/package.json, packages/utils/package.json, packages/website/package.json
In order to avoid the situation when some other library depends on the other version of node types and our users end up with two (current state with ethers.js 4.0) we want to be less restrictive here.
=> Don't depend on a specific version of node types

.circleci/config.yml
This PR migrates our Docker images from my personal DockerHub account to our new organization-wide account.
=> Migrate docker images to 0xorg DockerHub account

packages/asset-buyer/src/order_providers/standard_relayer_api_order_provider.ts, packages/connect/CHANGELOG.json, packages/connect/src/http_client.ts, packages/connect/src/index.ts, packages/connect/src/types.ts, packages/connect/src/utils/orders_channel_message_parser.ts, packages/connect/src/utils/relayer_response_json_parsers.ts, packages/connect/src/utils/type_converters.ts, packages/connect/src/ws_orders_channel.ts, packages/connect/test/fixtures/standard_relayer_api/asset_pairs.ts, packages/connect/test/fixtures/standard_relayer_api/fee_recipients.ts, packages/connect/test/fixtures/standard_relayer_api/order_config.ts, packages/connect/test/fixtures/standard_relayer_api/orderbook.ts, packages/connect/test/fixtures/standard_relayer_api/orders.ts, packages/types/CHANGELOG.json, packages/types/src/index.ts, yarn.lock
We want to reuse that types in other places incuding 0x-relayer-template and we need them exported.
Those types and SRA related, not connect related and that's why we created a new package.
It builds
=> [types] Move SRA types from @0xproject/connect to @0xproject/types

packages/sol-doc/bin/sol-doc.js
Fix a few little problems with the new sol-doc stuff that just landed.
Ensure the builds go cleanly (namely test-publish).
=> [sol-doc] fixes

packages/order-watcher/CHANGELOG.json, packages/order-watcher/src/index.ts
I think expiration watcher is usefull enough to be used separately. It has a nice clean configurable API.
=> Export ExpirationWatcher from OrderWatcher

package.json, yarn.lock
This PR fixes a bug in the `postinstall` step introduced in [#1004](https://github.com/0xProject/0x-monorepo/pull/1004/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40).
It was causing a build failure if you do a full re-install with `yarn remove_node_modules && yarn install && yarn build`:
```
@0xproject/sra-report
| packages/sra-report/src/postman_environment_factory.ts(98,64): error TS2339: Property 'maker' does not exist on type 'SignedOrder'.
| packages/sra-report/src/postman_environment_factory.ts(99,64): error TS2339: Property 'taker' does not exist on type 'SignedOrder'.
| packages/sra-report/src/postman_environment_factory.ts(100,71): error TS2339: Property 'feeRecipient' does not exist on type 'SignedOrder'.
error Command failed with exit code 1.
info Visit …
```
=> Remove yarn postinstall hack

packages/ethereum-types/package.json, packages/json-schemas/package.json, packages/react-shared/package.json, packages/sol-resolver/package.json, packages/types/package.json, packages/typescript-typings/package.json, packages/utils/package.json
=> Update package.json versions to match the npm ones

package.json
OK this PR turned out simpler than expected. I also wanted to create a CDN and upload assets to that CDN post-publish but we can just use unpkg for now. The UMD bundles will be available in the `public/` directory (along with the index.html file which will provide a live demo of the bundle per version which is pretty cool).
=> Add 0x Instant to bundle analysis

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/src/asset_buyer.ts, packages/asset-buyer/src/types.ts, packages/asset-buyer/src/utils/assert.ts, packages/asset-buyer/src/utils/buy_quote_calculator.ts, packages/asset-buyer/test/buy_quote_calculator_test.ts, packages/order-utils/src/order_factory.ts
* Updated logic in the `buy_quote_calculator` to more accurately calculate min and max rate
* Added tests for `buy_quote_calculator`
`yarn test` in the `asset-buyer` package
=> [asset-buyer] Rework min / max rate calc and add tests

.circleci/config.yml, package.json, yarn.lock
https://github.com/bundlewatch/bundlewatch#i-use-bundlesize-why-should-i-switch-to-bundlewatch
=> Use bundlewatch instead of bundlesize

packages/website/package.json, packages/website/ts/utils/error_reporter.ts, yarn.lock
One of the reasons we did not include `website` in the `project references` build command `build:ws` is because it still needed `allowJs` in `tsconfig.json` to support the Rollbar UMD and `u2f_api.js` UMD. This PR removes one of them, getting us a step closer to our goal.
Modify the website to call `errorHandler.report` onLoad. Check Rollbar and make sure the error was transmitted.
=> fix(website): replace Rollbar UMD with regular npm package

.circleci/config.yml, .gitignore, package.json, python-packages/order_utils/package.json, python-packages/order_utils/setup.py, python-packages/order_utils/src/conf.py, python-packages/order_utils/src/index.rst, python-packages/order_utils/src/zero_ex/__init__.py, python-packages/order_utils/src/zero_ex/order_utils/__init__.py, python-packages/order_utils/src/zero_ex/order_utils/signature_utils.py, python-packages/order_utils/test/__init__.py, python-packages/order_utils/test/test_doctest.py, python-packages/order_utils/test/test_signature_utils.py, python-packages/order_utils/tox.ini
An empty project, with respect to functionality, but one configured with
a test framework, linters, CI integration, etc.
https://app.asana.com/0/836857747873847/839549782781239/f
Watch CircleCI!  To test locally, have python 3.7 installed, and see commands available in `package.json`.
=> [python/order_utils] Project stub

packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/contract_wrappers/forwarder_wrapper.ts, packages/contract-wrappers/test/forwarder_wrapper_test.ts
Similar to the approach taken in exchange wrapper, make a call to an rpc
node in order to simulate the transaction before actually sending the
transaction. The decorator will parse revert reasons and other types of
errors into canonical errors that a consumer of the library expects when
interacting with a contract wrapper.
- Navigate to `packages/contract-wrappers`
- Run `yarn test`
=> [contract-wrappers] Add optional validation to the forwarder wrapper

packages/website/ts/pages/about/about.tsx
Add Steve's github account and capitalize AppFolio correctly
* Bug Fix
=> [website] Add Steve's github

packages/website/ts/components/portal/portal.tsx, packages/website/ts/components/relayer_index/relayer_grid_tile.tsx, packages/website/ts/components/relayer_index/relayer_index.tsx, yarn.lock
* Add the `expanded` and `minimized` display styles to the relayer grid
* Because our data pipeline is not reporting v2 related data correctly yet, hide volume numbers that are coming from v1 using the minimized display style
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/portal
=> [website] Add expanded and minimized display types to relayer grid

packages/abi-gen-wrappers/package.json, packages/abi-gen-wrappers/tslint.json, yarn.lock
=> Enable linter on generated abi-gen wrappers

packages/0x.js/package.json, packages/monorepo-scripts/src/publish.ts
=> Don't attempt publishing if no packages need it

packages/monorepo-scripts/src/prepublish_checks.ts, packages/monorepo-scripts/src/publish.ts, packages/monorepo-scripts/src/publish_release_notes.ts, packages/monorepo-scripts/src/utils/github_release_utils.ts, packages/monorepo-scripts/src/utils/utils.ts
=> Fix the package versions in release notes

packages/contracts/README.md
=> Update links, remove 1.0 from contracts README

packages/website/ts/blockchain.ts, packages/website/ts/components/portal/portal.tsx, yarn.lock
* Instantiate the correct subprovider for metamask
* Do not load balances for empty token list
=> [website] Fix broken order signing on portal and broken loading on kovan

packages/contracts/contracts/extensions/Forwarder/MixinExchangeWrapper.sol, packages/contracts/test/extensions/forwarder.ts, packages/contracts/test/utils/forwarder_wrapper.ts
This PR addresses a handful of failed transactions for the forwarding contract.
Sample:
https://etherscan.io/tx/0x3d22b18fe2615c1903408b1b969744bcd117becc30205df18d5c5c54d27d1237
It was found that the rounding direction for MarketBuys needed to be reversed.
The exchange contract favors the maker by rounding down how much MakerAsset is spent.
To account for this in the forwarding contract, we need to round up how much TakerAsset is spent.
This PR includes test cases.
=> [WIP] Round up for Market Buys in Forwarding Contract.

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/src/asset_buyer.ts, packages/asset-buyer/src/types.ts, packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/index.ts, packages/contract-wrappers/src/types.ts, packages/contract-wrappers/src/utils/constants.ts, packages/contract-wrappers/src/utils/decorators.ts, packages/monorepo-scripts/CHANGELOG.json, packages/monorepo-scripts/src/doc_gen_configs.ts
* Expanded the `AssetBuyerError` enum to include  `AssetBuyerError.SignatureRequestDenied` and `AssetBuyerError.TransactionValueTooLow`
* `SignatureRequestDenied` is thrown by the `executeBuyQuoteAsync()` method when the end-user denies the signing request
* The above is achieved buy extending the errorTransformers in the contract-wrappers decorators to handle errors thrown by MetaMask
* `TransactionValueTooLow` is thrown by the`executeBuyQuoteAsync()` method when forwarder market buy validation comes back with an error. This means that the input we formed to send to the forwarder will most likely result in a transaction failure. We should handle this error at the 0x Instant level and reset the current buyQuote
Todo:
`yarn test`
New feature (non-breaking change which adds functionality)
* …
=> [asset-buyer][contract-wrappers] Throw SignatureRequestDenied and TransactionValueTooLow errors from AssetBuyer

CODEOWNERS
I added myself wherever I think makes the most sense. Open to suggestions.
=> Add albrow to CODEOWNERS

packages/migrations/README.md
This PR removes instructions for the older v1 and v2-testnet-beta scripts from the migrations README. These scripts were removed in #1105.
=> Update migrations README.

packages/instant/src/components/buy_button.tsx, packages/instant/src/components/buy_order_state_button.tsx, packages/instant/src/components/instant_heading.tsx, packages/instant/src/constants.ts, packages/instant/src/containers/selected_asset_amount_input.ts, packages/instant/src/containers/selected_asset_buy_button.ts, packages/instant/src/containers/selected_asset_buy_order_state_button.tsx, packages/instant/src/containers/selected_asset_view_transaction_button.tsx, packages/instant/src/redux/reducer.ts, packages/instant/src/types.ts, packages/instant/src/util/etherscan.ts
When transaction is processing:
- Be able to view transaction on etherscan
- Update top text and show spinner icon
=> [instant] View Processing Transaction

packages/website/ts/components/fill_order.tsx, yarn.lock
Fixes https://github.com/0xProject/0x-monorepo/issues/1183
* When calculating the amount of makerAsset left in an order we were not rounding the result
* This was causing us to fail an `isValidBaseUnitAmount` assertion when converting to unit amount in the `VisualOrder` component
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/portal/fill?order={%22signedOrder%22:{%22senderAddress%22:%220x0000000000000000000000000000000000000000%22,%22makerAddress%22:%220x7a1009d352fe8529d30cb1e6b5bad23b8ed76cf3%22,%22takerAddress%22:%220x0000000000000000000000000000000000000000%22,%22makerFee%22:%220%22,%22takerFee%22:%220%22,%22makerAssetAmount%22:%22529000000000000000000%22,%22takerAssetAmount%22:%22687700000000000000000%22,%22makerAssetData%22:%220xf47261b000000000000000000000000061327ca77f …
=> [website] Round makerAssetToken amount in FillOrder component

packages/instant/src/components/buy_button.tsx, packages/instant/src/constants.ts
* Default to 6 gwei for transactions
=> [instant] Add default gasPrice of 6 gwei to transactions

packages/instant/src/components/buy_button.tsx, packages/instant/src/components/zero_ex_instant.tsx, packages/instant/src/constants.ts, packages/instant/src/util/coinbase_api.ts, packages/instant/src/util/gas_price_estimator.ts
Hit eth gas station to get best gas price
=> [instant] Gas price estimate

packages/instant/public/index.html, packages/instant/src/components/ui/button.tsx, packages/instant/src/components/ui/icon.tsx, packages/instant/src/components/ui/index.ts, packages/instant/src/components/ui/overlay.tsx, packages/instant/src/components/zero_ex_instant.tsx, packages/instant/src/components/zero_ex_instant_overlay.tsx, packages/instant/src/components/zero_ex_instant_provider.tsx, packages/instant/src/constants.ts, packages/instant/src/index.ts, packages/instant/src/index.umd.ts, packages/instant/src/style/theme.ts
* Export a new component that encases the instant component in a dismissible overlay
* Update umd bundle to use the new ZeroExInstantOverlay component
http://0x-instant-dogfood.s3-website-us-east-1.amazonaws.com/
* New feature (non-breaking change which adds functionality) 
=> [instant] Dismissible overlay

packages/instant/public/index.html, packages/instant/src/data/asset_data_network_mapping.ts, packages/instant/src/data/asset_meta_data_map.ts, packages/instant/src/redux/reducer.ts
- Fix the typo in index.html.
- (Re)create and add orders for REP, GNT and MKR.
- Fix casing issues with assetDatas in the map.
What we used for bug-bash (no GNT though):
http://0x-instant-dogfood.s3-website-us-east-1.amazonaws.com/?networkId=42&orderSource=provided
=> [instant] Add GNT and MKR testnet orders, fix typo

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/src/constants.ts
Lower default expiry buffer from 5 mins to 2 mins
=> [asset-buyer] Lower default expiryBuffer from 5 minutes to 2 minutes

packages/contracts/CHANGELOG.json, packages/contracts/README.md
=> Add CHANGELOG.json to contracts package

packages/subproviders/src/subproviders/ledger.ts, packages/subproviders/src/utils/wallet_utils.ts
Fixes: https://github.com/0xProject/0x-monorepo/issues/1247
=> Fix lowercase address bug in LedgerSubprovider and MnemonicSubprovider

packages/instant/src/components/erc20_token_selector.tsx, packages/instant/src/components/instant_heading.tsx, packages/instant/src/components/ui/container.tsx, packages/instant/src/components/ui/input.tsx, packages/instant/src/components/zero_ex_instant_container.tsx
* Prevent the token picker from popping up when pressing tab
* Do not round corners on mobile
* Token picker search bar should only match on prefixes
N/A
=> [instant] Fix a bunch of low hanging bugs

packages/asset-buyer/src/utils/order_provider_response_processor.ts
* Sometimes calls issued to the `OrderValidator` contract come back with response `0x`
* Due to different implementations of parity and geth nodes, its difficult to tell whether this response is due to node failure or the call was successful, but did not return anything
* Because of these implementation details its hard to implement a general error handling fix in web3-wrapper or subproviders
* Therefore, we introduce logic in the application layer here, where we know `OrderValidator.getOrdersAndTradersInfoAsync()` always returns a value
* In the case of failure, we just swallow the error and allow the buyQuote to be calculated by using partial information provided to us by the SRA, or if none is provided, assuming the orders are fully fillable
* Issue a bunch of quote requests
* Observe …
=> [instant] Catch errors coming from calls to the orderValidator contract

packages/website/ts/blockchain.ts, packages/website/webpack.config.js, yarn.lock
* Add an undefined check that we were missing
* As of webpack 4 we do not need to use the `webpack.DefinePlugin` to set the NODE_ENV environment variable to production explicitly anymore
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/portal
=> [website] Fix currentProvider called on undefined and NODE_ENV production warning

packages/instant/package.json
In https://github.com/0xProject/0x-monorepo/pull/1275 I actually broke the `test-publish` test suite. This should fix it for now until we know the cause.
=> [instant] (temporarily) make instant private

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/src/index.ts
```
ERC20Proxy successfully deployed at 0x3e809c563c15a295e832e37053798ddc8d6c8dab
ERC721Proxy successfully deployed at 0x8e1ff02637cb5e39f2fa36c14706aa348b065b09
ZRXToken successfully deployed at 0x2727e688b8fd40b198cd5fe6e408e00494a06f07
Exchange successfully deployed at 0x22ebc052f43a88efa06379426120718170f2204e
AssetProxyOwner successfully deployed at 0x1da52d1d3a3acfa0a1836b737393b4e9931268fc
DummyERC20Token successfully deployed at 0x537732b0bac4f2a1a97b1a60cea0df5c3f0def16
DummyERC20Token successfully deployed at 0x1e28a5fb7b112291f088bbb8ab693d2214db7895
DummyERC20Token successfully deployed at 0x60498ee9f32dac81ca260747ea65f069b2312b0e
DummyERC20Token successfully deployed at 0x1c0bf72c5b989c54567948a9b31237e87daa2c3c
DummyERC20Token successfully deployed at …
```
=> Deploy contracts to Rinkeby

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/package.json, packages/instant/package.json
=> [asset-buyer][instant] downgrade lodash to be consistent with the rest of 0x packages

packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/src/contract_wrappers/erc20_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/erc721_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/ether_token_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts, packages/contract-wrappers/src/contract_wrappers/forwarder_wrapper.ts, packages/contract-wrappers/src/schemas/tx_opts_schema.ts, packages/contract-wrappers/src/types.ts
Sometimes transactions get stuck because of insufficient gas price and you need to rebroadcast them.
For that, you need to be able to specify the nonce. That PR allows that.
=> Add `nonce` to `TxOpts`

packages/instant/src/components/erc20_asset_amount_input.tsx, packages/instant/src/containers/selected_erc20_asset_amount_input.ts
Don't allow user to change assets when an order is happening.
=> [instant] Don't allow changing of assets when order in progress

packages/abi-gen-wrappers/CHANGELOG.json, packages/abi-gen-wrappers/package.json, packages/abi-gen-wrappers/src/generated-wrappers/asset_proxy_owner.ts, packages/abi-gen-wrappers/src/generated-wrappers/dummy_erc20_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/dummy_erc721_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc20_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc20_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc721_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc721_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/exchange.ts, packages/abi-gen-wrappers/src/generated-wrappers/forwarder.ts, packages/abi-gen-wrappers/src/generated-wrappers/i_validator.ts, packages/abi-gen-wrappers/src/generated-wrappers/i_wallet.ts, packages/abi-gen-wrappers/src/generated-wrappers/order_validator.ts, packages/abi-gen-wrappers/src/generated-wrappers/weth9.ts, packages/abi-gen-wrappers/src/generated-wrappers/zrx_token.ts, packages/contract_templates/contract.handlebars, packages/types/CHANGELOG.json, packages/types/src/index.ts
Fixes: https://github.com/0xProject/0x-monorepo/issues/1297
=> Fix Artifact Interface Type Issue

packages/instant/src/containers/connected_account_payment_method.ts, packages/instant/src/redux/analytics_middleware.ts, packages/instant/src/redux/async_data.ts, packages/instant/src/util/analytics.ts, packages/instant/src/util/heap.ts
Adds the following events
```
ACCOUNT_LOCKED = 'Account - Locked',
ACCOUNT_READY = 'Account - Ready',
ACCOUNT_UNLOCK_REQUESTED = 'Account - Unlock Requested',
ACCOUNT_UNLOCK_DENIED = 'Account - Unlock Denied',
ACCOUNT_ADDRESS_CHANGED = 'Account - Address Changed',
```
Check out live capture on heap
=> [instant] Implement account related events

packages/instant/package.json, packages/monorepo-scripts/CHANGELOG.json, packages/monorepo-scripts/src/publish.ts
Currently the CI build is broken: [Build log](https://circleci.com/gh/0xProject/0x-monorepo/43271)
After fixing that parameter naming issue I've encountered the second one that was also present before: [Build log](https://circleci.com/gh/0xProject/0x-monorepo/42949)
This PR fixes both. @fragosti Please look at this PR as it's related to instant and I'm not sure my fix is a correct one.
=> [@0x/instant] Fix CI build broken by instant installation tests

packages/instant/package.json, packages/monorepo-scripts/CHANGELOG.json, packages/monorepo-scripts/src/publish.ts
Reverts 0xProject/0x-monorepo#1312
=> Revert "[@0x/instant] Fix CI build broken by instant installation tests"

package.json
=> fix: add --exclude-missing flag to yarn clean command

packages/instant/src/components/payment_method_dropdown.tsx
Copying to clipboard was broken, without this change got error:
```
Uncaught TypeError: copy_to_clipboard_1.default is not a function
```
=> [instant] Fix copy to clipboard

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/src/index.ts
Redeployed Rinkeby due to the previous version having the Mainnet Exchange bytecode deployed. This prevented Rinkeby ZRX being used in the contracts as it was referencing Mainnet.
```
ERC20Proxy successfully deployed at 0x2f5ae4f6106e89b4147651688a92256885c5f410
ERC721Proxy successfully deployed at 0x7656d773e11ff7383a14dcf09a9c50990481cd10
ZRXToken successfully deployed at 0x8080c7e4b81ecf23aa6f877cfbfd9b0c228c6ffa
Exchange successfully deployed at 0xbce0b5f6eb618c565c3e5f5cd69652bbc279f44e
AssetProxyOwner successfully deployed at 0xe1703da878afcebff5b7624a826902af475b9c03
DummyERC20Token successfully deployed at 0x175ac784563de645647c6350f0cfc577dcc7ee5b
DummyERC20Token successfully deployed at 0xa47aa5fcecbfb374e79144f05fdf91d0f50fa351
DummyERC20Token successfully deployed at …
```
=> [testnet][contract-addresses] Rinkeby and Ganache 

packages/instant/src/components/install_wallet_panel_content.tsx, packages/instant/src/components/standard_panel_content.tsx, packages/instant/src/containers/connected_account_payment_method.ts, packages/instant/src/redux/analytics_middleware.ts, packages/instant/src/types.ts, packages/instant/src/util/analytics.ts
Analytic events for installing wallet
=> [instant] Install Wallet analytic events

packages/instant/src/components/timed_progress_bar.tsx, packages/instant/src/components/ui/container.tsx, packages/instant/src/style/theme.ts
Make progress bar background 10% opacity of primary color
=> [instant] Progress bar background

packages/instant/.dogfood.discharge.json, packages/instant/.production.discharge.json, packages/instant/.staging.discharge.json, packages/instant/README.md, packages/instant/package.json, packages/instant/src/index.umd.ts, packages/instant/src/util/version.ts, packages/instant/tsconfig.json, packages/instant/webpack.config.js, tsconfig.json
Should I change the CDN settings to redirect HTTP to HTTPS?
https://instant.0xproject.com/instant.js
=> [instant] Remove commonjs bundle, productionize UMD bundle

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/src/order_providers/standard_relayer_api_order_provider.ts, packages/instant/src/data/asset_meta_data_map.ts
* Update asset-buyer to expand the list of supported Assets it interprets from the `/asset_pairs`endpoint
* Update DAI color in instant
http://0x-instant-dogfood.s3-website-us-east-1.amazonaws.com
=> [asset-buyer][instant] support DAI in instant

packages/pipeline/migrations/1543434472116-TokenOrderbookSnapshots.ts, packages/pipeline/src/data_sources/ddex/index.ts, packages/pipeline/src/data_sources/paradex/index.ts, packages/pipeline/src/entities/index.ts, packages/pipeline/src/entities/token_order.ts, packages/pipeline/src/ormconfig.ts, packages/pipeline/src/parsers/ddex_orders/index.ts, packages/pipeline/src/parsers/paradex_orders/index.ts, packages/pipeline/src/scripts/pull_ddex_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_paradex_orderbook_snapshots.ts, packages/pipeline/src/types.ts, packages/pipeline/test/entities/token_order_test.ts, packages/pipeline/test/parsers/ddex_orders/index_test.ts, packages/pipeline/test/parsers/paradex_orders/index_test.ts, packages/tslint-config/tslint.json
1. Sets up token_orderbook_snapshot migration.
2. Scrapes orderbook data from Ddex and inserts it into the table.
Added tests for parser. These work fine.
Ran script and saved data into DB:
Most important functions have been documented.
=> WIP token_orderbook_snapshots

packages/instant/src/components/buy_order_progress.tsx, packages/instant/src/components/instant_heading.tsx, packages/instant/src/components/order_details.tsx, packages/instant/src/components/payment_method.tsx
=> [instant] Reduce vertical padding in instant

packages/website/ts/pages/instant/code_demo.tsx, packages/website/ts/pages/instant/config_generator.tsx, packages/website/ts/pages/instant/fee_percentage_slider.tsx
Disable the configurator slider when affiliate info address is falsey.
=> [website] Disable slider when no affiliate info

packages/instant/src/components/erc20_token_selector.tsx
Don't throw an error if we can't find an icon for a token
Use custom erc20 integration code here: https://gist.github.com/steveklebanoff/b87eef363f6df06a144426120eb731d9
=> [instant] Don't throw error if can't find icon for token

packages/instant/src/components/instant_heading.tsx, yarn.lock
This PR hides the loading indicators to the right of the amount input when no token or buy amount is selected
http://0x-instant-dogfood.s3-website-us-east-1.amazonaws.com/
=> [instant] Hide loaders when no token or buy amount is chosen

packages/instant/src/components/zero_ex_instant_provider.tsx, packages/instant/src/containers/connected_account_payment_method.ts, packages/instant/src/types.ts, packages/instant/src/util/analytics.ts, packages/instant/src/util/env.ts, packages/instant/src/util/provider_state_factory.ts
- Adds `displayName` field to `ProviderState`. 
- Centralizes `displayName` calculation logic. 
- Logs displayName to heap
=> [instant] Refactor provider name and provider display name logic, log the display name

packages/pipeline/src/parsers/token_metadata/index.ts
Token Metadata creation fails when decimals field is null
=> perform null check on token metadata

packages/order-utils/CHANGELOG.json, packages/order-utils/src/signature_utils.ts
Addresses: https://github.com/0xProject/0x-monorepo/issues/1407
=> [order-utils] Fix Wallet Signature Verification

python-packages/order_utils/src/zero_ex/dev_utils/type_assertions.py
Fabio and I discussed the TODO item here and ultimately decided that this code already does what we need it to do.
None!  Just comments removed.
=> Remove stale TODO

packages/pipeline/migrations/1544131658904-TokenOrderbookSnapshotAddOrderType.ts, packages/pipeline/src/data_sources/idex/index.ts, packages/pipeline/src/data_sources/oasis/index.ts, packages/pipeline/src/entities/token_order.ts, packages/pipeline/src/parsers/ddex_orders/index.ts, packages/pipeline/src/parsers/idex_orders/index.ts, packages/pipeline/src/parsers/oasis_orders/index.ts, packages/pipeline/src/parsers/utils.ts, packages/pipeline/src/scripts/pull_idex_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_oasis_orderbook_snapshots.ts, packages/pipeline/test/parsers/ddex_orders/index_test.ts, packages/pipeline/test/parsers/idex_orders/index_test.ts, packages/pipeline/test/parsers/oasis_orders/index_test.ts, packages/pipeline/test/parsers/utils/index_test.ts
track idex orderbook snapshots
usual tests
new feature
=> track idex orderbook snapshots

packages/pipeline/src/scripts/pull_missing_blocks.ts
This PR fixes a bug/oversight in the __pull_missing_blocks__ script. Previously, it only looked at block numbers in the `exchange_fill_events` table. Now it considers all types of events.
=> Make pull_missing_blocks script consider all events with block numbers

package.json, yarn.lock
Update the a newer version of our Lerna fork with a CI fix for the failing `test-publish` task. 
=> CI Lerna Fix

contracts/test-utils/src/assertions.ts, contracts/test-utils/src/test_with_reference.ts, packages/pipeline/src/scripts/pull_competing_dex_trades.ts, packages/pipeline/src/scripts/pull_ddex_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_idex_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_missing_blocks.ts, packages/pipeline/src/scripts/pull_oasis_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_paradex_orderbook_snapshots.ts, packages/pipeline/src/scripts/pull_trusted_tokens.ts, packages/pipeline/src/scripts/update_relayer_info.ts, packages/tslint-config/CHANGELOG.json, packages/tslint-config/rules/walkers/async_suffix.ts
We have a custom linter rule `async-suffix`. Before it only worked for methods. Now functions are also checked.
It detected two places and they were fixed. GJ everyone. Just two places!!!.
=> Check for an Async suffix in functions, not just methods.

packages/pipeline/src/parsers/token_metadata/index.ts, packages/pipeline/src/utils/index.ts
Title is self-explanatory. This is a bugfix in the token metadata parser.
=> Fix bug that occurs when token metadata decimals is undefined.

packages/instant/src/redux/async_data.ts
Bug repro (per Discord report): 
- Type in a 0 amount
- Wait for heartbeat to happen
- Notice that we show a 0 buy quote and can click the buy button
This fixes that bug by not triggering a buy quote update if the amount is 0
=> [instant] Don't update heartbeat if amount is 0

README.md
Fixed the PyPI version badge on the top-level README.  I had cloned it from the `order-utils` entry, and missed changing one of the references.
=> Correct Python SRA client version badge

packages/website/public/images/developers/tutorials/integrate_0x_instant.svg, packages/website/translations/english.json, packages/website/ts/pages/documentation/docs_home.tsx, packages/website/ts/types.ts
* Added 0x instant wiki  as a track in the top level docs
=> [website] add 0x Instant as a track in the docs

packages/pipeline/src/utils/get_ohlcv_trading_pairs.ts
Small fix to start scraping ETH/USD OHLCVs
I also renamed some variables to distinguish where we were getting tokens from. 
I've run the script locally but not on QA. Script works locally.
=> add special case to scrape OHLCV for eth/usd

packages/pipeline/src/parsers/ddex_orders/index.ts, packages/pipeline/src/parsers/oasis_orders/index.ts, packages/pipeline/src/parsers/paradex_orders/index.ts, packages/pipeline/test/parsers/ddex_orders/index_test.ts, packages/pipeline/test/parsers/oasis_orders/index_test.ts, packages/pipeline/test/parsers/paradex_orders/index_test.ts
Based on results of audit from here: https://quip.com/aPzQAbLRpVGc/DEX-Order-Format-Audit
yarn test
Bug fix
=> Fix dex order quote/base asset assigning

packages/pipeline/src/scripts/pull_erc20_events.ts
This PR adds two new ERC20 tokens for which we will scrape approval events: ZRX and DAI. We can add more tokens in the future, but this seems like a good starting point.
=> Pull approval events for ZRX and DAI

packages/website/ts/@next/pages/about/jobs.tsx, packages/website/ts/index.tsx, yarn.lock
* Updated the `/jobs#positions` link to work
* Fixed broken website-api.0xproject.com links
=> [0x.org] update jobs page to load positions from greenhouse

packages/website/ts/@next/components/newsletter_form.tsx
* Prettify file
* Allow manual triggering of error through newsletter form to test Rollbar
* Send newsletter subscription errors to Rollbar
=> [website] 0x.org: Allow manual triggering of error, and report newsletter errors to Rollbar

packages/website/ts/@next/components/sections/landing/about.tsx
- Prettify file
- Update stats
=> [website] 0x.org stats

packages/website/ts/@next/components/aboutPageLayout.tsx, packages/website/ts/@next/pages/about/jobs.tsx, packages/website/ts/@next/pages/about/mission.tsx, packages/website/ts/@next/pages/about/press.tsx, packages/website/ts/@next/pages/about/team.tsx, packages/website/ts/index.tsx
=> [website] 0x org about

python-packages/sra_client/tox.ini
If you wanted to run these new commands:
* `tox -erun_tests_against_test_deployment`
* `tox -erun_tests_against_deployment`
=> Add tox commands for testing sra_client.py against deployed pkg

contracts/protocol/CHANGELOG.json, contracts/protocol/contracts/protocol/AssetProxy/MultiAssetProxy.sol, contracts/protocol/test/asset_proxy/proxies.ts
=> Add validation to MAP

packages/website/ts/@next/components/link.tsx, packages/website/ts/@next/pages/about/jobs.tsx, packages/website/ts/components/ui/container.tsx
* Make "Apply" look like the other 'action links'
* Make position section wider
* Align position text with location & apply button
**Old**
**New**
=> [website] Tweak job listings

packages/website/ts/components/ui/container.tsx
Take out duplicate props from a bad merge which made the website build break on CI
=> [website] Fix duplicate props which made ci build break

packages/instant/src/components/ui/container.tsx, packages/instant/src/components/ui/dropdown.tsx
Makes the dropdown color the primary color at 10% opacity
=> [instant] Dropdown hover 10% of primary color

packages/sra-spec/public/index.html
Add title tag to OpenSwagger to ReDoc page.  This was annoying me when I couldn't find the Standard Relayer API in my browser tabs :) 
=> [sra-spec] Add title tag

packages/asset-buyer/README.md
=> [asset-buyer] Remove beta note from asset-buyer

packages/website/ts/components/modals/modal_contact.tsx, packages/website/ts/components/newsletter_form.tsx, packages/website/ts/utils/configs.ts, packages/website/ts/utils/constants.ts
This branch goes along with some EC2 load balancer fiddling to make sure the endpoints have the correct SSL certificate. 
The backup geth nodes aren't working anyway because of CORS, so I've gone ahead and changed the configs for those already. 
For website-api.0x.org, I'll have to update those configs when I deploy.
=> [website] Audit and fix 0x.org migration URLs

packages/instant/src/constants.ts, packages/instant/src/types.ts, packages/instant/src/util/env.ts
Now that Instant works in Opera I added it as a provider type and gave it a friendly name. This also means we'll see a readable name in Heap.
=>  [instant] Implement logging and friendly wallet name for Opera

packages/pipeline/README.md
As per our recent meeting, this PR adds some additional instructions to the README related to deploying new pipeline scripts.
=> Add new deployment related instructions to pipeline README

packages/react-shared/package.json, yarn.lock
* Update website's dep on our react-highlight fork to the latest commit
* https://github.com/0xProject/react-highlight/pull/2
http://staging-0xproject.s3-website-us-east-1.amazonaws.com/wiki
=> [website] Update react-highlight dep in website to latest commit

packages/pipeline/src/scripts/pull_competing_dex_trades.ts, packages/pipeline/src/scripts/pull_copper.ts, packages/pipeline/src/scripts/pull_exchange_events.ts, packages/pipeline/src/scripts/pull_missing_blocks.ts, packages/pipeline/src/scripts/pull_ohlcv_cryptocompare.ts, packages/pipeline/src/scripts/pull_radar_relay_orders.ts, packages/pipeline/src/scripts/pull_trusted_tokens.ts, packages/pipeline/src/scripts/update_relayer_info.ts
=> Replace console.log with logUtils.log

packages/website/md/docs/sol_coverage/usage.md, packages/website/md/docs/sol_profiler/usage.md, packages/website/md/docs/sol_trace/usage.md
=> Add notes about istanbul and Geth to website docs

packages/devnet/docker-compose.yml
Add docker-compose.yml config for 0x-devnet package Docker image. This can be expanded upon in future if necessary.
I don't think any testing is necessary for this change, it's more to make the Docker configuration self-commenting for those familiar with the docker-compose tool.
=> [feature] [package/0x-devnet] Add docker-compose basic config

packages/instant/src/components/erc20_asset_amount_input.tsx
-   [ x ] Prefix PR title with `[WIP]` if necessary.
=> Changed error message from "Assets Unavailable" to "Tokens Unavailable"

packages/pipeline/migrations/1548809952793-AllowDuplicateTxHashesInDexTrades.ts, packages/pipeline/src/data_sources/bloxy/index.ts, packages/pipeline/src/entities/dex_trade.ts, packages/pipeline/src/parsers/bloxy/index.ts, packages/pipeline/test/entities/dex_trades_test.ts, packages/pipeline/test/parsers/bloxy/index_test.ts, yarn.lock
This removes the assumption from our data pipeline that trades (Fills in our case) have unique transaction hashes. Removing this constraint meant that we needed a new way to uniquely identify a DEX trade. Thankfully Bloxy was willing to (quickly) expose a `trade_index` field through the API, and guarantee that `(trade_index, tx_hash)` pairs are unique. I wrote a migration to add `trade_index` as a primary column to DEX trades, so the composite primary key is now `(source_url, tx_hash, trade_index)`. It'll be useful to have `source_url` in there if we ever want to integrate a source that isn't Bloxy and still easily guarantee row uniqueness. 
Before:
After:
-   [ ] Update documentation as …
=> [pipeline] Fix missing DEX Trades from Bloxy

packages/website/ts/components/mobileNav.tsx, packages/website/ts/utils/constants.ts
Per convo in Slack, link out to blog.0xproject.com instead of blog.0xproject.com/latest
=> [website] Change blog link

packages/order-utils/CHANGELOG.json, packages/order-utils/src/eip712_utils.ts, packages/order-utils/src/index.ts, packages/order-utils/test/eip712_utils_test.ts
=> Stop exporting EIP712 schemas

packages/website/ts/components/footer.tsx
=> Added forum link

packages/website/ts/index.tsx, packages/website/ts/pages/vote_placeholder.tsx, packages/website/ts/types.ts, packages/website/ts/utils/constants.ts, yarn.lock
=> Add vote placeholder page

packages/website/ts/components/modals/modal_contact.tsx
=> Fix for credit lead form data

packages/website/ts/components/announcement.tsx, packages/website/ts/components/hero.tsx, packages/website/ts/components/sections/landing/hero.tsx
TODO:
Need it to look better on mobile. 
=> Adding announcement component for hero (for vote)

packages/website/ts/components/hero.tsx
=> [WIP] Added padding fix

packages/devnet/README.md
=> Update README for devnet

packages/website/ts/pages/governance/address_table.tsx, packages/website/ts/pages/governance/connect_form.tsx, packages/website/ts/pages/governance/ledger_sign_note.tsx, packages/website/ts/pages/governance/modal_vote.tsx, packages/website/ts/pages/governance/vote_bar.tsx, packages/website/ts/pages/governance/vote_form.tsx, packages/website/ts/pages/governance/vote_stats.tsx
Fix bug in ledger address selector where provider does not exist. This can happen in browsers without metamask or a injected provider
=> [Governance] Ledger address selector ZRX balance

packages/website/ts/pages/governance/address_table.tsx, packages/website/ts/pages/governance/ledger_sign_note.tsx, packages/website/ts/pages/governance/vote_form.tsx
Fixes broken formatting + adds note when signing with ledger
=> Governance tweaks

packages/website/ts/pages/governance/governance.tsx
=> Change vote end date to end on PST 25/02/2019

packages/contract-addresses/CHANGELOG.json, python-packages/contract_addresses/src/zero_ex/contract_addresses/__init__.py
=> Fix OrderValidator and Forwarder addresses in Python package

packages/website/ts/components/sections/landing/hero.tsx
=> [WIP] Removed announcement

packages/website/public/index.html
Reintroducing metadata into public.html for now, until the greater issue with SEO is resolved.
=> Added temporary metadata

packages/sol-compiler/CHANGELOG.json, packages/sol-compiler/src/utils/compiler.ts
Fixes: https://github.com/0xProject/0x-monorepo/issues/1597#event-2131103568
Overall that log message wasn't very useful. We have other messages after it that make more sense.
=> Remove redundant logging from sol-compiler

packages/utils/CHANGELOG.json, packages/utils/src/log_utils.ts
=> Check for process in browser environments

packages/contract-wrappers/CHANGELOG.json, packages/contract-wrappers/package.json, packages/metacoin/package.json, yarn.lock
This can bring in a lot of unwanted dependencies when using Contract-wrappers.
=> Move contracts-test-utils to dev dependencies

packages/sol-profiler/CHANGELOG.json, packages/sol-profiler/src/cost_utils.ts, packages/sol-profiler/src/profiler_subprovider.ts, packages/sol-tracing-utils/CHANGELOG.json, packages/sol-tracing-utils/src/artifact_adapters/truffle_artifact_adapter.ts, packages/sol-tracing-utils/src/constants.ts, packages/sol-tracing-utils/src/revert_trace.ts, packages/sol-tracing-utils/src/trace.ts, packages/sol-tracing-utils/src/trace_info_subprovider.ts, packages/sol-tracing-utils/src/types.ts, packages/sol-tracing-utils/src/utils.ts
The last sol-profiler PR fixes some stuff and breaked some other stuff. It was caused by me testing it only against Geth and truffle post 5.0. This PR fixes those issues, adds performance optimizations etc.
After this PR sol-compiler works for the DEX contract.
It's also much faster now.
One of the big changes in that PR is fixing the stack ordering. Now both Ganache and Geth stack are ordered upside-down. We also use constants defined in one place for stack param offsets instead of hardcoding 1s and 2. all over the codebase.
=> Sol profiler improvements and bug fixes

packages/website/ts/components/sections/landing/about.tsx
=> Updated stats on website

contracts/asset-proxy/CHANGELOG.json, contracts/asset-proxy/compiler.json, contracts/erc20/CHANGELOG.json, contracts/erc20/compiler.json, contracts/erc721/CHANGELOG.json, contracts/erc721/compiler.json, contracts/exchange-forwarder/CHANGELOG.json, contracts/exchange-forwarder/compiler.json, contracts/exchange-libs/CHANGELOG.json, contracts/exchange-libs/compiler.json, contracts/exchange/CHANGELOG.json, contracts/exchange/compiler.json, contracts/extensions/CHANGELOG.json, contracts/extensions/compiler.json, contracts/multisig/CHANGELOG.json, contracts/multisig/compiler.json, contracts/tec/CHANGELOG.json, contracts/tec/compiler.json, contracts/test-utils/CHANGELOG.json, contracts/utils/CHANGELOG.json, contracts/utils/compiler.json
Contracts aren't building. This (hopefully) fixes it.
=> Fix contracts after Solidity 0.5.5 update

packages/pipeline/src/entities/block.ts, packages/pipeline/src/entities/dex_trade.ts, packages/pipeline/src/entities/erc20_approval_event.ts, packages/pipeline/src/entities/exchange_cancel_event.ts, packages/pipeline/src/entities/exchange_cancel_up_to_event.ts, packages/pipeline/src/entities/exchange_fill_event.ts, packages/pipeline/src/entities/nonfungible_dot_com_trade.ts, packages/pipeline/src/entities/relayer.ts, packages/pipeline/src/entities/sra_order.ts, packages/pipeline/src/entities/sra_order_observed_timestamp.ts, packages/pipeline/src/entities/token_metadata.ts, packages/pipeline/src/entities/token_order.ts, packages/pipeline/src/entities/transaction.ts
This PR adds documentation for the entities in the pipeline package which I helped work on.
=> Add documentation for some pipeline entities

contracts/coordinator/contracts/src/Coordinator.sol, contracts/coordinator/contracts/src/registry/CoordinatorRegistry.sol, contracts/coordinator/contracts/test/TestLibs.sol, contracts/coordinator/contracts/test/TestMixins.sol, contracts/exchange/contracts/src/Exchange.sol
This fixes build issues when new versions of Solidity are released.
=> Unpin Solidity versions for contracts that are not deployed

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/src/index.ts
=> Added Dutch Auction mainnet address to contract-addresses package

packages/website/md/docs/sol_coverage/usage.md, packages/website/md/docs/sol_profiler/usage.md, packages/website/md/docs/sol_trace/usage.md
=> Fix documentation typos

python-packages/sra_client/CHANGELOG.json, python-packages/sra_client/sra_client/models/order_schema.py
Fix issue described in https://github.com/0xProject/0x-monorepo/issues/1727. 
Run `python test`
Bug fix (non-breaking change which fixes an issue)
=> Fix regex validation on numeric inputs

packages/website/ts/pages/explore/explore_content.tsx
=> updates explore page

packages/website/less/all.less, packages/website/ts/pages/explore/explore_content.tsx
=> Switched Pixura link

packages/website/ts/pages/governance/vote_form.tsx, packages/website/ts/utils/constants.ts
=> Fix code sandbox link and 0x.js dep in website

python-packages/sra_client/sra_client/__init__.py, python-packages/sra_client/test/test_default_api.py
These tests have worked multiple times in Circle CI, but now they're not, and it seems to be misbehaving intermittently, so just disabling them for now.
Watch CI
=> Disable Python SRA tests against Launch Kit

.circleci/config.yml
I may have found a different way to fix the "Permission denied" errors in CircleCI that still allows us to install a specific version of yarn. Planning to re-run the tests a few times to make sure it works.
=> Fix yarn permission denied errors in CircleCI

packages/website/public/index.html, packages/website/ts/components/header.tsx, packages/website/ts/pages/explore.tsx, packages/website/ts/pages/explore/explore_grid.tsx
=> [WIP] Fix Explore Issues with flash of css + other minor bugs

packages/website/ts/pages/explore.tsx, packages/website/ts/pages/explore/explore_grid.tsx
=> Fix for menu z-index for explore

packages/instant/src/components/ui/flex.tsx, packages/instant/src/components/zero_ex_instant_overlay.tsx, packages/instant/src/components/zero_ex_instant_provider.tsx
Just added overflow: scroll to the container of instant so you can scroll to get to the buy button on small screens.
Also fixed a bug where the Token Amount said "1 ???" as a result of adding ERC721.
=> Add overflow scroll to instant overlay & fix display bug

packages/instant/src/index.umd.ts
Addressing PR feedback from the Wiki PR https://github.com/0xProject/wiki/pull/123
=> Export utility methods and data from instant

packages/website/ts/components/meta_tags.tsx, packages/website/ts/utils/document_meta_constants.tsx
=> Updated meta data for website

package.json
=> Add clean:contracts command to top level package.json

packages/website/public/index.html, packages/website/ts/components/meta_tags.tsx
=> Removed default descriptions for website SEO performance

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/src/index.ts, python-packages/contract_addresses/src/zero_ex/contract_addresses/__init__.py
Updates Coordinator bytecode so that approval signature verification doesn't fail. 
=> Update coordinator contracts

packages/migrations/src/cli.ts
Adds `--pk` option to supply a private key to the migration script
* New feature (non-breaking change which adds functionality) 
=> add private key option to migration script

packages/website/ts/pages/documentation/docs_home.tsx, packages/website/ts/pages/launch_kit.tsx, packages/website/ts/utils/constants.ts, python-packages/sra_client/README.md, python-packages/sra_client/setup.py, python-packages/sra_client/src/zero_ex/sra_client/__init__.py
Now that we have a `0x-launch-kit` backend and frontend repo, it makes sense to rename the backend repo to have the `-backend` suffix.
=> website/python-packages: Update 0x-launch-kit repo name to include `-backend`

packages/website/ts/components/dropdowns/dropdown_developers.tsx, packages/website/ts/components/dropdowns/dropdown_resources.tsx, packages/website/ts/components/header.tsx
- Added "Resources" to the main nav to include links to our Programs, Blog and Legal Wiki.
=> Added Resources dropdown to main nav

packages/website/ts/components/hero.tsx
=> Fixed bug with launch kit background

yarn.lock
=> Fixes the severe security vulnerability warnings on Github

packages/dev-tools-pages/ts/pages/coverage.tsx, packages/dev-tools-pages/ts/pages/profiler.tsx, packages/dev-tools-pages/ts/pages/trace.tsx, packages/metacoin/README.md, packages/website/md/docs/sol_coverage/usage.md, packages/website/md/docs/sol_profiler/usage.md, packages/website/md/docs/sol_trace/usage.md, packages/website/ts/components/documentation/sidebar_header.tsx, packages/website/ts/pages/documentation/developers_page.tsx, packages/website/ts/pages/documentation/docs_home.tsx
This PR:
- Recommends users of our Ethereum dev tools use Ganache since it's now supported (https://github.com/0xProject/0x-monorepo/issues/1520) and `devnet` might get deprecated.
- Removes some of the tools from the Dev homepage to declutter a bit.
- Removed the scrollbar hide unless hovered from doc pages since it was interfering with readers using `CMD-F` to search the content unless they were hovering over the content section. This is a short-term fix until Docs 2.0 is released.
- Fix a version picker overflow issue.
=> website: Doc Fixes

packages/website/ts/components/announcement.tsx, packages/website/ts/components/sections/landing/hero.tsx
=> Added StarkDEX announcement to homepage

contracts/README.md, packages/migrations/README.md
Add notes to improve discoverability of contracts build and publish workflow. It's pretty manual right now to make sure `Contract.sol`, `Contract.json`, `abi-gen-wrappers/Contract.ts`, and `@0x/contract-artifacts` are all kept in sync. Recording it in writing will help.
Example: https://github.com/0xProject/0x-monorepo/pull/1848/files#r290218854
Only README changes.
=> Note on updating contract artifacts

packages/instant/package.json, yarn.lock
=> [WIP] CFL instant temp CI fix

packages/asset-buyer/CHANGELOG.json, packages/asset-buyer/package.json, packages/asset-buyer/src/asset_buyer.ts, packages/asset-buyer/src/constants.ts, packages/asset-buyer/src/errors.ts, packages/asset-buyer/src/index.ts, packages/asset-buyer/src/order_providers/basic_order_provider.ts, packages/asset-buyer/src/order_providers/standard_relayer_api_order_provider.ts, packages/asset-buyer/src/quote_consumers/forwarder_swap_quote_consumer.ts, packages/asset-buyer/src/swap_quoter.ts, packages/asset-buyer/src/types.ts, packages/asset-buyer/src/utils/affiliate_fee_utils.ts, packages/asset-buyer/src/utils/assert.ts, packages/asset-buyer/src/utils/buy_quote_calculator.ts, packages/asset-buyer/src/utils/calculate_liquidity.ts, packages/asset-buyer/src/utils/order_provider_response_processor.ts, packages/asset-buyer/src/utils/swap_quote_calculator.ts, packages/asset-buyer/src/utils/utils.ts, packages/asset-buyer/test/forwarder_swap_quote_consumer_test.ts, packages/asset-buyer/test/global_hooks.ts, packages/asset-buyer/test/swap_quote_calculator_test.ts, packages/asset-buyer/test/swap_quoter_test.ts, packages/asset-buyer/test/utils/migrate.ts, packages/asset-buyer/test/utils/mocks.ts, packages/asset-buyer/test/utils/swap_quote.ts, packages/asset-buyer/test/utils/web3_wrapper.ts, packages/instant/package.json, yarn.lock
Still have yet to test all the code, but the large changes made are as follows:
- Changed naming schemes from `AssetBuyer` to `SwapQuoter`
- Changed `BuyQuote` to `SwapQuote`
- Added functionality to support ERC to ERC pairs for requesting `SwapQuotes`
- Created a new interface `SwapQuoteConsumer` that consumes or executes a `SwapQuote`
- Created preliminary Forwarder `SwapQuoteConsumer` that consumes valid forwarder `SwapQuotes` and returns calldata, smart contract params, or executes a forwarder smart contract call. 
=> [WIP] Asset-buyer Refactor for CFL

packages/asset-buyer/src/quote_consumers/exchange_swap_quote_consumer.ts, packages/asset-buyer/src/quote_consumers/forwarder_swap_quote_consumer.ts, packages/asset-buyer/src/types.ts, packages/asset-buyer/src/utils/swap_quote_consumer_utils.ts
=> [WIP] Asset-buyer 2.0 Exchange SwapQuote Consumer

packages/asset-buyer/src/index.ts, packages/asset-buyer/src/quote_consumers/dynamic_swap_quote_consumer.ts, packages/asset-buyer/src/quote_consumers/swap_quote_consumer.ts, packages/asset-buyer/src/types.ts, packages/asset-buyer/src/utils/swap_quote_consumer_utils.ts
Created a new consumer that will use the 'best' underlying consumer (Exchange, Forwarder, in the future Coordinator) to provide output or execute the swap quote. 
If the order is forwarder valid, the consumer will look at eth and weth balances as well to choose which consumer is best. 
=> [WIP] Asset buyer 2.0 Dynamic swap quote consumer

packages/asset-swapper/src/swap_quoter.ts
Per feedback from @dekz in https://github.com/0xProject/0x-monorepo/pull/1939
Changed interface for `SwapQuoter` to:
`getSwapQuote` -> `getSwapQuoteForAssetData`
`getSwapQuoteForERC20Address` -> `getSwapQuote`
Hope this makes the interface more intuitive.
=> Asset-swapper method interface change

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/src/index.ts
=> Redeployed 2.0 Mainnet

README.md, packages/asset-swapper/README.md
=> Updated README.md for asset-swapper

packages/order-watcher/README.md, packages/order-watcher/package.json, packages/website/md/docs/order_watcher/2/introduction.md, packages/website/ts/pages/documentation/docs_home.tsx
Deprecates `@0x/order-watcher` in favor of [Mesh](https://github.com/0xProject/0x-mesh)
=> Deprecate @0x/order-watcher

packages/website/ts/components/sections/landing/hero.tsx
=> Add announcement for vote

package.json, packages/monorepo-scripts/src/publish.ts, yarn.lock
Fixes: #1871
Lerna added support for 2FA in v3.16.0. This PR upgrades our fork of Lerna to v3.16.0, applying our changes on top of it. It also makes the necessary changes to work with this upgraded version.
Important note: The 2FA support only works for publishing 2FA enabled on the developers account , _not_ per-package 2FA configs.
=> Update Lerna fork to latest version

packages/website/ts/pages/governance/vote_index.tsx, packages/website/ts/utils/constants.ts
=> Add FAQ link to vote page

packages/asset-swapper/CHANGELOG.json
=> Asset-swapper fix changelog

packages/asset-swapper/src/quote_consumers/exchange_swap_quote_consumer.ts, packages/asset-swapper/src/quote_consumers/forwarder_swap_quote_consumer.ts, packages/asset-swapper/src/quote_consumers/swap_quote_consumer.ts, packages/asset-swapper/src/utils/assert.ts, packages/asset-swapper/src/utils/swap_quote_calculator.ts, packages/asset-swapper/src/utils/swap_quote_consumer_utils.ts, packages/asset-swapper/test/affiliate_fee_utils_test.ts, packages/asset-swapper/test/exchange_swap_quote_consumer_test.ts, packages/asset-swapper/test/forwarder_swap_quote_consumer_test.ts, packages/asset-swapper/test/swap_quote_calculator_test.ts, packages/asset-swapper/test/swap_quote_consumer_utils_test.ts, packages/asset-swapper/test/utils/swap_quote.ts
=> Add test coverage for asset-swapper

packages/website/ts/components/sections/landing/hero.tsx
=> Removed Banner

packages/asset-swapper/src/quote_consumers/exchange_swap_quote_consumer.ts, packages/asset-swapper/src/quote_consumers/forwarder_swap_quote_consumer.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/test/exchange_swap_quote_consumer_test.ts, packages/asset-swapper/test/forwarder_swap_quote_consumer_test.ts
=> Asset swapper renaming to -> toAddress

packages/0x.js/package.json, packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json, packages/asset-swapper/src/index.ts, packages/asset-swapper/src/quote_consumers/forwarder_swap_quote_consumer.ts, packages/asset-swapper/src/quote_consumers/swap_quote_consumer.ts, packages/asset-swapper/src/swap_quoter.ts, packages/monorepo-scripts/src/doc_gen_configs.ts, packages/website/md/docs/asset_swapper/installation.md, packages/website/md/docs/asset_swapper/introduction.md, packages/website/ts/containers/asset_swapper_documentation.ts, packages/website/ts/index.tsx, packages/website/ts/pages/documentation/doc_page.tsx, packages/website/ts/pages/documentation/docs_home.tsx, packages/website/ts/types.ts, yarn.lock
=> Version bump for asset-buyer and docs prep 1.0.0

packages/website/ts/containers/asset_swapper_documentation.ts
=> Removed react-docs from asset_swapper

contracts/exchange/test/fill_order.ts, contracts/test-utils/CHANGELOG.json, contracts/test-utils/package.json, contracts/test-utils/src/chai_setup.ts, contracts/test-utils/src/index.ts, contracts/test-utils/src/mocha_blockchain.ts, contracts/test-utils/src/test_with_reference.ts, contracts/test-utils/test/mocha_blockchain.ts, contracts/test-utils/test/subtests/mocha_blockchain_1.ts
This PR introduces various boilerplate reductions for smart contract tests via `@0x/contracts-test-utils`.
- `@0x/contracts-test-utils`
- Exports a `blockchainTests()` function that:
- Has similar semantics to `describe()`.
- Automatically spins up a `BlockchainLifecycle` on first call.
- Passes an "environment" object into the callback with many common requirements.
- Supports the following test suite "modifiers":
- `blockchainTests.skip`: Analogous to `describe.skip`.
- `blockchainTests.only`: Analogous to `describe.only`.
- `blockchainTests.optional`: Only runs if the `TEST_ALL` environment variable is set.
- `blockchainTests.resets`: Automatically calls `BlockchainLifecycle.startAsync()/revertAsync()` before/after every nested test case.
- Exports a custom `describe()` function that …
=> Mocha extensions for smart contract tests

packages/website/ts/components/modals/modal_contact.tsx
=> Change modal contact form

packages/asset-swapper/src/types.ts
=> Update comments for asset-swapper

packages/website/ts/components/footer.tsx, packages/website/ts/components/textList.tsx, packages/website/ts/index.tsx, packages/website/ts/pages/privacy.tsx, packages/website/ts/pages/terms.tsx, packages/website/ts/types.ts, packages/website/ts/utils/document_meta_constants.tsx
=> Privacy Policy and Terms of Service pages

contracts/exchange-libs/contracts/test/TestLibs.sol, contracts/exchange-libs/test/lib_eip712_exchange_domain.ts, contracts/exchange-libs/test/lib_order.ts, contracts/exchange-libs/test/lib_zero_ex_transaction.ts, contracts/utils/test/lib_eip712.ts, packages/utils/src/sign_typed_data_utils.ts
This PR adds unit tests to the `exchange-libs` package. All contracts are covered, and these changes predominately include tests to cover hashing. 
`yarn build && yarn test && yarn lint`
* Unit testing
=> `@0x:contracts-exchange-libs` Added unit tests to exchange-libs

packages/website/ts/components/footer.tsx, packages/website/ts/components/mobileNav.tsx
I deployed this already but wanted to make sure it passes CI.
=> Fix small issue on mobile nav

contracts/exchange/contracts/src/MixinAssetProxyDispatcher.sol, contracts/exchange/test/core.ts, contracts/exchange/test/dispatcher.ts
Remove `from != to` check from `_dispatchTransferFrom` and update related tests
=> remove from != to check and update tests

contracts/exchange/contracts/src/MixinWrapperFunctions.sol, contracts/exchange/contracts/src/interfaces/IWrapperFunctions.sol, contracts/exchange/test/wrapper.ts, contracts/exchange/test/wrapper_unit_tests.ts
=> Remove restrictions on maker/takerAssetData for marketBuy/Sell functions

contracts/exchange-libs/contracts/src/LibOrder.sol
A cheeky assertion to handle an exceptional internal error that should never arise.
=> Sanity check on order offset when hashing

packages/types/src/index.ts
=> Make `OrdersChannelSubscriptionOpts` conform to SRAv2

packages/abi-gen/templates/TypeScript/partials/method_abi_helper.handlebars, packages/abi-gen/test-cli/output/typescript/abi_gen_dummy.ts, packages/abi-gen/test-cli/output/typescript/test_lib_dummy.ts
While trying to address #2111, I noticed that the method signatures for `getABIDecodedTransactionData` and `getABIDecodedReturnData` looked fishy. The return signature for both methods was for the output type of the Solidity function. `getABIDecodedTransactionData` should return the input type, and `getABIDecodedReturnData` should return the output type. 
Tests passed because the ABI encoder/decoder was also passed the wrong types.
This PR fixes the decoding issue, and adds doc comments for all three methods. You can see the effect of these changes in `abi_gen_dummy.ts` (generated file). Resolves #2111
```typescript
getABIDecodedTransactionData(
callData: string,
): { input: { foo: BigNumber; bar: string; car: string }; lorem: string; ipsum: string; dolor: string } {
const self = (this as …
```
=> Fix ABI encoding/decoding functions

packages/asset-swapper/package.json
=> Change asset-swapper URL in package.json

packages/abi-gen/test-cli/test_typescript/test/abi_gen_dummy_test.ts
Adding different error types to `@0x/base-contract` resulted in this test failing. Not sure why it wasn't failing on CI before. This PR just updates the error type in the unit test.
CI should pass. 
=> Quick fix to abi-gen test

contracts/staking/contracts/src/StakingProxy.sol, contracts/staking/contracts/src/interfaces/IStakingEvents.sol, contracts/staking/contracts/src/interfaces/IStakingProxy.sol, contracts/staking/contracts/src/interfaces/IVaultCore.sol, contracts/staking/contracts/src/interfaces/IZrxVault.sol, contracts/staking/contracts/src/stake/MixinStake.sol, contracts/staking/contracts/src/stake/MixinStakeBalances.sol, contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol, contracts/staking/contracts/src/vaults/MixinVaultCore.sol, contracts/staking/contracts/src/vaults/ZrxVault.sol
=> Rename shadowed instances of `owner` to `staker`

contracts/staking/contracts/src/StakingProxy.sol, contracts/staking/contracts/src/fees/MixinExchangeManager.sol, contracts/staking/contracts/src/libs/LibStakingRichErrors.sol, contracts/staking/contracts/src/stake/MixinStake.sol, contracts/staking/contracts/src/sys/MixinParams.sol, contracts/staking/contracts/src/sys/MixinScheduler.sol, contracts/staking/test/exchange_test.ts, contracts/staking/test/migration.ts, contracts/utils/contracts/src/LibSafeMathRichErrors.sol, packages/order-utils/src/staking_revert_errors.ts
- Deletes unused rich reverts
- Renames `SomethingErrorCode` => `SomethingErrorCodes` everywhere for consistency
- Consolidates 2 rich reverts... I don't think there's actually a ton of room to do more
=> Cleanup rich reverts

contracts/staking/contracts/src/Staking.sol, contracts/staking/contracts/src/StakingProxy.sol, contracts/staking/contracts/src/fees/MixinExchangeFees.sol, contracts/staking/contracts/src/fees/MixinExchangeManager.sol, contracts/staking/contracts/src/stake/MixinStake.sol, contracts/staking/contracts/src/stake/MixinStakeBalances.sol, contracts/staking/contracts/src/stake/MixinStakeStorage.sol, contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol, contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol, contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol, contracts/staking/contracts/src/sys/MixinAbstract.sol, contracts/staking/contracts/src/sys/MixinFinalizer.sol, contracts/staking/contracts/src/sys/MixinParams.sol, contracts/staking/contracts/src/sys/MixinScheduler.sol, contracts/staking/contracts/src/vaults/ZrxVault.sol
=> Cleanup inheritance... again

.circleci/config.yml, packages/abi-gen-wrappers/src/generated-wrappers/asset_proxy_owner.ts, packages/abi-gen-wrappers/src/generated-wrappers/coordinator.ts, packages/abi-gen-wrappers/src/generated-wrappers/coordinator_registry.ts, packages/abi-gen-wrappers/src/generated-wrappers/dev_utils.ts, packages/abi-gen-wrappers/src/generated-wrappers/dummy_erc20_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/dummy_erc721_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/dutch_auction.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc1155_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc20_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc20_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc721_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/erc721_token.ts, packages/abi-gen-wrappers/src/generated-wrappers/exchange.ts, packages/abi-gen-wrappers/src/generated-wrappers/forwarder.ts, packages/abi-gen-wrappers/src/generated-wrappers/i_asset_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/multi_asset_proxy.ts, packages/abi-gen-wrappers/src/generated-wrappers/weth9.ts, packages/abi-gen-wrappers/src/generated-wrappers/zrx_token.ts, packages/abi-gen/templates/TypeScript/partials/method_tx.handlebars, packages/abi-gen/test-cli/output/typescript/abi_gen_dummy.ts
This line doesn't seem to be necessary anymore.
`estimateGasAsync` is defined at the same level as `sendTransactionAsync` so it can do its own binding within its own function definition. 
=> Remove unnecessary function binding

packages/asset-swapper/docs/reference.mdx, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/utils.ts, packages/asset-swapper/test/utils_test.ts
=> Feature asset-swapper smarter fee logic

.circleci/config.yml, package.json, packages/contract-artifacts/test/contract_artifacts_test.ts
Re-enable unit tests that were disabled on `3.0`.
Failing tests (still disabled):
- @0x/asset-buyer
- @0x/connect
- python tests
These mostly just need to be updated for the new order format.
Disabled tests (not touching):
- @0x/contracts-extensions
- @0x/contracts-coordinator
CI 🙌 
=> Enable tests on 3.0

packages/0x.js/src/index.ts, packages/testnet-faucets/package.json, packages/testnet-faucets/src/ts/handler.ts
This PR copies changes from #2147 and redos them on `3.0`.
=> Reduce exports from 0x.js

contracts/exchange/test/end-to-end/deployment.ts
=> Fix deployment and configuration tests

contracts/exchange/contracts/src/MixinAssetProxyDispatcher.sol, contracts/exchange/test/dispatcher.ts
=> Enforce assetData is padded to 32 bytes

contracts/staking/contracts/src/StakingProxy.sol, contracts/staking/contracts/src/immutable/MixinConstants.sol, contracts/staking/contracts/src/immutable/MixinStorage.sol, contracts/staking/contracts/src/stake/MixinStakeBalances.sol, contracts/staking/contracts/src/staking_pools/MixinCumulativeRewards.sol, contracts/staking/contracts/src/sys/MixinParams.sol
=> Separate immutable contracts, only inherit as needed

contracts/staking/contracts/src/immutable/MixinStorage.sol, contracts/staking/contracts/src/interfaces/IStructs.sol, contracts/staking/contracts/src/stake/MixinStake.sol, contracts/staking/contracts/src/stake/MixinStakeBalances.sol, contracts/staking/contracts/src/stake/MixinStakeStorage.sol, contracts/staking/contracts/src/staking_pools/MixinStakingPoolRewards.sol, contracts/staking/contracts/test/TestMixinStakeStorage.sol, contracts/staking/test/unit_tests/mixin_stake_storage_test.ts
This abstraction was unnecessarily confusing.
=> Remove `loadSyncedBalance` and `loadUnsyncedBalance`

contracts/utils/CHANGELOG.json, contracts/utils/contracts/src/Ownable.sol, contracts/utils/contracts/src/interfaces/IOwnable.sol, contracts/utils/test/ownable.ts
This pull request adds an "OwnershipTransferred" event to `IOwnable`, which will be emitted by `Ownable` when the `transferOwnership` function is successfully called. This change addresses auditor feedback regarding event emission in critical functions.
`yall`
=> Ownership Transferred Event

contracts/exchange/package.json, contracts/exchange/src/index.ts, contracts/exchange/test/assertion_wrappers/fill_order_wrapper.ts, contracts/exchange/test/balance_stores/balance_store.ts, contracts/exchange/test/balance_stores/blockchain_balance_store.ts, contracts/exchange/test/balance_stores/index.ts, contracts/exchange/test/balance_stores/local_balance_store.ts, contracts/exchange/test/balance_stores/types.ts, contracts/exchange/test/core.ts, contracts/test-utils/src/index.ts, contracts/test-utils/src/types.ts
New and improved `BalanceStore`, `BlockchainBalanceStore`, and `LocalBlockchainStore`:
- no longer rely on `ERC{20, 721, 1155}Wrapper`; `BlockchainBalanceStore` does all the balance fetching logic (but with more lodash magic 😏)
- better `expect` messages, e.g. 
Planning on using `BalanceStore` in a lot more places moving forward
=> BalanceStore++

contracts/staking/contracts/src/fees/MixinExchangeFees.sol, contracts/staking/contracts/src/immutable/MixinStorage.sol, contracts/staking/contracts/src/interfaces/IStakingEvents.sol, contracts/staking/contracts/src/interfaces/IStorage.sol, contracts/staking/contracts/src/interfaces/IStructs.sol, contracts/staking/contracts/src/libs/LibCobbDouglas.sol, contracts/staking/contracts/src/stake/MixinStakeBalances.sol, contracts/staking/contracts/src/sys/MixinFinalizer.sol, contracts/staking/contracts/test/TestDelegatorRewards.sol, contracts/staking/contracts/test/TestFinalizer.sol, contracts/staking/contracts/test/TestProtocolFees.sol, contracts/staking/contracts/test/TestStorageLayoutAndConstants.sol, contracts/staking/test/actors/finalizer_actor.ts, contracts/staking/test/unit_tests/finalizer_test.ts, contracts/staking/test/unit_tests/protocol_fees_test.ts, contracts/staking/test/utils/api_wrapper.ts
1. Removes state variables:
- totalWeightedStakeThisEpoch
- totalFeesCollectedThisEpoch
- numActivePoolsThisEpoch
2. No longer indexes by epoch % 2
3. Renamed event StakingPoolActivated → StakingPoolEarnedRewards.
4. Renamed structs:
- ActivePool → PoolStats. This holds stats for a pool that earned rewards.
- UnfinalizedState → AggregatedStats. This aggregates stats from the former struct.
=> Refactored finalization state.

contracts/staking/contracts/src/Staking.sol, contracts/staking/contracts/test/TestFinalizer.sol
Addresses C16
Took the easy way out in updating the finalizer tests; seemed like overkill to use the proxy pattern for those tests but 🤷‍♂ 
=> Remove payable fallback from Staking.sol

contracts/integrations/test/internal-integration-tests/exchange_integration_test.ts
=> `CI` Fix build failure

contracts/staking/contracts/src/fees/MixinExchangeFees.sol, contracts/staking/contracts/src/interfaces/IStaking.sol, contracts/staking/contracts/src/stake/MixinStake.sol, contracts/staking/test/unit_tests/protocol_fees_test.ts, contracts/staking/test/utils/cumulative_reward_tracking_simulation.ts
The fee hasn't necessarily been paid when the function is called. Seems more clear to call it `protocolFeeAmount`.
=> Replaced `protocolFeePaid` -> `protocolFeeAmount`

python-packages/contract_addresses/src/zero_ex/contract_addresses/__init__.py
I realized that they were missing.
Ensure CI runs clean, and compare addresses to https://github.com/0xProject/0x-monorepo/blob/development/packages/contract-addresses/src/index.ts
=> contract_addresses.py: Add DevUtils contract 

contracts/staking/contracts/test/TestMixinStakeBalances.sol, contracts/staking/src/artifacts.ts, contracts/staking/src/wrappers.ts, contracts/staking/test/unit_tests/stake_balances_test.ts, contracts/staking/tsconfig.json
Yooo, unit tests for `MixinStakeBalances`. 
\|ʘ‿ʘ)╯
__
=> Add MixinStakeBalances unit tests.

contracts/integrations/test/framework-unit-tests/function_assertion_test.ts, contracts/integrations/test/utils/function_assertions.ts
This PR implements `ContinuousFunctionAssertionSet` and `FunctionAssertionSequence`. These are both collections of function assertions that allow us to group function assertions into higher level simulations. 
- `ContinuousFunctionAssertionSet`: Runs registered function assertions continuously and randomly.
- `FunctionAssertionSequence`: Runs all of the registered function assertions in order.
`PKG=@0x/contracts-integrations yarn test`
=> Function Assertion Sets

contracts/integrations/test/actors/base.ts, contracts/integrations/test/actors/fee_recipient.ts, contracts/integrations/test/actors/hybrids.ts, contracts/integrations/test/actors/keeper.ts, contracts/integrations/test/actors/maker.ts, contracts/integrations/test/actors/pool_operator.ts, contracts/integrations/test/actors/staker.ts, contracts/integrations/test/actors/taker.ts, contracts/integrations/test/actors/tslint.json, contracts/integrations/test/actors/utils.ts, contracts/integrations/test/coordinator/coordinator_test.ts, contracts/integrations/test/coordinator/deploy_coordinator.ts, contracts/integrations/test/forwarder/deploy_forwarder.ts, contracts/integrations/test/forwarder/forwarder_test.ts, contracts/integrations/test/framework-unit-tests/function_assertion_test.ts, contracts/integrations/test/internal-integration-tests/fillorder_test.ts, contracts/integrations/test/utils/deployment_manager.ts, contracts/integrations/test/utils/function_assertions.ts, contracts/integrations/tslint.json
They call me the tslint whisperer
=> `@0x/contracts-integrations`: Enable tslint and fix lint errors

contracts/staking/test/unit_tests/mixin_scheduler_test.ts
Fixes intermittent test failure b removing block timestamp constraints from staking scheduler tests.
=> Fix development

contracts/dev-utils/src/wrappers.ts, contracts/exchange/src/balance_stores/balance_store.ts, contracts/exchange/src/balance_stores/blockchain_balance_store.ts, contracts/exchange/src/balance_stores/local_balance_store.ts, contracts/integrations/package.json, contracts/integrations/src/function_assertions.ts, contracts/integrations/test/actors/base.ts, contracts/integrations/test/actors/pool_operator.ts, contracts/integrations/test/actors/staker.ts, contracts/integrations/test/actors/tslint.json, contracts/integrations/test/deployment_manager.ts, contracts/integrations/test/framework-unit-tests/function_assertion_test.ts, contracts/integrations/test/function-assertions/createStakingPool.ts, contracts/integrations/test/function-assertions/decreaseStakingPoolOperatorShare.ts, contracts/integrations/test/function-assertions/index.ts, contracts/integrations/test/function-assertions/moveStake.ts, contracts/integrations/test/function-assertions/stake.ts, contracts/integrations/test/function-assertions/unstake.ts, contracts/integrations/test/internal-integration-tests/fillorder_test.ts, contracts/integrations/test/simulation/pool_management_fuzz_test.ts, contracts/integrations/test/simulation/pool_management_test.ts, contracts/integrations/test/simulation/simulation.ts, contracts/integrations/test/simulation/stake_management_test.ts, contracts/integrations/tslint.json, contracts/staking/src/index.ts, contracts/staking/src/types.ts, tsconfig.json, yarn.lock
First pass at the fuzzing framework. 
- Creates a `function-assertions` directory, where all `FunctionAssertion`s shall live. Each file corresponds to a contract function, and each function within a file returns a `FunctionAssertion` corresponding to a particular class of input (e.g. valid, invalid). Only valid assertions are implemented thus far.
- Generators corresponding to each contract function are added to their respective `Actor` mixins (in this PR, `Staker` and `PoolOperator`). This generator handles input generation for its own assertion. 
- A `Simulation` encapsulates a particular flow of interactions we would like to simulate/fuzz. The `_assertionGenerator` in a `Simulation` instance will typically instantiate some actors and/or simulations and subsequently choose one of their …
=> `@0x/contracts-integrations`: Pool management, stake management fuzz tests

contracts/staking/contracts/src/interfaces/IStakingEvents.sol
Clarified the documentation of the `epoch` parameter for the `RewardsPaid` event.
=> Updated `RewardsPaid` event docs

packages/asset-swapper/package.json, packages/orderbook/package.json, packages/orderbook/src/order_provider/mesh_order_provider.ts, yarn.lock
- Update `mesh-rpc-client` dep to latest version
=> Fix CI test-publish

packages/migrations/src/test_contract_configs.ts
=> Warn if Exchange contract not registered in StakingProxy

packages/migrations/Dockerfile
Fixes: https://github.com/0xProject/0x-mesh/issues/215
=> Extend keepAliveTimeout config on Ganache-cli Docker Image

.circleci/config.yml, packages/abi-gen/templates/Python/partials/method_class.handlebars, packages/abi-gen/test-cli/output/python/abi_gen_dummy/__init__.py, packages/abi-gen/test-cli/output/python/test_lib_dummy/__init__.py, python-packages/contract_addresses/setup.py, python-packages/contract_addresses/src/zero_ex/__init__.py, python-packages/contract_artifacts/setup.py, python-packages/contract_artifacts/src/zero_ex/__init__.py, python-packages/contract_wrappers/CHANGELOG.md, python-packages/contract_wrappers/setup.py, python-packages/contract_wrappers/src/zero_ex/__init__.py, python-packages/contract_wrappers/src/zero_ex/contract_wrappers/__init__.py, python-packages/contract_wrappers/src/zero_ex/contract_wrappers/bases.py, python-packages/contract_wrappers/src/zero_ex/contract_wrappers/tx_params.py, python-packages/contract_wrappers/test/test_exchange_wrapper.py, python-packages/json_schemas/setup.py, python-packages/json_schemas/src/zero_ex/__init__.py, python-packages/middlewares/setup.py, python-packages/middlewares/src/zero_ex/__init__.py, python-packages/order_utils/setup.py, python-packages/order_utils/src/zero_ex/__init__.py, python-packages/order_utils/src/zero_ex/order_utils/__init__.py, python-packages/sra_client/setup.py, python-packages/sra_client/src/zero_ex/sra_client/__init__.py, python-packages/sra_client/test/relayer/docker-compose.yml
OpenSea is integrating with 0x v2 (for now), and they've hit a bug and a lack of needed functionality, both of which have already been fixed/implemented in the v3/development branch, so this PR is to backport that functionality for them.
=> Python backports for OpenSea

contracts/coordinator/src/client/index.ts
Fix for typo in constructor and gas price to apply to meta transaction for the coordinator client.
=> Fix for typo in constructor and gas price to apply to meta transaction.

contracts/exchange-forwarder/contracts/src/MixinExchangeWrapper.sol, contracts/exchange-forwarder/contracts/src/MixinForwarderCore.sol, contracts/exchange-forwarder/contracts/src/MixinWeth.sol, contracts/exchange-forwarder/contracts/src/interfaces/IForwarderCore.sol, contracts/exchange-forwarder/contracts/src/libs/LibConstants.sol, contracts/exchange-forwarder/contracts/src/libs/LibForwarderRichErrors.sol, contracts/integrations/test/forwarder/bridge_test.ts, contracts/integrations/test/forwarder/forwarder_test.ts, contracts/integrations/test/forwarder/forwarder_test_factory.ts, contracts/integrations/test/framework/balances/local_balance_store.ts, packages/utils/src/revert_errors/exchange-forwarder/revert_errors.ts
- Changes the affiliate fee to a flat amount rather than a percentage
- Removes the cap on affiliate fee size (it isn't possible to deterministically calculate what % of trade size the new flat affiliate fee would be)
- Splits the affiliate fee between multiple recipients
=> Forwarder affiliate fee usability improvements

contracts/integrations/package.json, contracts/integrations/test/coordinator/client_test.ts
These were broken because `0x-coordinator-server` was using an incompatible version of the exchange contract for ABI decoding. 
Fixed here: https://github.com/0xProject/0x-coordinator-server/pull/21
CI
=> Re-enable coordinator client tests

.circleci/config.yml
Circle builds are failing when installing yarn:
```
#!/bin/bash -eo pipefail
npm install --global yarn@1.17.0
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/bin/yarn'
npm ERR! File exists: /usr/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-19T08_40_19_522Z-debug.log
```
See relevant issue [here](https://github.com/yarnpkg/yarn/issues/7773). Rather than waiting for a fix we can just force install.
-   [ ] Prefix PR title with `[WIP]` if …
=> Fix Circle builds

package.json
=> Fix bundlewatch for instant and passing static-test

contracts/integrations/test/dev-utils/get_order_hash.ts, contracts/integrations/test/dev-utils/lib_asset_data.ts, contracts/integrations/test/dev-utils/order_validation_utils.ts
Fixes the DevUtils tests and removes the `.only` modifier.
=> Fixed the DevUtils tests

packages/migrations/Dockerfile, packages/migrations/package.json
This was added in #2420 but then was discovered not to be working properly.
=> @0x/migrations/Dockerfile: Remove --timestamping arg from wget invocation

packages/utils/src/hex_utils.ts
Quick fix for a circular reference, which breaks rollup bundling.
=> Fix circular reference

contracts/erc1155/contracts/src/ERC1155.sol, contracts/erc1155/contracts/src/ERC1155Mintable.sol, contracts/erc1155/contracts/src/MixinNonFungibleToken.sol, contracts/erc1155/contracts/src/interfaces/IERC1155.sol, contracts/erc1155/contracts/src/interfaces/IERC1155Mintable.sol, contracts/erc1155/contracts/src/interfaces/IERC1155Receiver.sol, contracts/exchange/CHANGELOG.json, contracts/exchange/test/wrapper_unit_tests.ts, contracts/utils/CHANGELOG.json, packages/utils/src/abi_decoder.ts
Replaces ethers with the 0x Abi Encoder for decoding events. This fixes log decoding of some dynamic types. For example, event parameters that were arrays or objects did not decode properly. 
Example: An event with a 0x order.
```
[
"0x956663ee086aF4D6288CdEd57E343b96a7f410d8",
"0x25701A051Df3eFaC4fAcB7db65bA428a432F458e",
"0x535bE1A09C091F1534022508296Ff468407A8E7D",
"0xA2FA57c6fe23b89628EF763B0944f137B5fd8f05",
{
"_hex": "0x03a1c581bf944f1880"
},
{
"_hex": "0x016c7408a868dc49c0"
},
{
"_hex": "0x26d4ae483260be80"
},
{
"_hex": "0x0444ea314cb73b6c40"
},
{
"_hex": "0x5e1ebe0e"
},
{
"_hex": "0x8e1e5a9f5ac705b09876ba9f3e7291a7c0b7070715cba20286f70815d8bf8e31"
},
"0x7e6e4e052cf298fb6fefeb1539b8bce07e3dd32c6aefbde8d64fc3faab29535a6436", …
```
=> Fixes log decoding of dynamic data

packages/contract-addresses/README.md
Fixed name of the function in the contract-addresses package.
N/A
=> Fixed function name in README, network -> chain

packages/monorepo-scripts/src/test_installation.ts, packages/subproviders/package.json
Just applying the working fix from #2460
=> Bump maxBuffer?

contracts/erc20-bridge-sampler/contracts/src/ERC20BridgeSampler.sol, contracts/utils/CHANGELOG.json, contracts/utils/contracts/src/DeploymentConstants.sol, packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
Update the Eth2Dai market address as per [upgrade](https://www.reddit.com/r/MakerDAO/comments/euplem/oasisdex_contract_will_be_upgraded_on_8th_feb_2020/) and redeploy the contracts that depend on it (Eth2DaiBridge and ERC20BridgeSampler).
Also adds a gas stipend to devutils calls.
=> Update Eth2Dai address

contracts/exchange/README.md
Fixes a small typo in the exchange readme
-   [X] Update documentation as needed.
=> FIXES spelling in exchange readme

packages/asset-swapper/src/swap_quoter.ts, packages/instant/src/components/zero_ex_instant_provider.tsx
Stops polling SRA and etherscan gas price when unmounted.
=> [Fix] Instant call destroyAsync on unmount

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/utils/market_operation_utils/index.ts
=> [asset-swapper] Fix native fill prune

contracts/erc20-bridge-sampler/contracts/src/ERC20BridgeSampler.sol
=> Fix getLiquidityProviderFromRegistry

packages/sol-compiler/src/utils/compiler.ts
Duplicate of: https://github.com/0xProject/0x-monorepo/pull/2497. Moved to this PR so that a small change could be made.
=> Update resolver errors to include parent filename

packages/contract-addresses/package.json
=> Add private:publish to contract-addresses

packages/contract-wrappers/package.json
Add publish:private to @0x/contract-wrappers
=> Add gitpkg to contract-wrappers

packages/asset-swapper/src/quote_consumers/forwarder_swap_quote_consumer.ts
https://github.com/0xProject/0x-monorepo/pull/2521
=> [asset-swapper] Forwarder market sell throw when amount not sold

contracts/asset-proxy/CHANGELOG.json, contracts/asset-proxy/contracts/src/bridges/DexForwarderBridge.sol, contracts/asset-proxy/contracts/test/TestDexForwarderBridge.sol, contracts/asset-proxy/test/dex_forwarder_bridge.ts, packages/asset-swapper/src/utils/market_operation_utils/orders.ts, packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
* Add GST in DFB (modified due to too deep stack)
* Revert to older CurveBridge (without explicit GST support)
* Remove `LiquidityProvider` from DFB (for now)
=> Add GST support to DFB

packages/asset-swapper/src/swap_quoter.ts
Fixed a couple of dangling promises in `@0x/asset-swapper`.
=> [asset-swapper] Fixed dangling promises

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
Previous one had misconfigured deployment constants.
=> `@0x/contract-addresses`: Redeploy sampler on kovan

packages/asset-swapper/src/index.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/quote_requestor.ts
Please review individual commit messages.
Run automated (mocha) tests and view logging output.
=> asset-swapper: Improve logging for 0x API consumption

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json
`asset-swapper` tests have decided to suddenly time out on CI so I just increased the timeout.
=> asset-swapper: Increase timeout for tests.

contracts/zero-ex/contracts/src/features/ITransformERC20.sol, contracts/zero-ex/contracts/src/features/TransformERC20.sol, contracts/zero-ex/test/features/transform_erc20_test.ts
So bridges with authorized callers don't have to find a moving target.
=> Flip `TransformERC20.createTransformWallet()` to `onlyOwner`

packages/asset-swapper/src/utils/quote_requestor.ts, packages/asset-swapper/test/quote_requestor_test.ts
=> Quote Requestor Fix:  BigNumbers to Strings

packages/sol-profiler/CHANGELOG.json, packages/sol-profiler/src/cost_utils.ts, packages/sol-resolver/CHANGELOG.json, packages/sol-resolver/src/resolvers/fs_resolver.ts, packages/sol-resolver/src/resolvers/name_resolver.ts, packages/sol-resolver/src/resolvers/npm_resolver.ts, packages/sol-resolver/src/resolvers/relative_fs_resolver.ts, packages/sol-resolver/src/resolvers/url_resolver.ts, packages/sol-tracing-utils/CHANGELOG.json, packages/sol-tracing-utils/src/artifact_adapters/sol_compiler_artifact_adapter.ts
=> Fix sol-profiler bugs

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/utils/protocol_fee_utils.ts
Changes the ethgasstation URL in asset-swapper to our cached proxy url
=> fix: asset-swapper ethgasstation proxy url

packages/0x.js/package.json, packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/package.json, packages/asset-swapper/src/constants.ts, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/types.ts, packages/asset-swapper/src/utils/protocol_fee_utils.ts, packages/contract-wrappers-test/package.json, packages/orderbook/package.json
=> fix: asset-swapper ethgasstation url option

packages/asset-swapper/CHANGELOG.json, packages/asset-swapper/src/swap_quoter.ts, packages/asset-swapper/src/utils/protocol_fee_utils.ts, packages/asset-swapper/test/utils/mocks.ts
Use a singleton to prevent excess polling of the gas price oracle
=> feat: asset-swapper singleton gas price oracle

packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json
Deploys the new `FillQuoteTransformer` with cheaper bridge fills from #2608 to all networks.
=> Deploy FQT from #2608

contracts/utils/CHANGELOG.json, contracts/utils/contracts/src/DeploymentConstants.sol, packages/contract-addresses/CHANGELOG.json, packages/contract-addresses/addresses.json, packages/ethereum-types/CHANGELOG.json
DFB was incorrectly deployed on Kovan.
=> Redeploy DFB on kovan.
